"""`woof hex register`, `woof hex vertical` and `woof hex cull --parent-vertical`.

The chain under test is the one a mesh generated by anything but the point
door has to walk to reach a forecast: mint the vertical on the GLOBAL
parent, cut grid + static + vertical with one region, register the parent,
register the cut against it.  The mesh is a real ``rw_mpas_mesh`` sphere
(572 cells, generated in a fraction of a second); the static is synthetic --
the grid Earth-scaled plus the terrain and the derived-geometry slots a real
static carries -- because a real one reads a 16 GB terrain archive.  Tests
that need the generator skip by name when it is not on the engine ladder.
"""

from __future__ import annotations

import json
from pathlib import Path
import shutil
import subprocess
from types import SimpleNamespace

import numpy as np
import pytest

from woof.hex import mesh_rows
from woof.hex.cli import main as hex_main
from woof.hex.cull_door import CULL_ROLES, CullRefusal, check_parent_vertical
from woof.hex.register_door import RegisterRefusal, register_mesh
from woof.hex.vertical_door import REGIONAL_REFUSAL, VerticalDoorRefusal, mint_vertical

netCDF4 = pytest.importorskip("netCDF4")

EARTH_RADIUS_M = 6371229.0
#: Deliberately NOT 55: the level count must come from the vertical spec.
LEVELS = 7


def _engine() -> Path:
    from woof.hex.engines import MESH, EngineRefusal, resolve

    try:
        return resolve(MESH, None)
    except EngineRefusal as error:  # pragma: no cover - box-dependent
        pytest.skip(f"rw_mpas_mesh is not on the engine ladder: {error}")


def synthetic_static(grid: Path, out: Path) -> Path:
    """The grid, Earth-scaled, plus terrain and the slots a static carries."""

    shutil.copyfile(grid, out)
    with netCDF4.Dataset(str(out), "a") as ds:
        for name in ("dcEdge", "dvEdge", "nominalMinDc", "xCell", "yCell", "zCell",
                     "xEdge", "yEdge", "zEdge", "xVertex", "yVertex", "zVertex"):
            ds.variables[name][...] = np.asarray(ds.variables[name][...]) * EARTH_RADIUS_M
        for name in ("areaCell", "areaTriangle", "kiteAreasOnVertex"):
            ds.variables[name][...] = (
                np.asarray(ds.variables[name][...]) * EARTH_RADIUS_M ** 2
            )
        ds.setncattr("sphere_radius", EARTH_RADIUS_M)
        lat = np.asarray(ds.variables["latCell"][:])
        lon = np.asarray(ds.variables["lonCell"][:])
        ds.createVariable("ter", "f4", ("nCells",))[:] = (
            np.clip(np.sin(3.0 * lat) * np.cos(2.0 * lon), 0.0, None) * 2000.0
        ).astype("f4")
        for dim, size in (("TWO", 2), ("FIFTEEN", 15), ("R3", 3)):
            if dim not in ds.dimensions:
                ds.createDimension(dim, size)
        n_edges = len(ds.dimensions["nEdges"])
        ds.createVariable("deriv_two", "f4", ("nEdges", "TWO", "FIFTEEN"))[:] = (
            np.full((n_edges, 2, 15), 1.0e-12, dtype="f4")
        )
        for name, dims in (
            ("edgeNormalVectors", ("nEdges", "R3")),
            ("localVerticalUnitVectors", ("nCells", "R3")),
            ("cellTangentPlane", ("nCells", "TWO", "R3")),
            ("coeffs_reconstruct", ("nCells", "maxEdges", "R3")),
        ):
            ds.createVariable(name, "f4", dims)[...] = 0.0
    return out


def _generate(engine: Path, out: Path, background_km: float) -> Path:
    subprocess.run(
        [str(engine), "--background-km", str(background_km), "--out", str(out), "--clobber"],
        check=True, capture_output=True, text=True,
    )
    return out


@pytest.fixture(scope="module")
def chain(tmp_path_factory) -> SimpleNamespace:
    """Generate, mint the vertical, cull all three: once for the module."""

    engine = _engine()
    root = tmp_path_factory.mktemp("register-vertical")
    grid = _generate(engine, root / "g.grid.nc", 1000.0)
    static = synthetic_static(grid, root / "g.static.nc")
    spec = root / "vertical-spec.json"
    spec.write_text(json.dumps({
        "schema": "gpuwm-hex.vertical-spec/v1", "n_vert_levels": LEVELS,
        "ztop_m": 20000.0,
    }), encoding="utf-8")
    vertical = root / "g.vertical.nc"
    assert hex_main([
        "vertical", "--grid", str(grid), "--static", str(static),
        "--vertical-spec", str(spec), "-o", str(vertical),
    ]) == 0
    region = root / "region.json"
    region.write_text(json.dumps(
        {"kind": "cap", "center_deg": [40.0, -100.0], "radius_km": 4000.0}
    ), encoding="utf-8")
    cut = root / "cut"
    cut.mkdir()
    assert hex_main([
        "cull", "--parent-grid", str(grid), "--parent-static", str(static),
        "--parent-vertical", str(vertical), "--region", str(region),
        "--out-dir", str(cut), "--name", "c", "--engine", str(engine),
    ]) == 0
    return SimpleNamespace(
        engine=engine, root=root, grid=grid, static=static, spec=spec,
        vertical=vertical, region=region, cut=cut,
        cull_grid=cut / "c.grid.nc", cull_static=cut / "c.static.nc",
        cull_vertical=cut / "c.vertical.nc", cull_receipt=cut / "c.cull.json",
    )


def _quiet(*_args, **_kwargs) -> None:
    return None


def _register_pair(chain: SimpleNamespace, rows: Path, **extra) -> tuple:
    parent, _ = register_mesh(
        grid=chain.grid, static=chain.static, name="g1000", rows=rows,
        vertical_spec=chain.spec, log=_quiet,
    )
    cull, _ = register_mesh(
        grid=chain.cull_grid, static=chain.cull_static, name="c1000", rows=rows,
        parent_row="g1000", cull_receipt=chain.cull_receipt, log=_quiet, **extra,
    )
    return parent, cull


class Binding:
    def __init__(self, **kwargs):
        self.kwargs = kwargs
        self.name = kwargs["name"]


# ---------------------------------------------------------------------------
# the cull door's vertical role
# ---------------------------------------------------------------------------
def test_the_vertical_role_is_cut_after_the_static_and_before_the_init() -> None:
    roles = [role for role, _ in CULL_ROLES]
    assert roles == ["grid", "static", "vertical", "init"]


def test_the_culled_vertical_is_the_parent_restricted_to_the_cut_cells(chain) -> None:
    def coords(path: Path, kind: str) -> np.ndarray:
        with netCDF4.Dataset(str(path)) as ds:
            return np.stack([
                np.asarray(ds.variables[f"{axis}{kind}"][:], dtype=np.float64)
                for axis in ("x", "y", "z")
            ], axis=1)

    def lookup(parent: np.ndarray, child: np.ndarray) -> np.ndarray:
        scale = np.max(np.abs(parent))
        keys = {tuple(np.round(row / scale, 9)): i for i, row in enumerate(parent)}
        return np.array([keys[tuple(np.round(row / scale, 9))] for row in child])

    cells = lookup(coords(chain.vertical, "Cell"), coords(chain.cull_vertical, "Cell"))
    edges = lookup(coords(chain.vertical, "Edge"), coords(chain.cull_vertical, "Edge"))
    assert 0 < cells.size < 572
    with netCDF4.Dataset(str(chain.vertical)) as parent, \
            netCDF4.Dataset(str(chain.cull_vertical)) as child:
        assert len(child.dimensions["nVertLevels"]) == LEVELS
        for name in ("ter", "zgrid", "zz", "dss", "hx"):
            np.testing.assert_array_equal(
                np.asarray(child.variables[name][:]),
                np.asarray(parent.variables[name][:])[cells], err_msg=name,
            )
        for name in ("zxu", "zb", "zb3"):
            np.testing.assert_array_equal(
                np.asarray(child.variables[name][:]),
                np.asarray(parent.variables[name][:])[edges], err_msg=name,
            )
        for name in ("rdzw", "fzm", "fzp"):
            np.testing.assert_array_equal(
                np.asarray(child.variables[name][:]), np.asarray(parent.variables[name][:]),
            )
        # Lineage carried: the vertical stamp and spec digest survive the cut.
        assert child.getncattr("gpuwm_hex_vertical_spec_sha256") == \
            parent.getncattr("gpuwm_hex_vertical_spec_sha256")


def test_the_cull_receipt_records_digests_for_every_role(chain) -> None:
    receipt = json.loads(chain.cull_receipt.read_text(encoding="utf-8"))
    for role in ("grid", "static"):
        entry = receipt["files"][role]
        assert entry["out_sha256"] == mesh_rows.sha256_file(Path(entry["out"]))
        assert entry["parent_sha256"] == mesh_rows.sha256_file(Path(entry["parent"]))
    # No row pins the vertical (or an init), so the cull does not reread it.
    assert "out_sha256" not in receipt["files"]["vertical"]
    assert receipt["files"]["vertical"]["parent_vertical"]["n_vert_levels"] == LEVELS
    assert receipt["region_document"]["kind"] == "cap"


def test_a_parent_vertical_that_is_not_an_artifact_is_refused(chain) -> None:
    with pytest.raises(CullRefusal) as refusal:
        check_parent_vertical(chain.grid, chain.static)
    assert "not a vertical artifact" in str(refusal.value)


def test_a_parent_vertical_minted_on_another_mesh_is_refused(chain, tmp_path) -> None:
    other_grid = _generate(chain.engine, tmp_path / "o.grid.nc", 1200.0)
    with pytest.raises(CullRefusal) as refusal:
        check_parent_vertical(other_grid, chain.vertical)
    assert "minted on another mesh" in str(refusal.value)


# ---------------------------------------------------------------------------
# the vertical door
# ---------------------------------------------------------------------------
def test_the_vertical_door_takes_its_level_count_from_the_spec(chain) -> None:
    with netCDF4.Dataset(str(chain.vertical)) as ds:
        assert len(ds.dimensions["nVertLevels"]) == LEVELS
        assert int(ds.getncattr("config_nvertlevels")) == LEVELS
    receipt = json.loads(
        chain.vertical.with_name(chain.vertical.name + ".receipt.json").read_text()
    )
    assert receipt["invariants"]["n_vert_levels"] == LEVELS


def test_the_vertical_door_refuses_a_regional_grid_with_the_authority_message(chain, tmp_path) -> None:
    with pytest.raises(VerticalDoorRefusal) as refusal:
        mint_vertical(
            grid=chain.cull_grid, static=chain.cull_static,
            vertical_spec=chain.spec, output=tmp_path / "v.nc",
        )
    assert REGIONAL_REFUSAL in str(refusal.value)
    assert not (tmp_path / "v.nc").exists()


def test_the_vertical_door_refuses_to_overwrite_its_input(chain) -> None:
    with pytest.raises(VerticalDoorRefusal):
        mint_vertical(grid=chain.grid, static=chain.static,
                      vertical_spec=chain.spec, output=chain.static)


# ---------------------------------------------------------------------------
# register
# ---------------------------------------------------------------------------
def test_register_writes_a_global_and_a_cull_row_that_round_trip_and_bind(chain, tmp_path) -> None:
    rows = tmp_path / "mesh-rows.json"
    parent, cull = _register_pair(chain, rows)
    assert parent.kind == "generated-global" and parent.point_deg is None
    assert parent.n_levels == LEVELS and cull.n_levels == LEVELS
    assert parent.timestep_evidence == mesh_rows.ANCHORED_TIMESTEP_EVIDENCE
    assert parent.dt_seconds in {120.0, 100.0, 75.0}
    # The spec is the one the generator stamped on the grid.
    assert parent.region["background_km"] == 1000.0 and parent.spec_sha256
    with netCDF4.Dataset(str(chain.static)) as ds:
        assert parent.nominal_dx_m == float(np.float32(ds.variables["nominalMinDc"][:]))
    assert cull.parent_row == "g1000" and cull.boundary_zone_width == 7
    assert cull.cull_receipt == str(chain.cull_receipt.absolute())
    assert cull.cull_region["kind"] == "cap" and cull.cull_pad_scale is None
    assert mesh_rows.read_rows(rows) == [parent, cull]
    assert mesh_rows.GENERATED_GLOBAL_ROW_MARKER in parent.notes()
    assert mesh_rows.CULL_ROW_MARKER in cull.notes()
    patched = mesh_rows.apply_rows({}, Binding, rows)
    assert patched["c1000"].kwargs["boundary_zone_width"] == 7
    assert patched["g1000"].kwargs["n_levels"] == LEVELS


def test_register_reads_the_rows_file_from_the_environment(chain, tmp_path, monkeypatch) -> None:
    rows = tmp_path / "env-rows.json"
    monkeypatch.setenv(mesh_rows.MESH_ROWS_ENVIRONMENT, str(rows))
    assert hex_main([
        "register", "--grid", str(chain.grid), "--static", str(chain.static),
        "--name", "genv", "--vertical", str(chain.vertical),
    ]) == 0
    assert [row.name for row in mesh_rows.read_rows(rows)] == ["genv"]


def test_register_refuses_a_cull_whose_parent_row_is_absent(chain, tmp_path) -> None:
    with pytest.raises(RegisterRefusal) as refusal:
        register_mesh(
            grid=chain.cull_grid, static=chain.cull_static, name="c1", rows=tmp_path / "r.json",
            parent_row="nobody", cull_receipt=chain.cull_receipt, log=_quiet,
        )
    assert "is not in" in str(refusal.value)


def test_register_refuses_a_parent_row_without_a_cull_receipt(chain, tmp_path) -> None:
    with pytest.raises(RegisterRefusal) as refusal:
        register_mesh(grid=chain.cull_grid, static=chain.cull_static, name="c1",
                      rows=tmp_path / "r.json", parent_row="g1000", log=_quiet)
    assert "go together" in str(refusal.value)


def test_register_refuses_mismatched_cull_digests(chain, tmp_path) -> None:
    rows = tmp_path / "r.json"
    register_mesh(grid=chain.grid, static=chain.static, name="g1000", rows=rows,
                  vertical_spec=chain.spec, log=_quiet)
    receipt = json.loads(chain.cull_receipt.read_text(encoding="utf-8"))
    tampered = json.loads(json.dumps(receipt))
    tampered["files"]["static"]["out_sha256"] = "0" * 64
    bad_out = tmp_path / "out.cull.json"
    bad_out.write_text(json.dumps(tampered), encoding="utf-8")
    with pytest.raises(RegisterRefusal) as refusal:
        register_mesh(grid=chain.cull_grid, static=chain.cull_static, name="c1", rows=rows,
                      parent_row="g1000", cull_receipt=bad_out, log=_quiet)
    assert "moved after the cull" in str(refusal.value)
    tampered = json.loads(json.dumps(receipt))
    tampered["files"]["grid"]["parent_sha256"] = "1" * 64
    bad_parent = tmp_path / "parent.cull.json"
    bad_parent.write_text(json.dumps(tampered), encoding="utf-8")
    with pytest.raises(RegisterRefusal) as refusal:
        register_mesh(grid=chain.cull_grid, static=chain.cull_static, name="c1", rows=rows,
                      parent_row="g1000", cull_receipt=bad_parent, log=_quiet)
    assert "was not cut from that parent" in str(refusal.value)
    for role in ("grid", "static"):
        receipt["files"][role].pop("out_sha256")
    old = tmp_path / "old.cull.json"
    old.write_text(json.dumps(receipt), encoding="utf-8")
    with pytest.raises(RegisterRefusal) as refusal:
        register_mesh(grid=chain.cull_grid, static=chain.cull_static, name="c1", rows=rows,
                      parent_row="g1000", cull_receipt=old, log=_quiet)
    assert "re-run" in str(refusal.value)


def test_register_refuses_a_level_count_that_disagrees_with_the_parent(chain, tmp_path) -> None:
    rows = tmp_path / "r.json"
    register_mesh(grid=chain.grid, static=chain.static, name="g1000", rows=rows,
                  vertical_spec=chain.spec, log=_quiet)
    spec = tmp_path / "v9.json"
    spec.write_text(json.dumps({"schema": "gpuwm-hex.vertical-spec/v1", "n_vert_levels": 9}))
    with pytest.raises(RegisterRefusal) as refusal:
        register_mesh(grid=chain.cull_grid, static=chain.cull_static, name="c1", rows=rows,
                      parent_row="g1000", cull_receipt=chain.cull_receipt,
                      vertical_spec=spec, log=_quiet)
    assert "a cull moves no level" in str(refusal.value)


def test_register_refuses_a_regional_grid_as_global_and_a_global_as_cull(chain, tmp_path) -> None:
    with pytest.raises(RegisterRefusal) as refusal:
        register_mesh(grid=chain.cull_grid, static=chain.cull_static, name="x",
                      rows=tmp_path / "r.json", log=_quiet)
    assert "boundary zone" in str(refusal.value)


def test_register_refuses_an_unanchored_timestep_with_the_anchor_table_message(chain, tmp_path) -> None:
    with pytest.raises(RegisterRefusal) as refusal:
        register_mesh(grid=chain.grid, static=chain.static, name="g7",
                      rows=tmp_path / "r.json", dt_seconds=7.0, log=_quiet)
    assert "holds no timestep anchor" in str(refusal.value)
    assert not (tmp_path / "r.json").exists()
    row, _ = register_mesh(grid=chain.grid, static=chain.static, name="g20",
                           rows=tmp_path / "r.json", dt_seconds=20.0, log=_quiet)
    assert row.dt_seconds == 20.0
    assert row.timestep_evidence == mesh_rows.ANCHORED_TIMESTEP_EVIDENCE


def test_register_refuses_a_timestep_above_the_courant_limit_even_experimentally(chain, tmp_path) -> None:
    for experimental in (False, True):
        with pytest.raises(RegisterRefusal) as refusal:
            register_mesh(grid=chain.grid, static=chain.static, name="gbig",
                          rows=tmp_path / "r.json", dt_seconds=100000.0,
                          experimental=experimental, log=_quiet)
        assert "Courant limit" in str(refusal.value)


def test_the_experimental_lane_skips_only_the_anchor_and_labels_the_row(chain, tmp_path) -> None:
    rows = tmp_path / "r.json"
    with pytest.raises(RegisterRefusal) as refusal:
        register_mesh(grid=chain.grid, static=chain.static, name="gx",
                      rows=rows, experimental=True, log=_quiet)
    assert "needs an explicit dt" in str(refusal.value)
    parent, _ = register_mesh(grid=chain.grid, static=chain.static, name="gx", rows=rows,
                              dt_seconds=7.0, experimental=True, vertical_spec=chain.spec,
                              log=_quiet)
    assert parent.timestep_evidence == mesh_rows.EXPERIMENTAL_TIMESTEP_EVIDENCE
    assert parent.experimental and "EXPERIMENTAL-UNANCHORED" in parent.notes()
    # Its cull inherits the unanchored dt only on the same opt-in.
    with pytest.raises(RegisterRefusal) as refusal:
        register_mesh(grid=chain.cull_grid, static=chain.cull_static, name="cx", rows=rows,
                      parent_row="gx", cull_receipt=chain.cull_receipt, log=_quiet)
    assert "same explicit opt-in" in str(refusal.value)
    cull, _ = register_mesh(grid=chain.cull_grid, static=chain.cull_static, name="cx",
                            rows=rows, parent_row="gx", cull_receipt=chain.cull_receipt,
                            experimental=True, log=_quiet)
    assert cull.experimental and cull.dt_seconds == 7.0
    assert [row.timestep_evidence for row in mesh_rows.read_rows(rows)] == [
        "experimental-unanchored", "experimental-unanchored"]


def test_register_refuses_a_spec_that_is_not_the_grids_own(chain, tmp_path) -> None:
    spec = tmp_path / "other.json"
    spec.write_text(json.dumps({"background_km": 500.0, "regions": []}))
    with pytest.raises(RegisterRefusal) as refusal:
        register_mesh(grid=chain.grid, static=chain.static, name="g", rows=tmp_path / "r.json",
                      spec=spec, log=_quiet)
    assert "false lineage" in str(refusal.value)
    # The generator stamps the spec it PARSED: 1000 reads back as 1000.0 and
    # an omitted regions list as []; the file it was made from still matches.
    same = tmp_path / "same.json"
    same.write_text(json.dumps({"background_km": 1000}))
    row, _ = register_mesh(grid=chain.grid, static=chain.static, name="g",
                           rows=tmp_path / "r.json", spec=same, log=_quiet)
    assert row.spec_sha256 == mesh_rows.sha256_file(same)


def test_register_refuses_a_unit_sphere_grid_as_its_own_static(chain, tmp_path) -> None:
    with pytest.raises(RegisterRefusal) as refusal:
        register_mesh(grid=chain.grid, static=chain.grid, name="g",
                      rows=tmp_path / "r.json", log=_quiet)
    assert "unit-sphere" in str(refusal.value)


def test_register_refuses_without_a_rows_file(chain, monkeypatch) -> None:
    monkeypatch.delenv(mesh_rows.MESH_ROWS_ENVIRONMENT, raising=False)
    with pytest.raises(RegisterRefusal) as refusal:
        register_mesh(grid=chain.grid, static=chain.static, name="g", log=_quiet)
    assert "no row file" in str(refusal.value)


def test_register_refuses_a_name_the_shipped_registry_holds(chain, tmp_path) -> None:
    from woof.hex.register_door import shipped_mesh_names

    shipped = shipped_mesh_names()
    assert "x4.163842" in shipped
    with pytest.raises(RegisterRefusal) as refusal:
        register_mesh(grid=chain.grid, static=chain.static, name="x4.163842",
                      rows=tmp_path / "r.json", log=_quiet)
    assert "shipped registry row" in str(refusal.value)
    assert not (tmp_path / "r.json").exists()


def test_register_refuses_a_name_another_environment_row_file_holds(chain, tmp_path, monkeypatch) -> None:
    import os

    other = tmp_path / "other.json"
    register_mesh(grid=chain.grid, static=chain.static, name="gdup", rows=other, log=_quiet)
    target = tmp_path / "target.json"
    monkeypatch.setenv(mesh_rows.MESH_ROWS_ENVIRONMENT, os.pathsep.join([str(other), str(target)]))
    with pytest.raises(RegisterRefusal) as refusal:
        register_mesh(grid=chain.grid, static=chain.static, name="gdup", rows=target, log=_quiet)
    assert "already registered in" in str(refusal.value)


def test_an_experimental_cull_of_an_anchored_parent_keeps_the_anchored_label(chain, tmp_path) -> None:
    rows = tmp_path / "r.json"
    register_mesh(grid=chain.grid, static=chain.static, name="g1000", rows=rows,
                  vertical_spec=chain.spec, log=_quiet)
    cull, _ = register_mesh(grid=chain.cull_grid, static=chain.cull_static, name="c1",
                            rows=rows, parent_row="g1000", cull_receipt=chain.cull_receipt,
                            experimental=True, log=_quiet)
    assert cull.timestep_evidence == mesh_rows.ANCHORED_TIMESTEP_EVIDENCE


def test_the_pad_scale_is_derived_only_for_a_cap_on_the_parents_own_core(chain, tmp_path) -> None:
    rows = tmp_path / "r.json"
    parent, _ = register_mesh(grid=chain.grid, static=chain.static, name="g1000", rows=rows,
                              vertical_spec=chain.spec, log=_quiet)
    # Give the parent a point cap that is NOT the cut's centre.
    raw = parent.as_dict()
    raw.update(point_deg=[10.0, 20.0], core_radius_km=1000.0)
    mesh_rows.write_rows(rows, [mesh_rows.MeshRow.from_dict(raw)])
    cull, _ = register_mesh(grid=chain.cull_grid, static=chain.cull_static, name="c1",
                            rows=rows, parent_row="g1000", cull_receipt=chain.cull_receipt,
                            log=_quiet)
    assert cull.cull_pad_scale is None
    raw.update(point_deg=[40.0, -100.0])
    mesh_rows.write_rows(rows, [mesh_rows.MeshRow.from_dict(raw)])
    cull, _ = register_mesh(grid=chain.cull_grid, static=chain.cull_static, name="c2",
                            rows=rows, parent_row="g1000", cull_receipt=chain.cull_receipt,
                            log=_quiet)
    assert cull.cull_pad_scale == pytest.approx(4.0)


def test_a_parent_vertical_without_cell_centres_is_refused(chain, tmp_path) -> None:
    stripped = tmp_path / "no-lat.grid.nc"
    with netCDF4.Dataset(str(chain.grid)) as src, \
            netCDF4.Dataset(str(stripped), "w", format="NETCDF3_64BIT_OFFSET") as dst:
        for dim, value in src.dimensions.items():
            dst.createDimension(dim, len(value))
        for name in ("lonCell", "xCell"):
            var = src.variables[name]
            dst.createVariable(name, var.dtype, var.dimensions)[:] = var[:]
    with pytest.raises(CullRefusal) as refusal:
        check_parent_vertical(stripped, chain.vertical)
    assert "a size match alone is refused" in str(refusal.value)
