"""Generate lw_dump_state.F90 from the UNMODIFIED WRF v4.6.1 LW module.

Parses the declaration blocks of the rrlw_* data modules inside
phys/module_ra_rrtmg_lw.F and emits one dump subroutine per module, each
writing every non-parameter module variable through lw_binio.  Run once at
build time (lw_build.sh) so the dump list can never drift from the source:
a renamed or added module variable regenerates into the dump automatically.

Usage: python3 lw_gen_dumpers.py WRF_LW_SOURCE OUT_F90
"""

import re
import sys

MODULES = (
    [f"rrlw_kg{i:02d}" for i in range(1, 17)]
    + ["rrlw_ref", "rrlw_tbl", "rrlw_wvn", "rrlw_con", "rrlw_cld"]
)

DECL_RE = re.compile(
    r"^\s*(real\s*\(kind=rb\)|integer\s*\(kind=im\))\s*"
    r"(?:,\s*dimension\s*\(([^)]*)\)\s*)?::\s*(.*)$",
    re.IGNORECASE,
)


def split_names(rhs):
    """Split 'a(5,13,no1), b , c(2)' at top-level commas."""
    out, depth, cur = [], 0, []
    for ch in rhs:
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
        if ch == "," and depth == 0:
            out.append("".join(cur).strip())
            cur = []
        else:
            cur.append(ch)
    if cur and "".join(cur).strip():
        out.append("".join(cur).strip())
    return out


def rank_of(entry, dim_attr):
    m = re.match(r"^([a-z0-9_]+)\s*(?:\(([^)]*)\))?$", entry.strip(), re.I)
    if not m:
        raise SystemExit(f"unparsed declaration entity: {entry!r}")
    name, dims = m.group(1), m.group(2)
    if dims is None:
        dims = dim_attr
    if dims is None:
        return name, 0
    return name, dims.count(",") + 1


def parse_module(lines, mod):
    inside = False
    out = []
    start = re.compile(rf"^\s*module\s+{mod}\s*$", re.I)
    end = re.compile(rf"^\s*end\s+module\s+{mod}\s*$", re.I)
    for raw in lines:
        if start.match(raw):
            inside = True
            continue
        if inside and end.match(raw):
            break
        if not inside:
            continue
        line = raw.split("!")[0].rstrip()
        if not line or "parameter" in line.lower():
            continue
        m = DECL_RE.match(line)
        if not m:
            continue
        kind = "i" if m.group(1).lower().startswith("integer") else "r"
        dim_attr = m.group(2)
        for entry in split_names(m.group(3)):
            name, rank = rank_of(entry, dim_attr)
            if kind == "i" and rank > 1:
                raise SystemExit(f"{mod}/{name}: integer rank {rank} unsupported")
            out.append((name, kind, rank))
    if not out:
        raise SystemExit(f"module {mod}: no variables parsed")
    return out


def main():
    src, out_path = sys.argv[1], sys.argv[2]
    with open(src, "r", errors="replace") as fh:
        lines = fh.readlines()

    parts = [
        "! GENERATED by lw_gen_dumpers.py -- do not edit by hand.",
        "! Dumps every non-parameter variable of the rrlw_* data modules",
        "! (raw *o arrays as read from RRTMG_LW_DATA, plus the reduced",
        "! g-point arrays and tables produced by rrtmg_lw_ini).",
        "module lw_dump_state",
        "  use lw_binio",
        "  implicit none",
        "contains",
    ]
    subs = []
    for mod in MODULES:
        vars_ = parse_module(lines, mod)
        subs.append(f"dump_{mod}")
        parts.append(f"  subroutine dump_{mod}()")
        parts.append(f"    use {mod}")
        for name, kind, rank in vars_:
            parts.append(f"    call wr_{kind}{rank}('{mod}/{name}', {name})")
        parts.append(f"  end subroutine dump_{mod}")
        parts.append("")
    parts.append("  subroutine dump_all_state(path)")
    parts.append("    character(len=*), intent(in) :: path")
    parts.append("    call bio_open(path)")
    for s in subs:
        parts.append(f"    call {s}()")
    parts.append("    call bio_close()")
    parts.append("  end subroutine dump_all_state")
    parts.append("end module lw_dump_state")
    with open(out_path, "w", newline="\n") as fh:
        fh.write("\n".join(parts) + "\n")
    print(f"lw_dump_state.F90 written: {len(subs)} modules")


if __name__ == "__main__":
    main()
