#!/usr/bin/env bash
# Build + run the o3input=2 ozone-pipeline control against the UNMODIFIED
# WRF v4.6.1 sources.  Mirrors lw_build.sh's effective cpp state for the
# campaign bundle: EM_CORE=1, WRF_CHEM=0, HWRF=0, RWORDSIZE=4 (default REAL
# is FP32; DM_PARALLEL undefined so oznini's MPI block drops out).
#
# The four routines (lin_interpol2 + oznini from module_ra_cam_support.F,
# ozn_time_int + ozn_p_int from module_radiation_driver.F) are extracted
# VERBATIM by start/end line patterns into a generated wrapper module that
# supplies only the module-level state oznini uses (ozmixin_save etc.,
# transcribed from module_ra_cam_support.F lines 33-35) -- the physics
# statements themselves are byte-identical to the authority (modulo CR
# stripping); their SHA-256s are recorded beside the fixtures.
#
# usage: ozn_build.sh WRF_SOURCE_ROOT BUILD_DIR [INPUT_TXT OUT_DIR]
set -euo pipefail

if [[ $# -lt 2 ]]; then
    echo "usage: ozn_build.sh WRF_SOURCE_ROOT BUILD_DIR [INPUT_TXT OUT_DIR]" >&2
    exit 2
fi

source_root=$(realpath "$1")
build_dir=$(realpath -m "$2")
script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
cam_source="${source_root}/phys/module_ra_cam_support.F"
drv_source="${source_root}/phys/module_radiation_driver.F"

test -f "${cam_source}"
test -f "${drv_source}"
for f in ozone.formatted ozone_lat.formatted ozone_plev.formatted; do
    test -f "${source_root}/run/${f}"
done
mkdir -p "${build_dir}"
cd "${build_dir}"

FFLAGS="-O0 -cpp -ffree-form -ffree-line-length-none -fconvert=big-endian \
  -fallow-argument-mismatch -DEM_CORE=1 -DWRF_CHEM=0 -DHWRF=0 \
  -DRWORDSIZE=4 -DIWORDSIZE=4 -DDWORDSIZE=8 -DLWORDSIZE=4"

extract() { # extract FILE START_REGEX END_REGEX OUT
    awk -v s="$2" -v e="$3" '
        { sub(/\r$/, "") }
        $0 ~ s { grab = 1 }
        grab { print }
        $0 ~ e { grab = 0 }
    ' "$1" > "$4"
    if [[ ! -s "$4" ]]; then
        echo "ozn_build: extraction produced empty $4 (pattern $2)" >&2
        exit 3
    fi
}

# NOTE: patterns avoid regex metacharacters (awk -v mangles backslashes);
# uniqueness of each start line is asserted by the grep -c checks below.
extract "${cam_source}" '^[[:space:]]*function lin_interpol2' \
    '^[[:space:]]*end function lin_interpol2' ozn_x_lininterp2.f90
extract "${cam_source}" '^subroutine oznini' \
    '^END SUBROUTINE oznini' ozn_x_oznini.f90
extract "${drv_source}" '^SUBROUTINE ozn_time_int' \
    '^END SUBROUTINE ozn_time_int' ozn_x_timeint.f90
extract "${drv_source}" '^SUBROUTINE ozn_p_int' \
    '^END SUBROUTINE ozn_p_int' ozn_x_pint.f90

# Each extraction must hold exactly one routine.
grep -c '^[[:space:]]*function lin_interpol2(' ozn_x_lininterp2.f90 | grep -qx 1
grep -c '^subroutine oznini(' ozn_x_oznini.f90 | grep -qx 1
grep -c '^SUBROUTINE ozn_time_int(' ozn_x_timeint.f90 | grep -qx 1
grep -c '^SUBROUTINE ozn_p_int(' ozn_x_pint.f90 | grep -qx 1

{
    cat <<'EOF'
! GENERATED by ozn_build.sh -- verbatim WRF v4.6.1 routine extractions
! wrapped with the module state oznini expects (module_ra_cam_support.F
! module header lines: ozmixin_save/lat_ozone_save/plev_ozone_save,
! levsiz_ozone_save, have_ozone).  Do not edit; regenerate instead.
module ozn_oracle_mod
  implicit none

      real, pointer :: ozmixin_save(:,:,:,:), lat_ozone_save(:), plev_ozone_save(:)
      integer :: levsiz_ozone_save=-1
      logical :: have_ozone=.false.

contains

EOF
    cat ozn_x_lininterp2.f90
    echo
    cat ozn_x_oznini.f90
    echo
    cat ozn_x_timeint.f90
    echo
    cat ozn_x_pint.f90
    echo
    echo 'end module ozn_oracle_mod'
} > ozn_oracle_mod.F90

gfortran -c $FFLAGS "${script_dir}/lw_stub_wrf.F90"
gfortran -c $FFLAGS ozn_oracle_mod.F90
gfortran -c -O0 -ffree-form -ffree-line-length-none \
    "${script_dir}/lw_binio.F90"
# The MAIN program carries the same flags (gfortran takes the process-wide
# default I/O conversion from the main program); lw_binio pins
# convert='little_endian' per fixture unit, and the ozone climatology
# files are formatted text, so -fconvert does not touch them.
gfortran -c $FFLAGS -I "${build_dir}" "${script_dir}/ozn_extract.F90"
gfortran -o ozn_extract lw_stub_wrf.o ozn_oracle_mod.o lw_binio.o \
    ozn_extract.o

# Cheap uninitialized-variable lead sweep on the extracted authority code
# (charter: never be bit-exact to a bug).  Non-fatal; log kept.
gfortran -c $FFLAGS -O2 -Wall -Wno-unused-variable -Wno-unused-dummy-argument \
    -Wno-unused-label -o /dev/null ozn_oracle_mod.F90 \
    > ozn_warnings_O2.log 2>&1 || true

cp "${source_root}/run/ozone.formatted" \
   "${source_root}/run/ozone_lat.formatted" \
   "${source_root}/run/ozone_plev.formatted" .

if [[ $# -ge 4 ]]; then
    input_txt=$(realpath "$3")
    out_dir=$(realpath -m "$4")
    mkdir -p "${out_dir}"
    ./ozn_extract "${input_txt}" "${out_dir}"
    sha256sum "${cam_source}" "${drv_source}" \
        "${source_root}/run/ozone.formatted" \
        "${source_root}/run/ozone_lat.formatted" \
        "${source_root}/run/ozone_plev.formatted" \
        "${script_dir}/lw_stub_wrf.F90" "${script_dir}/lw_binio.F90" \
        "${script_dir}/ozn_extract.F90" \
        ozn_oracle_mod.F90 ozn_x_lininterp2.f90 ozn_x_oznini.f90 \
        ozn_x_timeint.f90 ozn_x_pint.f90 "${input_txt}" \
        > "${out_dir}/ozn_oracle_sha256sums.txt"
    ( cd "${out_dir}" && sha256sum ozn_fixture.bin \
        >> ozn_oracle_sha256sums.txt )
    gfortran --version | head -1 > "${out_dir}/ozn_compiler.txt"
fi
echo "ozn_build: OK"
