"""Build independent SPP fixtures from unmodified WRF v4.6.1 physics.

The existing deterministic harnesses are copied and given nonzero pattern
inputs. Source modules are never patched. GF's direct CUP_gf interface is
used because stock GFDRV discards its SPP pattern before that interface.
Run under nice on a CPU node, with OMP and BLAS threads capped externally.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import platform
import shutil
import subprocess

PINS = {
    "module_bl_mynn_common.F": "ba3e6909447408210fce490e95bdf2decc1e205d3446ddc5c715277d2b23924c",
    "module_bl_mynn.F": "b36c8b935cd9c8265359e78dbe8db285d99e992c7cab29917b5fca9d57d49452",
    "module_sf_mynn.F": "86395534a6c9bfc79dcad50094bce290eff05756777a95794b2673795f9761c3",
    "module_cu_gf_wrfdrv.F": "0cead99c913b6a74f3a492aea1e1c7ef6d34f95402574336022d1a6c716a4382",
    "module_cu_gf_deep.F": "798ad7271963757b88be36ce01e24222f7af045dc0692908d6e7c270d6b4ea11",
    "module_cu_gf_sh.F": "0dd1ed7c620b39e13f7ef77dc4ff1a269fa1f8d746492d360e203df0215b529a",
    "module_gfs_machine.F": "300ee4f75663e89d34c8a9b8733cc07a5dd48c3d973da019d31cb76524babe25",
    "module_gfs_physcons.F": "2b8ef99663ba62748b57c7002f5e5b8c9338f2a825c1d32c113bd4e3bff2eb52",
}


def once(text, old, new):
    if text.count(old) != 1:
        raise ValueError(f"SPP oracle harness anchor changed: {old!r}")
    return text.replace(old, new, 1)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--wrf-source", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--repo-root", type=Path, default=Path(__file__).resolve().parents[2])
    args = parser.parse_args()
    out = args.output.resolve()
    out.mkdir(parents=True, exist_ok=False)
    for name, pin in PINS.items():
        source = args.wrf_source / name
        if hashlib.sha256(source.read_bytes()).hexdigest() != pin:
            raise ValueError(f"WRF source bytes differ: {name}")
        shutil.copy2(source, out / name)
    env = dict(os.environ, OMP_NUM_THREADS="1", OPENBLAS_NUM_THREADS="1",
               MKL_NUM_THREADS="1", CUDA_VISIBLE_DEVICES="", GPUWM_NO_LOCAL_GPU="1")
    flags = ["gfortran", "-O0", "-ffp-contract=off", "-cpp", "-ffree-form", "-ffree-line-length-none"]
    commands = []
    def run(command):
        commands.append(command)
        subprocess.run(command, cwd=out, env=env, check=True)
    def compile(source):
        run(flags + ["-c", source])
    def harness(directory, name, replacements, output_name=None):
        text = (args.repo_root / "tools" / directory / name).read_text()
        for old, new in replacements:
            text = once(text, old, new)
        name = output_name or name
        (out / name).write_text(text)
        variant = "spp" if replacements else "off"
        (out / (Path(name).stem + "-" + variant + ".F90")).write_text(text)
        compile(name)
        return Path(name).stem
    pbl_dir = args.repo_root / "tools" / "mynn_pbl_wrf461_oracle"
    shutil.copy2(pbl_dir / "stub_wrf.F90", out / "stub_wrf.F90")
    compile("stub_wrf.F90")
    for name in ("module_bl_mynn_common.F", "module_bl_mynn.F", "module_sf_mynn.F"):
        compile(name)
    pbl_objects = ["stub_wrf.o", "module_bl_mynn_common.o", "module_bl_mynn.o"]
    specs = {
        "run_turbulence.F90": [
            ("rstoch(k) = 0.0", "rstoch(k) = 0.15 * real(c - 2)"),
            ("tkeprodtd, 0, rstoch)", "tkeprodtd, 1, rstoch)"),
            ("'pdk,pdt,pdq,pdc,el,qkw_unused,sm,sh'", "'pdk,pdt,pdq,pdc,el,qkw_unused,sm,sh,rstoch'"),
            ('I0,42(', 'I0,43('),
            ("sm(k), sh(k)\n", "sm(k), sh(k), rstoch(k)\n"),
        ],
        "run_condensation.F90": [
            ("spp_pbl = 0", "spp_pbl = 1"),
            ("rstoch(k) = 0.0", "rstoch(k) = 0.15 * real(mod(c,3) - 1)"),
        ],
        "run_dmp_mf.F90": [
            ("  spp_pbl = 0\n", "  spp_pbl = 1\n"),
            ("rstoch(k) = 0.0", "rstoch(k) = 0.1 * real(mod(c,5) - 2)"),
        ],
        "run_driver.F90": [
            ("bl_mynn_mixqt = 0, spp_pbl = 0", "bl_mynn_mixqt = 0, spp_pbl = 1"),
            ("pattern_spp_pbl(c, k) = 0.0", "pattern_spp_pbl(c, k) = 0.1 * real(c - 3)"),
        ],
    }
    for name, replacements in specs.items():
        program = harness("mynn_pbl_wrf461_oracle", name, replacements)
        run(["gfortran", "-o", program, *pbl_objects, program + ".o"])
        run(["./" + program, program.removeprefix("run_") + "-spp.csv"])
        # Same compiler and linked libm control. Existing checked-in fixtures
        # were generated by an older toolchain and are not this comparison.
        harness("mynn_pbl_wrf461_oracle", name, [])
        run(["gfortran", "-o", program, *pbl_objects, program + ".o"])
        run(["./" + program, program.removeprefix("run_") + "-off.csv"])
    high = [("dz(k) = 70.0 + 6.0 * real(k - 1)",
             "dz(k) = 1200.0 + 100.0 * real(k - 1)")]
    for active in (True, False):
        replacements = high + (specs["run_turbulence.F90"] if active else [])
        program = harness("mynn_pbl_wrf461_oracle", "run_turbulence.F90", replacements,
                          output_name="run_turbulence_high_" + ("on" if active else "off") + ".F90")
        run(["gfortran", "-o", program, *pbl_objects, program + ".o"])
        run(["./" + program, "turbulence-high-" + ("spp" if active else "off") + ".csv"])
    surface = harness("mynn_wrf461_oracle", "run_surface_layer_water.F90", [
        ("iz0tlnd = 0, spp_pbl = 0", "iz0tlnd = 0, spp_pbl = 1"),
        ("  rstoch1d = 0.0", "  do i=1,ncase\n    rstoch1d(i)=0.1 * real(mod(i,5) - 2)\n  enddo"),
        ('I0,59(', 'I0,60('),
        ("cpm(i, j), znt(i, j)\n", "cpm(i, j), znt(i, j), rstoch1d(i)\n"),
        ("'cka,cd,cda,wstar,qstar,cpm,znt'", "'cka,cd,cda,wstar,qstar,cpm,znt,rstoch'"),
    ])
    run(["gfortran", "-o", surface, "stub_wrf.o", "module_sf_mynn.o", surface + ".o"])
    run(["./" + surface, "surface-spp.csv", "surface-leaves-spp.csv"])
    harness("mynn_wrf461_oracle", "run_surface_layer_water.F90", [])
    run(["gfortran", "-o", surface, "stub_wrf.o", "module_sf_mynn.o", surface + ".o"])
    run(["./" + surface, "surface-off.csv", "surface-leaves-off.csv"])
    for name in ("module_gfs_machine.F", "module_gfs_physcons.F", "module_cu_gf_deep.F",
                 "module_cu_gf_sh.F", "module_cu_gf_wrfdrv.F"):
        compile(name)
    shutil.copy2(args.repo_root / "tools/gf_wrf461_oracle/gf_cases.F90", out / "gf_cases.F90")
    compile("gf_cases.F90")
    gf = harness("gf_wrf461_oracle", "run_cup_gf.F90", [
        ("    rand_clos(:, :) = 0.", "    rand_clos(:,1)=0.2\n    rand_clos(:,2)=-0.3\n"
         "    rand_clos(:,3)=0.4\n    rand_clos(:,4)=-0.5"),
    ])
    run(["gfortran", "-o", gf, "module_gfs_machine.o", "module_gfs_physcons.o",
         "module_cu_gf_deep.o", "module_cu_gf_sh.o", "module_cu_gf_wrfdrv.o",
         "gf_cases.o", gf + ".o"])
    run(["./" + gf, "gf-spp-levels.csv", "gf-spp-surface.csv", "gf-inert-stock-driver.csv"])
    gf_objects = ["module_gfs_machine.o", "module_gfs_physcons.o", "module_cu_gf_deep.o",
                  "module_cu_gf_sh.o", "module_cu_gf_wrfdrv.o", "gf_cases.o"]
    harness("gf_wrf461_oracle", "run_cup_gf.F90", [])
    run(["gfortran", "-o", gf, *gf_objects, gf + ".o"])
    run(["./" + gf, "gf-off-levels.csv", "gf-off-surface.csv", "gf-off-consistency.csv"])
    # Reuse the established PDF-value capture seam. The project gamma is
    # intentionally distinct; each native build must supply its own captures.
    for program in ("run_gf_stages", "run_gf_shallow"):
        harness("gf_wrf461_oracle", program + ".F90", [])
        run(["gfortran", "-o", program, *gf_objects, program + ".o"])
        stem = "gf-deep" if program == "run_gf_stages" else "gf-shallow"
        run(["./" + program, stem + "-levels.csv", stem + "-surface.csv", stem + "-consistency.csv"])
    receipt = {"wrf_version": "4.6.1", "source_pins": PINS, "commands": commands,
               "compiler": subprocess.check_output(["gfortran", "--version"], text=True).splitlines()[0],
               "libc": platform.libc_ver(),
               "files": {path.name: {"bytes": path.stat().st_size,
                           "sha256": hashlib.sha256(path.read_bytes()).hexdigest()}
                         for path in out.iterdir() if path.suffix in (".csv", ".F90")}}
    (out / "receipt.json").write_text(json.dumps(receipt, indent=2) + "\n")


if __name__ == "__main__":
    main()
