"""The radar site inventory a domain is planned against, and its one refusal.

Two questions come before a radar-assimilating case can be configured:

    sites_for_bbox(...)      which radars are inside this domain
    require_assimilable(...) and can their volumes actually be assimilated

The first is a lookup. The second is the one that matters, because the accurate
answer today for the European inventory is *no*, and the reason is a missing
number rather than a missing feed.

**Antenna elevation is the gate.** Beam height above ground is a function of
antenna height above mean sea level. A site assimilated with the wrong
antenna height places every gate at the wrong altitude, smoothly, with
nothing anywhere that looks like a failure -- the analysis is simply wrong
about where the storm is in the vertical. The frozen inventory carries
``elevation_m: null`` for every European site because the collection's
locations endpoint publishes a 2D point and the WMO registry its detail link
names answered ``totalCount: 0`` when probed on 2026-08-12.

So :func:`require_assimilable` refuses, by name, with the count. This is the
same rule the North-American antenna table is held to and for the same
reason: a placeholder elevation does not make a site usable, it makes an
unusable site *look* usable, and the campaign that discovers this is the one
that already ran.

Reflectivity *composites* are unaffected and are the route that works today
(:mod:`woof.obs.opera`): a composite is a georeferenced 2D grid and needs no
antenna geometry at all.

Nothing here names a country. WMO block numbers and station ids are data in
``data/radar_sites_odim.json``, regenerated by ``tools/freeze_radar_sites.py``.
"""

from __future__ import annotations

from dataclasses import dataclass
from functools import lru_cache
import json
from pathlib import Path

#: The schema the frozen inventory must declare.
TABLE_SCHEMA = "gpuwm-obs.radar-sites.v1"

#: The shipped inventory, beside this module.
TABLE_PATH = Path(__file__).resolve().parent / "data" / "radar_sites_odim.json"


class RadarSiteError(RuntimeError):
    """The inventory cannot answer, and the reason is the message."""


class SiteNotAssimilableError(RadarSiteError):
    """A site exists and is not usable, and the message says what is missing.

    A distinct class from :class:`RadarSiteError` because the two lead
    somewhere different: "no radar covers this domain" is a fact about
    geography and ends the plan, while this is a fact about metadata and is
    fixed by supplying it.
    """


@dataclass(frozen=True)
class RadarSite:
    """One radar, and what is known about it."""

    id: str
    name: str
    wmo_block: str | None
    latitude: float
    longitude: float
    #: Antenna height above mean sea level, or ``None`` when the archive
    #: does not publish one. ``None`` and ``0.0`` are different statements
    #: and are kept different: the first says nobody knows, the second says
    #: the antenna is at sea level.
    elevation_m: float | None
    moments: tuple[str, ...]
    methods: tuple[str, ...]
    has_velocity: bool
    has_volume_scan: bool

    @property
    def has_elevation(self) -> bool:
        return self.elevation_m is not None

    def inside(self, west: float, south: float, east: float,
               north: float) -> bool:
        return (south <= self.latitude <= north
                and west <= self.longitude <= east)


@dataclass(frozen=True)
class RadarSiteTable:
    """The frozen inventory, with the provenance of the listing behind it."""

    schema: str
    source_url: str
    source_sha256: str
    frozen_at: str
    elevation_basis: str
    sites: tuple[RadarSite, ...]

    def __len__(self) -> int:
        return len(self.sites)

    def by_id(self, site_id: str) -> RadarSite:
        for site in self.sites:
            if site.id == site_id:
                return site
        raise RadarSiteError(
            f"no radar {site_id!r} in the inventory of {len(self)}")


def _load(path: Path) -> RadarSiteTable:
    try:
        document = json.loads(path.read_text(encoding="utf-8"))
    except OSError as error:
        raise RadarSiteError(
            f"cannot read the radar site inventory at {path}: {error}. "
            f"Regenerate it with tools/freeze_radar_sites.py") from error
    except json.JSONDecodeError as error:
        raise RadarSiteError(f"{path} is not JSON: {error}") from error
    schema = str(document.get("schema", ""))
    if schema != TABLE_SCHEMA:
        raise RadarSiteError(
            f"{path} declares schema {schema!r}, expected {TABLE_SCHEMA!r}")
    rows = document.get("sites") or ()
    if not rows:
        raise RadarSiteError(
            f"{path} lists no radar; an empty inventory reports every domain "
            f"as uncovered, which is indistinguishable from a domain that "
            f"genuinely has no radar")
    sites = []
    seen: set[str] = set()
    for row in rows:
        site_id = str(row["id"])
        if site_id in seen:
            raise RadarSiteError(
                f"{path} lists radar {site_id!r} twice; which row is the "
                f"radar would then be an ordering accident")
        seen.add(site_id)
        elevation = row.get("elevation_m")
        sites.append(RadarSite(
            id=site_id,
            name=str(row.get("name", "")),
            wmo_block=(None if row.get("wmo_block") is None
                       else str(row["wmo_block"])),
            latitude=float(row["latitude"]),
            longitude=float(row["longitude"]),
            elevation_m=None if elevation is None else float(elevation),
            moments=tuple(str(m) for m in row.get("moments", ())),
            methods=tuple(str(m) for m in row.get("methods", ())),
            has_velocity=bool(row.get("has_velocity", False)),
            has_volume_scan=bool(row.get("has_volume_scan", False)),
        ))
    sites.sort(key=lambda site: site.id)
    return RadarSiteTable(
        schema=schema,
        source_url=str(document.get("source_url", "")),
        source_sha256=str(document.get("source_sha256", "")),
        frozen_at=str(document.get("frozen_at", "")),
        elevation_basis=str(document.get("elevation_basis", "")),
        sites=tuple(sites),
    )


@lru_cache(maxsize=4)
def load_table(path: str | Path | None = None) -> RadarSiteTable:
    """The frozen inventory, read once per path."""

    return _load(Path(path) if path is not None else TABLE_PATH)


def sites_for_bbox(west: float, south: float, east: float, north: float, *,
                   table: RadarSiteTable | None = None,
                   require_velocity: bool = False) -> tuple[RadarSite, ...]:
    """Every radar inside the domain, sorted by id.

    ``require_velocity`` keeps only sites that serve a radial-velocity
    moment. It changes *which* sites come back and never whether they are
    assimilable -- that is :func:`require_assimilable`'s question, and
    answering both here would let a caller check one and believe it had
    checked the other.
    """

    if south >= north or west >= east:
        raise RadarSiteError(
            f"({west}, {south}, {east}, {north}) is not a domain box")
    table = table or load_table()
    found = tuple(
        site for site in table.sites
        if site.inside(west, south, east, north)
        and (site.has_velocity or not require_velocity))
    return found


def require_assimilable(sites, *, need_velocity: bool = True) -> tuple[RadarSite, ...]:
    """The sites in ``sites`` whose volumes can accurately be assimilated.

    Raises :class:`SiteNotAssimilableError` naming every site that cannot,
    and why. It never returns a shortened list quietly: a caller that asked
    for eleven radars and silently got three would run a thinner analysis
    than it configured and report the same success either way.
    """

    sites = tuple(sites)
    if not sites:
        raise RadarSiteError(
            "no radar was offered for assimilation; an empty set assimilates "
            "nothing and reports the same success as a full one")
    missing_elevation = [site for site in sites if not site.has_elevation]
    missing_velocity = ([site for site in sites if not site.has_velocity]
                        if need_velocity else [])
    missing_volume = [site for site in sites if not site.has_volume_scan]
    if missing_elevation or missing_velocity or missing_volume:
        reasons = []
        if missing_elevation:
            reasons.append(
                f"{len(missing_elevation)} of {len(sites)} have no antenna "
                f"elevation ({', '.join(s.id for s in missing_elevation[:5])}"
                f"{', ...' if len(missing_elevation) > 5 else ''}). Beam "
                f"height above ground is a function of antenna height, so "
                f"assimilating without one puts every gate at the wrong "
                f"altitude with nothing that looks like a failure")
        if missing_velocity:
            reasons.append(
                f"{len(missing_velocity)} serve no radial-velocity moment "
                f"({', '.join(s.id for s in missing_velocity[:5])})")
        if missing_volume:
            reasons.append(
                f"{len(missing_volume)} publish no volume scan "
                f"({', '.join(s.id for s in missing_volume[:5])})")
        raise SiteNotAssimilableError(
            "; ".join(reasons)
            + ". Refusing rather than assimilating a subset or substituting a "
              "placeholder: a placeholder does not make a site usable, it "
              "makes an unusable site look usable")
    return sites


def coverage_summary(table: RadarSiteTable | None = None) -> dict:
    """Counts a plan can be judged on, without reading 136 rows."""

    table = table or load_table()
    return {
        "sites": len(table),
        "with_velocity": sum(1 for s in table.sites if s.has_velocity),
        "with_volume_scan": sum(1 for s in table.sites if s.has_volume_scan),
        "with_elevation": sum(1 for s in table.sites if s.has_elevation),
        "wmo_blocks": len({s.wmo_block for s in table.sites
                           if s.wmo_block is not None}),
        "frozen_at": table.frozen_at,
    }


__all__ = ["RadarSite", "RadarSiteError", "RadarSiteTable",
           "SiteNotAssimilableError", "TABLE_PATH", "TABLE_SCHEMA",
           "coverage_summary", "load_table", "require_assimilable",
           "sites_for_bbox"]
