"""Which surface-observation networks cover a domain, anywhere on Earth.

``rw_asos`` was already worldwide: its archive URL, its ``--networks`` list
and its ``--bbox`` are all arguments, and the network id is concatenated into
a URL template rather than branched on. What was missing was the step before
it -- given a domain, *which* networks to name. Passing the wrong ones is not
an error anyone sees: the fetch succeeds, the station table comes back short
or empty, and the case is scored against fewer observations than exist.

So this module owns one question and answers it from a frozen table:

    networks_for_bbox(west, south, east, north) -> ("DE__ASOS", "CZ__ASOS", ...)

**The extent is a candidate screen, not the filter.** Each row carries the
bounding box the archive publishes for that network, and that box is the
archive's own claim, padded and sometimes stale -- one European network
declares a southern edge in the tropics. Measured on 2026-08-12 against the
live station lists of twelve networks across three continents, every declared
extent *contained* its stations, with the archive padding each edge by 0.1
deg. So the screen errs toward including a network whose stations turn out to
lie elsewhere, and never toward dropping one.

That direction is the one that matters and it is the one this module is
built around. Including a network that contributes nothing costs one metadata
request. Dropping one costs observations, silently. The authoritative filter
is the station-level ``--bbox`` that ``rw_asos stations`` already applies to
real station coordinates; this module's job is only to make sure the right
networks were offered to it.

**What a longitude pair means is not decided here.** A network extent is the
eastward interval from ``west``, running past +180 when the network straddles
the antimeridian, and a caller's box is read the same way: ``west`` greater
than ``east`` is the box that crosses 180E. That reading belongs to
:class:`woof.fetch.Area`, which already decides it for an ``--area`` --
which pair crosses the antimeridian, and where each edge sits on the
``[-180, 180]`` branch -- and this module calls that same object rather than
restating it, so one ordered ``(west, east)`` pair is one box at both doors.

The step before that reading is not shared, and the boundary matters. An
``--area`` arrives as two corners with no west among them:
:func:`woof.fetch.parse_area` sorts them and then reads a span wider than
180 degrees as the complementary crossing box, so ``45,-170,55,170`` and
``45,170,55,-170`` are both the 20-degree Pacific box. A domain box arrives
already ordered and nothing here reorders it: ``(-170, 45, 170, 55)`` is the
340-degree box that excludes the Pacific, and ``(170, 45, -170, 55)`` is the
20-degree one that is it. So four numbers name one box at both doors once a
caller has said which edge is west, and only then.

Edges written in the ``[0, 360]`` convention land on the signed branch
before anything reads them, and ``(250, 30, 260, 40)`` and
``(-110, 30, -100, 40)`` are one box. Those are the two conventions the
box accepts; a longitude in neither is refused with the interval named,
because wrapping it would turn a coordinate off the globe into a legal box.

Nothing here names a country in code. Network ids and their boxes are data in
``data/surface_networks.json``, regenerated by
``tools/freeze_surface_networks.py``.
"""

from __future__ import annotations

from dataclasses import dataclass
from functools import lru_cache
import json
from pathlib import Path

from woof.fetch import Area

#: The schema the frozen table must declare.
TABLE_SCHEMA = "gpuwm-obs.surface-networks.v1"

#: Where the frozen table lives, beside this module.
TABLE_PATH = Path(__file__).resolve().parent / "data" / "surface_networks.json"


class SurfaceNetworkError(RuntimeError):
    """The network table cannot answer, and the reason is the message."""


def _area(west: float, east: float) -> Area:
    """The longitude pair handed to the object that reads longitude pairs.

    Only the two edges are in question here and :class:`woof.fetch.Area`
    reads them without reference to the band, so the latitudes are a
    placeholder.
    """

    return Area(lat_south=0.0, lon_west=west, lat_north=0.0, lon_east=east)


def _canonical_longitudes(west: float, east: float) -> tuple[float, float]:
    """``west`` on the ``[-180, 180]`` branch, ``east`` carried east of it.

    One statement of the rule and it is not this module's:
    :attr:`Area.crosses_antimeridian` decides whether the eastward walk
    passes +180 and :meth:`Area.as_cds` puts both edges on the signed
    branch, so the screen and the fetch layer read one pair one way.

    Idempotent by construction: ``west`` comes back inside ``[-180, 180)``
    and ``east`` inside ``(-180, 180]`` or that plus 360, and feeding either
    form back returns it unchanged. That is what lets a refusal name the
    pair the screen actually compared.
    """

    area = _area(west, east)
    _, branch_west, _, branch_east = area.as_cds()
    if area.crosses_antimeridian:
        branch_east += 360.0
    return (branch_west, branch_east)


def _longitude_pieces(west: float,
                      east: float) -> tuple[tuple[float, float], ...]:
    """``[west, east]`` as one or two intervals inside ``[-180, 180]``.

    An ``east`` running past +180 is how a network extent and a canonical
    domain box both say "the eastward walk from west to east passes the
    antimeridian". One function decomposes both, so the two sides of
    :meth:`SurfaceNetwork.intersects` can never be compared on different
    branches.
    """

    if east <= 180.0:
        return ((west, east),)
    return ((west, 180.0), (-180.0, east - 360.0))


def _pieces_meet(first_west: float, first_east: float, second_west: float,
                 second_east: float) -> bool:
    """Do two intervals inside ``[-180, 180]`` share at least one meridian?

    Touching counts, and the cut the pieces were made on is not a place on
    the globe: -180 and +180 are one meridian, so an interval ending at the
    antimeridian and one beginning at the other spelling of it graze exactly
    the way two intervals meeting at 0 do. Comparing the four numbers alone
    would call that the width of the world apart, which is the one contact
    a screen that never drops a network cannot miss.
    """

    if not (second_east < first_west or second_west > first_east):
        return True
    return ((first_east == 180.0 and second_west == -180.0)
            or (first_west == -180.0 and second_east == 180.0))


def _in_a_convention(west: float, east: float) -> bool:
    """Is each edge a longitude one of the two accepted conventions spells?

    ``[-180, 180]`` and ``[0, 360]`` between them cover ``[-180, 360]``, and
    an edge is read in whichever of the two can spell it -- which is one
    reading, because the conventions agree wherever they overlap. ``east``
    may also run once past the end, as far as ``west + 360``: that carried
    spelling is how an extent and :func:`_canonical_longitudes` both write a
    walk that passed the branch end, so the box accepts what this module
    itself hands back. A value in neither, such as -190, is refused rather
    than wrapped: wrapping it would turn a coordinate off the globe into a
    legal 205-degree crossing box.
    """

    return (-180.0 <= west <= 360.0
            and -180.0 <= east <= max(360.0, west + 360.0))


@dataclass(frozen=True)
class SurfaceNetwork:
    """One network the archive holds, and where its stations actually are.

    ``east`` may exceed ``+180``. That is not a coordinate error: a network
    whose stations straddle the antimeridian has no representation as a
    single ``west <= east`` interval inside ``[-180, 180]``, and the
    alternative -- ``min``/``max`` over the raw longitudes -- produces a box
    spanning nearly the whole globe. New Zealand reports stations near +178
    and near -176, so that box would be ``[-176, 178]`` and would match
    domains in the South Atlantic. The interval is stored as the shortest one
    that contains every station, running past +180 when it must, and
    :meth:`intersects` reads it in both pieces.
    """

    id: str
    name: str
    west: float
    south: float
    east: float
    north: float
    #: How many stations the extent was measured over, when the table records
    #: it. Carried for the receipt, never for the screen.
    stations: int | None = None

    @property
    def crosses_antimeridian(self) -> bool:
        """The same question, asked of the same object, as for a domain box."""

        return _area(self.west, self.east).crosses_antimeridian

    def intersects(self, west: float, south: float, east: float,
                   north: float) -> bool:
        """Does this network's extent overlap the box at all?

        Touching counts. A domain whose edge grazes a network's edge may
        still hold one of its stations, and the station-level filter is what
        decides that; excluding on a shared boundary here would drop the
        chance to ask.

        The box is canonicalized here so a caller holding raw edges gets the
        same answer as one holding the pair :func:`_check_box` handed back;
        :func:`_canonical_longitudes` is idempotent, so the second reading
        of an already-canonical pair changes nothing. Both sides are then
        decomposed by :func:`_longitude_pieces`, so a Pacific domain is
        compared against a Pacific extent piece by piece instead of against
        the wide complement of one, and the pieces are compared by
        :func:`_pieces_meet`, which knows that the cut they were made on is
        one meridian and not two.
        """

        if self.north < south or self.south > north:
            return False
        box_pieces = _longitude_pieces(*_canonical_longitudes(west, east))
        return any(
            _pieces_meet(extent_west, extent_east, piece_west, piece_east)
            for extent_west, extent_east in _longitude_pieces(self.west,
                                                              self.east)
            for piece_west, piece_east in box_pieces)


@dataclass(frozen=True)
class SurfaceNetworkTable:
    """The frozen table, with the provenance of the listing it came from."""

    schema: str
    source_url: str
    source_sha256: str
    frozen_at: str
    networks: tuple[SurfaceNetwork, ...]

    def __len__(self) -> int:
        return len(self.networks)


def _load(path: Path) -> SurfaceNetworkTable:
    try:
        raw = path.read_text(encoding="utf-8")
    except OSError as error:
        raise SurfaceNetworkError(
            f"cannot read the surface-network table at {path}: {error}. "
            f"Regenerate it with tools/freeze_surface_networks.py") from error
    try:
        document = json.loads(raw)
    except json.JSONDecodeError as error:
        raise SurfaceNetworkError(
            f"{path} is not JSON: {error}") from error
    schema = str(document.get("schema", ""))
    if schema != TABLE_SCHEMA:
        raise SurfaceNetworkError(
            f"{path} declares schema {schema!r}, expected {TABLE_SCHEMA!r}")
    rows = document.get("networks") or ()
    if not rows:
        raise SurfaceNetworkError(
            f"{path} lists no networks; an empty table resolves every domain "
            f"to no observations, which is indistinguishable from a domain "
            f"the archive genuinely does not cover")
    networks = []
    seen: set[str] = set()
    for row in rows:
        network = str(row["id"])
        if network in seen:
            raise SurfaceNetworkError(
                f"{path} lists network {network!r} twice; which extent is "
                f"the network's would then be an ordering accident")
        seen.add(network)
        stations = row.get("stations")
        entry = SurfaceNetwork(
            id=network,
            name=str(row.get("name", "")),
            west=float(row["west"]),
            south=float(row["south"]),
            east=float(row["east"]),
            north=float(row["north"]),
            stations=None if stations is None else int(stations),
        )
        if not (-90.0 <= entry.south <= entry.north <= 90.0):
            raise SurfaceNetworkError(
                f"{path}: network {network!r} spans latitudes "
                f"[{entry.south}, {entry.north}], which is not a band on the "
                f"globe")
        if not (-180.0 <= entry.west <= entry.east <= 540.0):
            raise SurfaceNetworkError(
                f"{path}: network {network!r} spans longitudes "
                f"[{entry.west}, {entry.east}]; an extent runs west to east "
                f"and may pass +180 once, never further")
        networks.append(entry)
    networks.sort(key=lambda entry: entry.id)
    return SurfaceNetworkTable(
        schema=schema,
        source_url=str(document.get("source_url", "")),
        source_sha256=str(document.get("source_sha256", "")),
        frozen_at=str(document.get("frozen_at", "")),
        networks=tuple(networks),
    )


@lru_cache(maxsize=4)
def load_table(path: str | Path | None = None) -> SurfaceNetworkTable:
    """The frozen network table, read once per path."""

    return _load(Path(path) if path is not None else TABLE_PATH)


#: The one longitude pair that spells the whole band instead of naming a
#: meridian twice: ``west`` at the west end of the signed branch, ``east`` at
#: its east end. It is also the pair :func:`_canonical_longitudes` hands back
#: for a full-band box, so a box that comes back out of :func:`_check_box`
#: and goes in again is read the same way the second time.
_WHOLE_BAND = (-180.0, 180.0)


def _check_box(west: float, south: float, east: float,
               north: float) -> tuple[float, float, float, float]:
    """The box as this module reads it, or a refusal naming the numbers.

    Integrity checks on the caller's own box only. The corners are finite,
    south is below north and the latitudes are on the globe; those are
    contradictions, not capability limits. The longitudes are canonicalized
    rather than refused wherever only a convention differs, and what comes
    back is the box the screen actually uses: ``west`` on the
    ``[-180, 180]`` branch and ``east`` carried eastward from it, running
    past +180 when the box crosses the antimeridian.

    A pair naming one meridian twice is the one longitude contradiction
    left, and it is caught by the width the pair encloses rather than by
    comparing the two branch values. The branches differ at their shared
    end: ``west`` lands in ``[-180, 180)`` and ``east`` in ``(-180, 180]``,
    so one meridian reads as -180 on one side and +180 on the other, and
    ``(180, 180)`` would have compared unequal and resolved to the whole
    globe. Zero degrees and 360 degrees are the two widths such a pair can
    mean; ``_WHOLE_BAND`` is the spelling that says which, and every other
    spelling is refused with that one named.
    """

    values = (float(west), float(south), float(east), float(north))
    if not all(value == value and abs(value) != float("inf")
               for value in values):
        raise SurfaceNetworkError("a domain box must be four finite numbers")
    if south >= north:
        raise SurfaceNetworkError(
            f"domain south {south} is not below north {north}")
    if south < -90.0 or north > 90.0:
        off_the_globe = south if south < -90.0 else north
        raise SurfaceNetworkError(
            f"domain latitude {off_the_globe} is off the globe; pass both "
            f"latitudes inside [-90, 90]. No station has that latitude, so "
            f"the screen would be answering about a band that does not "
            f"exist rather than about the domain")
    if not _in_a_convention(values[0], values[2]):
        raise SurfaceNetworkError(
            f"domain longitudes ({west}, {east}) lie in neither convention "
            f"this box accepts, so the screen would be run against a "
            f"hemisphere nobody asked for. Pass both edges inside "
            f"[-180, 180], or both inside [0, 360]; a box crossing the "
            f"antimeridian is written west greater than east")
    canonical_west, canonical_east = _canonical_longitudes(values[0],
                                                           values[2])
    eastward_span = canonical_east - canonical_west
    if (eastward_span == 0.0
            or (eastward_span == 360.0
                and (values[0], values[2]) != _WHOLE_BAND)):
        raise SurfaceNetworkError(
            f"domain west {west} and east {east} name the same meridian, so "
            f"the box is either zero degrees wide or the whole band and the "
            f"numbers do not say which. Write the whole band as (-180, 180), "
            f"or move one edge")
    return (canonical_west, values[1], canonical_east, values[3])


def networks_for_bbox(west: float, south: float, east: float, north: float, *,
                      table: SurfaceNetworkTable | None = None,
                      ) -> tuple[str, ...]:
    """Every network whose declared extent overlaps the domain, sorted by id.

    Sorted rather than in table order so the same domain names the same
    networks in the same sequence on every host: the id list ends up in a
    receipt, and a set that reorders itself makes two identical runs look
    different.

    The box takes either longitude convention the extents take: edges inside
    ``[-180, 180]``, with ``west`` greater than ``east`` meaning the box
    crosses the antimeridian, or edges inside ``[0, 360]``. Which of those a
    pair is, and what it means, is :class:`woof.fetch.Area`'s answer, not a
    second one. A longitude in neither is refused with the interval named.
    The order is the caller's and is read as written: sorting the pair is
    what ``--area`` does to two corners that carry no west, and doing it
    here would turn the crossing box into its complement.

    Raises :class:`SurfaceNetworkError` when nothing overlaps. A domain the
    archive does not cover is a real answer, but it is not the same answer as
    an empty fetch, and returning an empty tuple would let a case run to
    completion having assimilated no surface observation and said nothing
    about it.
    """

    given = (float(west), float(east))
    west, south, east, north = _check_box(west, south, east, north)
    table = table or load_table()
    matched = tuple(
        network.id for network in table.networks
        if network.intersects(west, south, east, north))
    if not matched:
        # The numbers in the message are the numbers the screen compared:
        # _check_box hands back the canonical pair, intersects canonicalizes
        # to that same pair, and so a reader can rerun the screen from the
        # message alone. When canonicalizing moved the edges, the pair as
        # passed is named beside them and how it was read is stated, so a
        # caller is shown neither only numbers it did not write nor a
        # hemisphere nothing ran on.
        as_given = ""
        if (west, east) != given:
            as_given = (f" (the ({given[0]:g}, {given[1]:g}) longitudes as "
                        f"passed, west put on the [-180, 180] branch and "
                        f"east carried eastward from it)")
        raise SurfaceNetworkError(
            f"none of the {len(table)} networks in the surface table has an "
            f"extent overlapping ({west:g}, {south:g}, {east:g}, "
            f"{north:g}){as_given}. "
            f"This domain has no surface observations from this archive; "
            f"refusing rather than returning an empty list, because a run "
            f"that assimilated nothing and reported nothing looks exactly "
            f"like a run that assimilated everything")
    return matched


def describe(networks: tuple[str, ...] | list[str], *,
             table: SurfaceNetworkTable | None = None) -> tuple[str, ...]:
    """``("DE__ASOS (Germany ASOS)", ...)`` for a receipt or a log line."""

    table = table or load_table()
    names = {network.id: network.name for network in table.networks}
    return tuple(
        f"{network} ({names[network]})" if names.get(network) else str(network)
        for network in networks)


__all__ = ["SurfaceNetwork", "SurfaceNetworkError", "SurfaceNetworkTable",
           "TABLE_PATH", "TABLE_SCHEMA", "describe", "load_table",
           "networks_for_bbox"]
