// Rust libm 0.2.16 device transcription: exp.rs, log.rs, log1p.rs, pow.rs,
// and generic/scalbn.rs. The crate grant is MIT; its contributor grant is
// MIT OR Apache-2.0. Full text: licenses/LICENSE-rust-libm.txt.
// glibc 2.39 log1pf is transcribed from gpuwm/core/noahmp_libm.py.
/*
 * Copyright (C) 2004 by Sun Microsystems, Inc. All rights reserved.
 *
 * Permission to use, copy, modify, and distribute this
 * software is freely granted, provided that this notice
 * is preserved.
 */
/*
 * Copyright (C) 1993 by Sun Microsystems, Inc. All rights reserved.
 *
 * Developed at SunSoft, a Sun Microsystems, Inc. business.
 * Permission to use, copy, modify, and distribute this
 * software is freely granted, provided that this notice
 * is preserved.
 */
/*
 * Copyright (C) 1993 by Sun Microsystems, Inc. All rights reserved.
 *
 * Developed at SunPro, a Sun Microsystems, Inc. business.
 * Permission to use, copy, modify, and distribute this
 * software is freely granted, provided that this notice
 * is preserved.
 */
// Generated by tools/portable_libm64_header.py. All arithmetic retains
// the host expression tree with one RN operation per AST node.
#ifndef GPUWM_PORTABLE_LIBM64_CUH
#define GPUWM_PORTABLE_LIBM64_CUH
__device__ __forceinline__ double plm_bits(unsigned long long u) { return __longlong_as_double((long long)u); }
__device__ __forceinline__ unsigned long long plm_word(double x) { return (unsigned long long)__double_as_longlong(x); }
__device__ __forceinline__ double plm_negd(double x) { return plm_bits(plm_word(x) ^ 0x8000000000000000ULL); }
__device__ __forceinline__ float plm_negf(float x) { return __int_as_float(__float_as_int(x) ^ (int)0x80000000U); }
__device__ __forceinline__ double plm_abs(double x) { return plm_bits(plm_word(x) & 0x7fffffffffffffffULL); }
__device__ __forceinline__ unsigned plm_hi(double x) { return (unsigned)(plm_word(x) >> 32); }
__device__ __forceinline__ double plm_sethi(double x, unsigned h) { return plm_bits(((unsigned long long)h << 32) | (plm_word(x) & 0xffffffffULL)); }
__device__ __forceinline__ double plm_setlo(double x, unsigned l) { return plm_bits((plm_word(x) & 0xffffffff00000000ULL) | l); }
// Rust float-to-i32 casts truncate and saturate; NaN casts to zero.
__device__ __forceinline__ int plm_i32(double x) {
    if ((plm_word(x) & 0x7fffffffffffffffULL) > 0x7ff0000000000000ULL) return 0;
    if (x >= 2147483647.0) return 2147483647;
    if (x <= -2147483648.0) return (-2147483647 - 1);
    return __double2int_rz(x);
}
__device__ __forceinline__ double plm_scalbn(double x, int n) {
    if (n > 1023) {
        x = __dmul_rn(x, plm_bits(0x7fe0000000000000)); n -= 1023;
        if (n > 1023) { x = __dmul_rn(x, plm_bits(0x7fe0000000000000)); n -= 1023; if (n > 1023) n = 1023; }
    } else if (n < -1022) {
        x = __dmul_rn(x, plm_bits(0x360000000000000)); n += 969;
        if (n < -1022) { x = __dmul_rn(x, plm_bits(0x360000000000000)); n += 969; if (n < -1022) n = -1022; }
    }
    double scale = plm_bits((unsigned long long)(1023 + n) << 52);
    return __dmul_rn(x, scale);
}
__device__ __forceinline__ double plm_exp(double x) {
    const double plm_LN2HI = plm_bits(0x3fe62e42fee00000), plm_LN2LO = plm_bits(0x3dea39ef35793c76);
    const double plm_INVLN2 = plm_bits(0x3ff71547652b82fe);
    const double plm_P1 = plm_bits(0x3fc555555555553e), plm_P2 = plm_bits(0xbf66c16c16bebd93);
    const double plm_P3 = plm_bits(0x3f11566aaf25de2c), plm_P4 = plm_bits(0xbebbbd41c5d26bf1), plm_P5 = plm_bits(0x3e66376972bea4d0);
    unsigned hx = plm_hi(x); int sign = hx >> 31; hx &= 0x7fffffff;
    if (hx >= 0x4086232b) {
        if ((plm_word(x) & 0x7fffffffffffffffULL) > 0x7ff0000000000000ULL) return x;
        if (x > 709.782712893383973096) return __dmul_rn(x, plm_bits(0x7fe0000000000000));
        if (x < -745.13321910194110842) return 0.0;
    }
    int k; double hi, lo;
    if (hx > 0x3fd62e42) {
        double half = sign ? -0.5 : 0.5;
        if (hx >= 0x3ff0a2b2) k = plm_i32(__dadd_rn(__dmul_rn(plm_INVLN2, x), half));
        else k = 1 - sign - sign;
        hi = __dsub_rn(x, __dmul_rn(__int2double_rn(k), plm_LN2HI)); lo = __dmul_rn(__int2double_rn(k), plm_LN2LO); x = __dsub_rn(hi, lo);
    } else if (hx > 0x3e300000) { k = 0; hi = x; lo = 0.0; }
    else return __dadd_rn(1.0, x);
    double xx = __dmul_rn(x, x);
    double c = __dsub_rn(x, __dmul_rn(xx, __dadd_rn(plm_P1, __dmul_rn(xx, __dadd_rn(plm_P2, __dmul_rn(xx, __dadd_rn(plm_P3, __dmul_rn(xx, __dadd_rn(plm_P4, __dmul_rn(xx, plm_P5))))))))));
    double y = __dadd_rn(1.0, __dadd_rn(__dsub_rn(__ddiv_rn(__dmul_rn(x, c), __dsub_rn(2.0, c)), lo), hi));
    return k == 0 ? y : plm_scalbn(y, k);
}
__device__ __forceinline__ double plm_log(double x) {
    const double plm_LN2_HI = plm_bits(0x3fe62e42fee00000), plm_LN2_LO = plm_bits(0x3dea39ef35793c76);
    const double plm_LG1 = plm_bits(0x3fe5555555555593), plm_LG2 = plm_bits(0x3fd999999997fa04), plm_LG3 = plm_bits(0x3fd2492494229359);
    const double plm_LG4 = plm_bits(0x3fcc71c51d8e78af), plm_LG5 = plm_bits(0x3fc7466496cb03de), plm_LG6 = plm_bits(0x3fc39a09d078c69f), plm_LG7 = plm_bits(0x3fc2f112df3e5244);
    unsigned long long ui = plm_word(x); unsigned hx = ui >> 32; int k = 0;
    if (hx < 0x00100000 || (hx >> 31) != 0) {
        if ((ui << 1) == 0) return plm_bits(0xfff0000000000000);
        if (hx >> 31) return __ddiv_rn(__dsub_rn(x, x), 0.0);
        k -= 54; x = __dmul_rn(x, plm_bits(0x4350000000000000)); ui = plm_word(x); hx = ui >> 32;
    } else if (hx >= 0x7ff00000) return x;
    else if (hx == 0x3ff00000 && (ui << 32) == 0) return 0.0;
    hx += 0x3ff00000 - 0x3fe6a09e; k += (int)(hx >> 20) - 0x3ff;
    hx = (hx & 0x000fffff) + 0x3fe6a09e; x = plm_sethi(x, hx);
    double f = __dsub_rn(x, 1.0), hfsq = __dmul_rn(__dmul_rn(0.5, f), f), s = __ddiv_rn(f, __dadd_rn(2.0, f));
    double z = __dmul_rn(s, s), w = __dmul_rn(z, z);
    double t1 = __dmul_rn(w, __dadd_rn(plm_LG2, __dmul_rn(w, __dadd_rn(plm_LG4, __dmul_rn(w, plm_LG6)))));
    double t2 = __dmul_rn(z, __dadd_rn(plm_LG1, __dmul_rn(w, __dadd_rn(plm_LG3, __dmul_rn(w, __dadd_rn(plm_LG5, __dmul_rn(w, plm_LG7)))))));
    double r = __dadd_rn(t2, t1), dk = __int2double_rn(k);
    return __dadd_rn(__dadd_rn(__dsub_rn(__dadd_rn(__dmul_rn(s, __dadd_rn(hfsq, r)), __dmul_rn(dk, plm_LN2_LO)), hfsq), f), __dmul_rn(dk, plm_LN2_HI));
}
__device__ __forceinline__ double plm_log1p(double x) {
    const double plm_LN2_HI = plm_bits(0x3fe62e42fee00000), plm_LN2_LO = plm_bits(0x3dea39ef35793c76);
    const double plm_LG1 = plm_bits(0x3fe5555555555593), plm_LG2 = plm_bits(0x3fd999999997fa04), plm_LG3 = plm_bits(0x3fd2492494229359);
    const double plm_LG4 = plm_bits(0x3fcc71c51d8e78af), plm_LG5 = plm_bits(0x3fc7466496cb03de), plm_LG6 = plm_bits(0x3fc39a09d078c69f), plm_LG7 = plm_bits(0x3fc2f112df3e5244);
    unsigned long long ui = plm_word(x); unsigned hx = ui >> 32, hu; int k = 1; double f = 0.0, c = 0.0;
    if (hx < 0x3fda827a || (hx >> 31) > 0) {
        if (hx >= 0xbff00000) { if (x == -1.0) return plm_bits(0xfff0000000000000); return __ddiv_rn(__dsub_rn(x, x), 0.0); }
        if ((hx << 1) < (0x3ca00000U << 1)) return x;
        if (hx <= 0xbfd2bec4) { k = 0; f = x; }
    } else if (hx >= 0x7ff00000) return x;
    if (k > 0) {
        double u = __dadd_rn(1.0, x); ui = plm_word(u); hu = ui >> 32;
        hu += 0x3ff00000 - 0x3fe6a09e; k = (int)(hu >> 20) - 0x3ff;
        if (k < 54) { c = k >= 2 ? __dsub_rn(1.0, __dsub_rn(u, x)) : __dsub_rn(x, __dsub_rn(u, 1.0)); c = __ddiv_rn(c, u); }
        hu = (hu & 0x000fffff) + 0x3fe6a09e; f = __dsub_rn(plm_sethi(u, hu), 1.0);
    }
    double hfsq = __dmul_rn(__dmul_rn(0.5, f), f), s = __ddiv_rn(f, __dadd_rn(2.0, f)), z = __dmul_rn(s, s), w = __dmul_rn(z, z);
    double t1 = __dmul_rn(w, __dadd_rn(plm_LG2, __dmul_rn(w, __dadd_rn(plm_LG4, __dmul_rn(w, plm_LG6))))), t2 = __dmul_rn(z, __dadd_rn(plm_LG1, __dmul_rn(w, __dadd_rn(plm_LG3, __dmul_rn(w, __dadd_rn(plm_LG5, __dmul_rn(w, plm_LG7)))))));
    double r = __dadd_rn(t2, t1), dk = __int2double_rn(k);
    return __dadd_rn(__dadd_rn(__dsub_rn(__dadd_rn(__dmul_rn(s, __dadd_rn(hfsq, r)), __dadd_rn(__dmul_rn(dk, plm_LN2_LO), c)), hfsq), f), __dmul_rn(dk, plm_LN2_HI));
}
__device__ __forceinline__ double plm_pow(double x, double y) {
    const double plm_BP[2] = {1.0, 1.5}, plm_DP_H[2] = {0.0, plm_bits(0x3fe2b80340000000)}, plm_DP_L[2] = {0.0, plm_bits(0x3e4cfdeb43cfd006)};
    const double plm_TWO53 = plm_bits(0x4340000000000000), plm_HUGE = 1.0e300, plm_TINY = 1.0e-300;
    const double plm_L1 = plm_bits(0x3fe3333333333303), plm_L2 = plm_bits(0x3fdb6db6db6fabff), plm_L3 = plm_bits(0x3fd55555518f264d);
    const double plm_L4 = plm_bits(0x3fd17460a91d4101), plm_L5 = plm_bits(0x3fcd864a93c9db65), plm_L6 = plm_bits(0x3fca7e284a454eef);
    const double plm_P1 = plm_bits(0x3fc555555555553e), plm_P2 = plm_bits(0xbf66c16c16bebd93), plm_P3 = plm_bits(0x3f11566aaf25de2c);
    const double plm_P4 = plm_bits(0xbebbbd41c5d26bf1), plm_P5 = plm_bits(0x3e66376972bea4d0);
    const double plm_LG2 = plm_bits(0x3fe62e42fefa39ef), plm_LG2_H = plm_bits(0x3fe62e4300000000), plm_LG2_L = plm_bits(0xbe205c610ca86c39);
    const double plm_OVT = 8.0085662595372944372e-17, plm_CP = plm_bits(0x3feec709dc3a03fd), plm_CP_H = plm_bits(0x3feec709e0000000), plm_CP_L = plm_bits(0xbe3e2fe0145b01f5);
    const double plm_IVLN2 = plm_bits(0x3ff71547652b82fe), plm_IVLN2_H = plm_bits(0x3ff7154760000000), plm_IVLN2_L = plm_bits(0x3e54ae0bf85ddf44);
    int hx = (int)plm_hi(x), hy = (int)plm_hi(y);
    unsigned lx = (unsigned)plm_word(x), ly = (unsigned)plm_word(y);
    int ix = hx & 0x7fffffff, iy = hy & 0x7fffffff;
    if (((unsigned)iy | ly) == 0) return 1.0;
    if (hx == 0x3ff00000 && lx == 0) return 1.0;
    // The host x+y selects the first NaN, including when both are NaNs.
    // plm_CUDA double addition may select the second, so quiet explicitly.
    if (ix > 0x7ff00000 || (ix == 0x7ff00000 && lx != 0)) return plm_bits(plm_word(x) | 0x0008000000000000ULL);
    if (iy > 0x7ff00000 || (iy == 0x7ff00000 && ly != 0)) return plm_bits(plm_word(y) | 0x0008000000000000ULL);
    int yisint = 0, k, j;
    if (hx < 0) {
        if (iy >= 0x43400000) yisint = 2;
        else if (iy >= 0x3ff00000) {
            k = (iy >> 20) - 0x3ff;
            if (k > 20) { j = (int)(ly >> (52 - k)); if (((unsigned)j << (52 - k)) == ly) yisint = 2 - (j & 1); }
            else if (ly == 0) { j = iy >> (20 - k); if ((j << (20 - k)) == iy) yisint = 2 - (j & 1); }
        }
    }
    if (ly == 0) {
        if (iy == 0x7ff00000) {
            if (((ix - 0x3ff00000) | (int)lx) == 0) return 1.0;
            if (ix >= 0x3ff00000) return hy >= 0 ? y : 0.0;
            return hy >= 0 ? 0.0 : plm_negd(y);
        }
        if (iy == 0x3ff00000) return hy >= 0 ? x : __ddiv_rn(1.0, x);
        if (hy == 0x40000000) return __dmul_rn(x, x);
        if (hy == 0x3fe00000 && hx >= 0) return __dsqrt_rn(x);
    }
    double ax = plm_abs(x);
    if (lx == 0 && (ix == 0x7ff00000 || ix == 0 || ix == 0x3ff00000)) {
        double z = ax;
        if (hy < 0) z = __ddiv_rn(1.0, z);
        if (hx < 0) {
            if (((ix - 0x3ff00000) | yisint) == 0) z = __ddiv_rn(__dsub_rn(z, z), __dsub_rn(z, z));
            else if (yisint == 1) z = plm_negd(z);
        }
        return z;
    }
    double s = 1.0;
    if (hx < 0) { if (yisint == 0) return __ddiv_rn(__dsub_rn(x, x), __dsub_rn(x, x)); if (yisint == 1) s = -1.0; }
    double t1, t2;
    if (iy > 0x41e00000) {
        if (iy > 0x43f00000) {
            if (ix <= 0x3fefffff) return hy < 0 ? __dmul_rn(plm_HUGE, plm_HUGE) : __dmul_rn(plm_TINY, plm_TINY);
            if (ix >= 0x3ff00000) return hy > 0 ? __dmul_rn(plm_HUGE, plm_HUGE) : __dmul_rn(plm_TINY, plm_TINY);
        }
        if (ix < 0x3fefffff) return hy < 0 ? __dmul_rn(__dmul_rn(s, plm_HUGE), plm_HUGE) : __dmul_rn(__dmul_rn(s, plm_TINY), plm_TINY);
        if (ix > 0x3ff00000) return hy > 0 ? __dmul_rn(__dmul_rn(s, plm_HUGE), plm_HUGE) : __dmul_rn(__dmul_rn(s, plm_TINY), plm_TINY);
        double t = __dsub_rn(ax, 1.0), w = __dmul_rn(__dmul_rn(t, t), __dsub_rn(0.5, __dmul_rn(t, __dsub_rn(0.3333333333333333, __dmul_rn(t, 0.25)))));
        double u = __dmul_rn(plm_IVLN2_H, t), v = __dsub_rn(__dmul_rn(t, plm_IVLN2_L), __dmul_rn(w, plm_IVLN2));
        t1 = plm_setlo(__dadd_rn(u, v), 0); t2 = __dsub_rn(v, __dsub_rn(t1, u));
    } else {
        int n = 0;
        if (ix < 0x00100000) { ax = __dmul_rn(ax, plm_TWO53); n -= 53; ix = (int)plm_hi(ax); }
        n += (ix >> 20) - 0x3ff; j = ix & 0x000fffff;
        int k; ix = j | 0x3ff00000;
        if (j <= 0x3988e) k = 0;
        else if (j < 0xbb67a) k = 1;
        else { k = 0; n += 1; ix -= 0x00100000; }
        ax = plm_sethi(ax, (unsigned)ix);
        double u = __dsub_rn(ax, plm_BP[k]), v = __ddiv_rn(1.0, __dadd_rn(ax, plm_BP[k])), ss = __dmul_rn(u, v), s_h = plm_setlo(ss, 0);
        double t_h = plm_sethi(0.0, (((unsigned)ix >> 1) | 0x20000000) + 0x00080000 + ((unsigned)k << 18));
        double t_l = __dsub_rn(ax, __dsub_rn(t_h, plm_BP[k])), s_l = __dmul_rn(v, __dsub_rn(__dsub_rn(u, __dmul_rn(s_h, t_h)), __dmul_rn(s_h, t_l)));
        double s2 = __dmul_rn(ss, ss), r = __dmul_rn(__dmul_rn(s2, s2), __dadd_rn(plm_L1, __dmul_rn(s2, __dadd_rn(plm_L2, __dmul_rn(s2, __dadd_rn(plm_L3, __dmul_rn(s2, __dadd_rn(plm_L4, __dmul_rn(s2, __dadd_rn(plm_L5, __dmul_rn(s2, plm_L6)))))))))));
        r = __dadd_rn(r, __dmul_rn(s_l, __dadd_rn(s_h, ss))); s2 = __dmul_rn(s_h, s_h);
        t_h = plm_setlo(__dadd_rn(__dadd_rn(3.0, s2), r), 0); t_l = __dsub_rn(r, __dsub_rn(__dsub_rn(t_h, 3.0), s2));
        u = __dmul_rn(s_h, t_h); v = __dadd_rn(__dmul_rn(s_l, t_h), __dmul_rn(t_l, ss));
        double p_h = plm_setlo(__dadd_rn(u, v), 0), p_l = __dsub_rn(v, __dsub_rn(p_h, u));
        double z_h = __dmul_rn(plm_CP_H, p_h), z_l = __dadd_rn(__dadd_rn(__dmul_rn(plm_CP_L, p_h), __dmul_rn(p_l, plm_CP)), plm_DP_L[k]);
        double t = __int2double_rn(n);
        t1 = plm_setlo(__dadd_rn(__dadd_rn(__dadd_rn(z_h, z_l), plm_DP_H[k]), t), 0);
        t2 = __dsub_rn(z_l, __dsub_rn(__dsub_rn(__dsub_rn(t1, t), plm_DP_H[k]), z_h));
    }
    double y1 = plm_setlo(y, 0), p_l = __dadd_rn(__dmul_rn(__dsub_rn(y, y1), t1), __dmul_rn(y, t2)), p_h = __dmul_rn(y1, t1), z = __dadd_rn(p_l, p_h);
    j = (int)plm_hi(z); int i = (int)plm_word(z);
    if (j >= 0x40900000) {
        if (((j - 0x40900000) | i) != 0) return __dmul_rn(__dmul_rn(s, plm_HUGE), plm_HUGE);
        if (__dadd_rn(p_l, plm_OVT) > __dsub_rn(z, p_h)) return __dmul_rn(__dmul_rn(s, plm_HUGE), plm_HUGE);
    } else if ((j & 0x7fffffff) >= 0x4090cc00) {
        if ((((unsigned)j - 0xc090cc00U) | (unsigned)i) != 0) return __dmul_rn(__dmul_rn(s, plm_TINY), plm_TINY);
        if (p_l <= __dsub_rn(z, p_h)) return __dmul_rn(__dmul_rn(s, plm_TINY), plm_TINY);
    }
    i = j & 0x7fffffff; k = (i >> 20) - 0x3ff; int n = 0;
    if (i > 0x3fe00000) {
        n = j + (0x00100000 >> (k + 1)); k = ((n & 0x7fffffff) >> 20) - 0x3ff;
        double t = plm_sethi(0.0, (unsigned)(n & ~(0x000fffff >> k)));
        n = ((n & 0x000fffff) | 0x00100000) >> (20 - k); if (j < 0) n = -n;
        p_h = __dsub_rn(p_h, t);
    }
    double t = plm_setlo(__dadd_rn(p_l, p_h), 0), u = __dmul_rn(t, plm_LG2_H), v = __dadd_rn(__dmul_rn(__dsub_rn(p_l, __dsub_rn(t, p_h)), plm_LG2), __dmul_rn(t, plm_LG2_L));
    z = __dadd_rn(u, v); double w = __dsub_rn(v, __dsub_rn(z, u)); t = __dmul_rn(z, z);
    t1 = __dsub_rn(z, __dmul_rn(t, __dadd_rn(plm_P1, __dmul_rn(t, __dadd_rn(plm_P2, __dmul_rn(t, __dadd_rn(plm_P3, __dmul_rn(t, __dadd_rn(plm_P4, __dmul_rn(t, plm_P5))))))))));
    double r = __dsub_rn(__ddiv_rn(__dmul_rn(z, t1), __dsub_rn(t1, 2.0)), __dadd_rn(w, __dmul_rn(z, w))); z = __dsub_rn(1.0, __dsub_rn(r, z));
    j = (int)((unsigned)plm_hi(z) + ((unsigned)n << 20));
    z = (j >> 20) <= 0 ? plm_scalbn(z, n) : plm_sethi(z, (unsigned)j);
    return __dmul_rn(s, z);
}
__device__ __forceinline__ float plm_log1pf(float x) {
    int hx = __float_as_int(x), ax = hx & 0x7fffffff, k = 1, hu = 0;
    // plm_CUDA float addition canonicalizes NaNs. The host x+x quiets the
    // input payload and retains its sign, so perform that bit operation.
    if (ax > 0x7f800000) return __int_as_float(hx | 0x00400000);
    float f = 0.0f, c = 0.0f;
    const float plm_LN2_HI = __int_as_float(0x3f317180), plm_LN2_LO = __int_as_float(0x3717f7d1);
    if (hx < 0x3ed413d7) {
        if (ax >= 0x3f800000) {
            if (x == -1.0f) return __int_as_float(0xff800000U);
            if (ax > 0x7f800000) return __fadd_rn(x, x);
            return __int_as_float(0xffc00000U);
        }
        if (ax < 0x31000000) return x;
        if (hx > 0 || hx <= (int)0xbe95f61fU) { k = 0; f = x; hu = 1; }
    } else if (hx >= 0x7f800000) return __fadd_rn(x, x);
    if (k != 0) {
        float u;
        if (hx < 0x5a000000) {
            u = __fadd_rn(1.0f, x); hu = __float_as_int(u); k = (hu >> 23) - 127;
            c = k > 0 ? __fsub_rn(1.0f, __fsub_rn(u, x)) : __fsub_rn(x, __fsub_rn(u, 1.0f)); c = __fdiv_rn(c, u);
        } else { u = x; hu = __float_as_int(u); k = (hu >> 23) - 127; }
        hu &= 0x007fffff;
        if (hu < 0x3504f7) u = __int_as_float(hu | 0x3f800000);
        else { k += 1; u = __int_as_float(hu | 0x3f000000); hu = (0x00800000 - hu) >> 2; }
        f = __fsub_rn(u, 1.0f);
    }
    float hfsq = __fmul_rn(__fmul_rn(0.5f, f), f), kf = __int2float_rn(k);
    if (hu == 0) {
        if (f == 0.0f) {
            if (k == 0) return 0.0f;
            c = __fadd_rn(c, __fmul_rn(kf, plm_LN2_LO)); return __fadd_rn(__fmul_rn(kf, plm_LN2_HI), c);
        }
        float r = __fmul_rn(hfsq, __fsub_rn(1.0f, __fmul_rn(__int_as_float(0x3f2aaaab), f)));
        if (k == 0) return __fsub_rn(f, r);
        return __fsub_rn(__fmul_rn(kf, plm_LN2_HI), __fsub_rn(__fsub_rn(r, __fadd_rn(__fmul_rn(kf, plm_LN2_LO), c)), f));
    }
    const float plm_LP1 = __int_as_float(0x3f2aaaab), plm_LP2 = __int_as_float(0x3ecccccd), plm_LP3 = __int_as_float(0x3e924925);
    const float plm_LP4 = __int_as_float(0x3e638e29), plm_LP5 = __int_as_float(0x3e3a3325), plm_LP6 = __int_as_float(0x3e1cd04f), plm_LP7 = __int_as_float(0x3e178897);
    float s = __fdiv_rn(f, __fadd_rn(2.0f, f)), z = __fmul_rn(s, s);
    float r = __fmul_rn(z, __fadd_rn(plm_LP1, __fmul_rn(z, __fadd_rn(plm_LP2, __fmul_rn(z, __fadd_rn(plm_LP3, __fmul_rn(z, __fadd_rn(plm_LP4, __fmul_rn(z, __fadd_rn(plm_LP5, __fmul_rn(z, __fadd_rn(plm_LP6, __fmul_rn(z, plm_LP7)))))))))))));
    if (k == 0) return __fsub_rn(f, __fsub_rn(hfsq, __fmul_rn(s, __fadd_rn(hfsq, r))));
    return __fsub_rn(__fmul_rn(kf, plm_LN2_HI), __fsub_rn(__fsub_rn(hfsq, __fadd_rn(__fmul_rn(s, __fadd_rn(hfsq, r)), __fadd_rn(__fmul_rn(kf, plm_LN2_LO), c))), f));
}
#endif
