"""GABLS1: the community's stably stratified boundary-layer benchmark.

A flat, dry, horizontally homogeneous column under a steady geostrophic
wind whose surface is cooled at a fixed rate for nine hours.  Turbulence
generated by the shear fights stratification generated by the cooling,
and the boundary layer settles to a depth that the fight decides.  That
depth is the answer, and it has been published: this is the first case
of the GEWEX Atmospheric Boundary Layer Study, run by eleven
large-eddy-simulation codes (Beare et al. 2006) and by nineteen
single-column models (Cuxart et al. 2006).

Why it is in the tree
---------------------
Because the experimental closure had no stable-limb calibration target,
and the absence of one blocked two separate attempts to fix a
structural defect in its stable limb.  That absence was a property of
this repository, not of the field.  This case ends it.

The stable boundary layer is the regime where boundary-layer closures
disagree most and where the disagreement is most consequential: it sets
the nocturnal low-level jet, the depth cold air pools to, and how
strongly the surface decouples from the flow above it.  The published
single-column ensemble spans a factor of four in depth against a
large-eddy answer that is tight to 9%, and the paper says plainly which
direction the operational schemes err in and why.  A closure can
therefore be told not just whether it is wrong but which company it is
in when it is.

What it scores
--------------
The closure's VERTICAL CHANNEL, driven as a single column -- which is
exactly the protocol Cuxart et al. ran and exactly the ensemble the
gates below are set against.  It is NOT a dycore test: no three-
dimensional model is integrated, and the case deliberately does not
pretend to be one.  The benchmark's own surface layer is used (the
prescribed Businger-Dyer stable similarity of the case description),
so what is being measured is the turbulence closure and not the drag
law, which is the whole design of the intercomparison.

Authority
---------
Every number below is transcribed from a primary source, and the source
is named at the number.  Nothing here is fitted, and no gate is set from
a run of this model.

* Beare, R.J., M.K. MacVean, A.A.M. Holtslag, J. Cuxart, I. Esau,
  J.-C. Golaz, M.A. Jimenez, M. Khairoutdinov, B. Kosovic, D. Lewellen,
  T.S. Lund, J.K. Lundquist, A. McCabe, A.F. Moene, Y. Noh, S. Raasch
  and P. Sullivan, 2006: "An intercomparison of large-eddy simulations
  of the stable boundary layer."  Bound.-Layer Meteorol. 118, 247-272.
  -- the LES intercomparison and the boundary-layer-depth DEFINITION
  used here.
* Cuxart, J., A.A.M. Holtslag, R.J. Beare, E. Bazile, A. Beljaars,
  A. Cheng, L. Conangla, M. Ek, F. Freedman, R. Hamdi, A. Kerstein,
  H. Kitagawa, G. Lenderink, D. Lewellen, J. Mailhot, T. Mauritsen,
  V. Perov, G. Schayes, G.-J. Steeneveld, G. Svensson, P. Taylor,
  W. Weng, S. Wunsch and K.-M. Xu, 2006: "Single-column model
  intercomparison for a stably stratified atmospheric boundary layer."
  Bound.-Layer Meteorol. 118, 273-303.  -- the SINGLE-COLUMN ensemble
  this case is scored against, its Table IV reference row, and the
  diagnosis of which closures err which way.
* The case originates with Kosovic, B. and J.A. Curry, 2000: "A large
  eddy simulation study of a quasi-steady, stably stratified
  atmospheric boundary layer."  J. Atmos. Sci. 57, 1052-1068.

Setup, as prescribed
--------------------
Geostrophic wind (8, 0) m/s on an f-plane at 73 N (f = 1.39e-4 s^-1).
Initial potential temperature 265 K below 100 m, then 0.01 K/m above,
reaching 268 K at 400 m.  Surface potential temperature prescribed
(Dirichlet, NOT a flux), starting at 265 K and falling at 0.25 K/h for
the whole nine hours.  Roughness 0.1 m for BOTH momentum and heat.
Dry: no moisture, no radiation, no subsidence.  Domain top 400 m, 64
levels of 6.25 m -- the intercomparison's own single-column resolution.
Initial turbulence energy 0.4*(1 - z/250)^3 below 250 m.  Nine hours;
diagnostics over the final hour.
"""

from __future__ import annotations

import json
import math
from pathlib import Path

import numpy as np

#: Geostrophic wind [m/s] (Beare et al. 2006 section 2; case description
#: "Ug = 8 m/s, Vg = 0 m/s").
GEO_U = 8.0
GEO_V = 0.0
#: Coriolis parameter [s^-1] at the prescribed latitude 73 N.
FCOR = 1.39e-4
#: Initial potential temperature: THETA_MIXED below MIXED_DEPTH, then
#: LAPSE above, reaching 268 K at the 400 m domain top.
THETA_MIXED = 265.0
MIXED_DEPTH = 100.0
LAPSE = 0.01
#: Prescribed surface potential temperature [K] and its COOLING RATE
#: [K/h].  This is a Dirichlet condition, not a prescribed heat flux --
#: the distinction is the case: the surface flux is an ANSWER here, and
#: it is one of the scored quantities.
THETA_SURFACE_0 = 265.0
COOLING_RATE_K_PER_HOUR = 0.25
#: Roughness length [m], the same for momentum and heat.
Z0 = 0.1
#: Domain top [m], level count, and the resulting uniform layer depth.
ZTOP = 400.0
NZ = 64
#: Model seconds and time step [s] (the intercomparison's own 9 h at
#: dt = 10 s for the single-column protocol).
RUN_SECONDS = 32400.0
DT = 10.0
#: Averaging window for the scored diagnostics [s]: the final hour.
AVERAGE_SECONDS = 3600.0
#: Initial turbulence energy profile 0.4*(1 - z/250)^3 below 250 m.
E_INIT_AMPLITUDE = 0.4
E_INIT_DEPTH = 250.0

#: THE PUBLISHED REFERENCE, Cuxart et al. (2006) Table IV, the LES row
#: at 3.125 m resolution -- "average; sigma" over the eight
#: large-eddy simulations, and the row the paper itself designates as
#: the reference the single-column models are scored against.
#: (Beare et al. Table IV's own ensemble mean at the same resolution is
#: 182 m against Cuxart's 177; the two primary sources differ by ~3% and
#: BOTH are recorded here rather than averaged.  Cuxart's is used
#: because it is the one published with a sigma and the one designated
#: as the scoring reference.)
LES_REFERENCE = {
    "boundary_layer_depth_m": (177.0, 16.0),
    "surface_heat_flux_kinematic": (-0.012, 0.002),
    "friction_velocity": (0.29, 0.02),
    "obukhov_length_m": (149.0, 31.0),
    "surface_wind_angle_deg": (35.0, 3.0),
}
#: Beare et al. (2006) Table IV ensemble-mean depth by LES grid spacing
#: [m], recorded because the resolution dependence is itself part of
#: what the intercomparison established.
LES_DEPTH_BY_SPACING_M = {1.0: 157.0, 2.0: 174.0, 3.125: 182.0,
                          6.25: 188.0, 12.5: 215.0}
#: THE SINGLE-COLUMN ENSEMBLE, Cuxart et al. (2006) Table IV.  This is
#: the company a closure keeps when it misses, and it is why this case
#: can say more than "wrong": the operational first-order schemes come
#: in at 396 +/- 60 m -- more than twice the LES depth -- and the paper
#: attributes that to too much mixing below the inversion, while the
#: higher-order schemes that carry a critical Richardson number come in
#: at 226 +/- 73 m.
SCM_ENSEMBLE_DEPTH_M = {
    "all_19_models": (285.0, 108.0),
    "operational": (396.0, 60.0),
    "research": (208.0, 47.0),
    "first_order": (395.0, 66.0),
    "higher_order": (226.0, 73.0),
}
#: Full published span of the 19 single-column depths [m]: NASA 120 at
#: the shallow end, ECMWF 483 at the deep end -- a factor of four.
SCM_DEPTH_SPAN_M = (120.0, 483.0)

#: THE DEPTH DEFINITION, Beare et al. (2006) section 2, verbatim in
#: substance: the height at which the mean stress magnitude falls to 5%
#: of its surface value, divided by 0.95 (linear extrapolation to zero
#: stress).  Same method as Kosovic and Curry (2000).  Recorded as a
#: constant because several other definitions exist, they disagree, and
#: a score against this reference is only meaningful under this one.
DEPTH_STRESS_FRACTION = 0.05
DEPTH_EXTRAPOLATION = 0.95

#: Pass gates, metric -> (lo, hi).  EVERY BOUND IS DERIVED FROM THE
#: PUBLISHED ENSEMBLE, and the derivation is stated:
#:
#: * ``boundary_layer_depth`` -- [120, 483], the full published span of
#:   the nineteen single-column models (SCM_DEPTH_SPAN_M).  A closure
#:   inside this is somewhere in the published field; outside it is
#:   outside everything anyone published, which is a statement worth
#:   being able to make.  It is deliberately NOT the LES band: this is a
#:   single-column score and the single-column ensemble is the peer
#:   group.  The distance from the LES 177 +/- 16 m is REPORTED as its
#:   own metric rather than gated, because a closure landing at 300 m
#:   would be in the middle of the operational pack and that is
#:   information, not a failure.
#: * ``depth_les_ratio`` -- h/177, reported against a band that admits
#:   the whole published single-column ensemble (0.68 = 120/177 to
#:   2.73 = 483/177).
#: * ``friction_velocity`` -- [0.20, 0.40] m/s: the published
#:   single-column spread is 0.30 +/- 0.03 and the LES 0.29 +/- 0.02, so
#:   this is roughly +/- 3 sigma of the ensemble.  u* is the least
#:   discriminating quantity in the intercomparison (every model gets it
#:   about right) and the band says so.
#: * ``surface_heat_flux`` -- [-0.030, -0.004] K m/s: the ensemble is
#:   -0.015 +/- 0.005 and the LES -0.012 +/- 0.002.  A closure that
#:   drives this to zero has decoupled the surface entirely; one that
#:   drives it far more negative is mixing far too hard.
#: * ``surface_wind_angle`` -- [15, 55] degrees: ensemble 33 +/- 7, LES
#:   35 +/- 3.  The cross-isobar angle is set by how deep the stress
#:   reaches, so it is a second, independent read on the same thing the
#:   depth measures.
#: * ``jet_max_speed`` -- [8.0, 11.0] m/s.  The super-geostrophic
#:   nocturnal jet is the structure the intercomparison found the
#:   over-mixing schemes DESTROY ("the operational models, with too much
#:   mixing, are not able to generate a wind maximum near the SBL top as
#:   seen in LES, except for MSC").  The floor is the geostrophic wind
#:   itself: a column with no jet at all cannot pass.  The ceiling is
#:   generous because the LES peak speed is published only in figures.
#: * ``mixing_stayed_bounded`` -- the column's peak eddy diffusivity
#:   [m2/s].  Cuxart et al. report LES equivalent mixing lengths of
#:   1-2 m for momentum; a stable boundary layer whose diffusivity runs
#:   to tens of m2/s is the over-mixing failure in its raw form.
GATES = {
    "boundary_layer_depth": SCM_DEPTH_SPAN_M,
    "depth_les_ratio": (
        SCM_DEPTH_SPAN_M[0] / LES_REFERENCE["boundary_layer_depth_m"][0],
        SCM_DEPTH_SPAN_M[1] / LES_REFERENCE["boundary_layer_depth_m"][0]),
    "friction_velocity": (0.20, 0.40),
    "surface_heat_flux": (-0.030, -0.004),
    "surface_wind_angle": (15.0, 55.0),
    "jet_max_speed": (8.0, 11.0),
    "mixing_stayed_bounded": (0.0, 20.0),
}


#: Uniform layer depth [m] of the prescribed column.
DZ = ZTOP / NZ


def grid(nz: int = NZ):
    """Layer depth and centers of the prescribed 64 x 6.25 m column.

    ``nz`` is a parameter only so the resolution convergence can be
    MEASURED rather than asserted, and so a sweep over closure
    constants can run at the coarse end without changing its verdict.
    Measured this session at the prescribed dt = 10 s: h = 185.8 m at
    nz = 32 against 185.3 m at nz = 64, i.e. GRID-CONVERGED to 0.3%.
    The time step is the sensitive one -- 193.2 / 185.3 / 169.6 m at
    dt = 5 / 10 / 20 s (nz = 64), so the prescribed dt = 10 s is what
    the scores are quoted at and a coarser step is not equivalent.
    """
    dz = ZTOP / int(nz)
    return dz, (np.arange(int(nz), dtype=np.float64) + 0.5) * dz


def sounding(z) -> np.ndarray:
    """Prescribed initial potential temperature [K]."""
    z = np.asarray(z, dtype=np.float64)
    return THETA_MIXED + LAPSE * np.maximum(z - MIXED_DEPTH, 0.0)


def initial_energy(z) -> np.ndarray:
    """Prescribed initial turbulence energy 0.4*(1 - z/250)^3 [m2/s2]."""
    z = np.asarray(z, dtype=np.float64)
    return E_INIT_AMPLITUDE * np.maximum(
        1.0 - z / E_INIT_DEPTH, 0.0) ** 3


def boundary_layer_depth(z_face, uw, vw, uw_sfc, vw_sfc) -> float:
    """Beare et al. (2006) depth: the height where the stress magnitude
    first falls to 5% of its surface value, divided by 0.95.

    Linear interpolation between the bracketing faces; returns 0.0 if
    the surface stress vanishes and the domain top if the stress never
    falls that far (both are answers a broken closure can produce, and
    both must be representable rather than raise).
    """
    tau_s = math.hypot(float(uw_sfc), float(vw_sfc))
    if tau_s <= 0.0:
        return 0.0
    tau = np.hypot(np.asarray(uw, dtype=np.float64),
                   np.asarray(vw, dtype=np.float64))
    target = DEPTH_STRESS_FRACTION * tau_s
    below = np.nonzero(tau >= target)[0]
    if below.size == 0:
        return 0.0
    k = int(below[-1])
    if k + 1 >= tau.size:
        return float(z_face[-1]) / DEPTH_EXTRAPOLATION
    t0, t1 = tau[k], tau[k + 1]
    frac = 0.0 if t0 == t1 else (t0 - target) / (t0 - t1)
    z_hit = z_face[k] + frac * (z_face[k + 1] - z_face[k])
    return float(z_hit) / DEPTH_EXTRAPOLATION


def run(outdir=None, *, additive_dissipation: bool = False,
        stable_dissipation: bool = False,
        nz: int = NZ) -> dict[str, float]:
    """Integrate the prescribed column and return the gate metrics.

    The scored quantities are averaged over the final hour exactly as
    the intercomparison prescribes, EXCEPT the profile-derived ones
    (depth, jet, peak diffusivity), which are taken from the final
    state -- the column is quasi-steady by hour 9 and the difference is
    reported, not assumed, by ``depth_last_hour_drift``.
    """
    from woof.verify import sase_ref

    dz, z = grid(nz)
    steps = int(round(RUN_SECONDS / DT))
    avg_steps = int(round(AVERAGE_SECONDS / DT))
    out = sase_ref.column_stable_cooling(
        GEO_U, GEO_V, FCOR, int(nz), dz, sounding(z), DT, steps,
        THETA_SURFACE_0, COOLING_RATE_K_PER_HOUR / 3600.0, z0=Z0,
        e_init=initial_energy(z),
        stable_dissipation=stable_dissipation,
        additive_dissipation=additive_dissipation)
    # surface quantities: final-hour means, as prescribed
    ust = float(np.mean(out["ust"][-avg_steps:]))
    hfx = float(np.mean(out["hfx_kin"][-avg_steps:]))
    tst = float(np.mean(out["tstar"][-avg_steps:]))
    lmo = (ust * ust * float(out["theta"][0])
           / (sase_ref.KARMAN * sase_ref.G_ACCEL * tst)
           if tst > 0.0 else float("inf"))
    uw_s = -ust * ust * out["u"][0] / max(
        float(np.hypot(out["u"][0], out["v"][0])), 1.0e-12)
    vw_s = -ust * ust * out["v"][0] / max(
        float(np.hypot(out["u"][0], out["v"][0])), 1.0e-12)
    depth = boundary_layer_depth(out["z_face"], out["uw"], out["vw"],
                                 uw_s, vw_s)
    speed = np.hypot(out["u"], out["v"])
    kjet = int(np.argmax(speed))
    angle = math.degrees(math.atan2(float(out["v"][0]),
                                    float(out["u"][0])))
    metrics = {
        "nan": float(not np.all(np.isfinite(np.concatenate(
            [out["theta"], out["u"], out["v"], out["e"]])))),
        "boundary_layer_depth": depth,
        "depth_les_ratio": depth / LES_REFERENCE[
            "boundary_layer_depth_m"][0],
        "friction_velocity": ust,
        "surface_heat_flux": hfx,
        "surface_wind_angle": angle,
        "jet_max_speed": float(speed[kjet]),
        "jet_height": float(z[kjet]),
        "obukhov_length": float(lmo),
        "mixing_stayed_bounded": float(np.max(out["kv"])),
        "peak_energy": float(np.max(out["e"])),
        "surface_theta_drop": float(THETA_SURFACE_0
                                    - out["theta_s"][-1]),
    }
    if outdir is not None:
        outdir = Path(outdir)
        outdir.mkdir(parents=True, exist_ok=True)
        tag = ("additive" if additive_dissipation else
               "stable" if stable_dissipation else "head")
        np.savez(outdir / f"gabls1_{tag}.npz",
                 **{k: np.asarray(v) for k, v in out.items()})
        (outdir / f"gabls1_{tag}.json").write_text(
            json.dumps(metrics, indent=2, sort_keys=True), newline="\n")
    return metrics


def compare(outdir=None, *, legs=("head", "additive")) -> dict:
    """Score several closure configurations on the identical case."""
    report: dict[str, object] = {
        "gates": dict(GATES), "les_reference": dict(LES_REFERENCE),
        "scm_ensemble": dict(SCM_ENSEMBLE_DEPTH_M), "legs": {}}
    for leg in legs:
        metrics = run(outdir, additive_dissipation=(leg == "additive"),
                      stable_dissipation=(leg == "stable"))
        passed = all(lo <= metrics[name] <= hi
                     for name, (lo, hi) in GATES.items())
        report["legs"][leg] = {"metrics": metrics, "pass": bool(passed)}
    return report


def main(argv=None) -> int:
    """``python -m woof.verify.cases.gabls1 [--out DIR] [LEG...]``"""
    import argparse

    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("legs", nargs="*",
                        default=["head", "additive"],
                        choices=["head", "additive", "stable"])
    parser.add_argument("--out", default=None)
    args = parser.parse_args(argv)
    report = compare(args.out, legs=tuple(args.legs))
    print(json.dumps(report, indent=2, sort_keys=True, default=float))
    return 0 if all(entry["pass"]
                    for entry in report["legs"].values()) else 1


if __name__ == "__main__":                       # pragma: no cover
    raise SystemExit(main())
