! Harness stand-ins for the four pieces of the WRF framework the CAM UW PBL
! sources USE but that are not physics: none of them carries a number the
! scheme computes with.
!
! * module_state_description is GENERATED by WRF's Registry tool.  The CAM
!   modules read one name from it, param_num_moist, and only as the static
!   dimension of module_cam_support's pcnst parameter; every loop the scheme
!   runs is bounded by pcnst_runtime (= 5, set by CAM_INIT) instead.  Any
!   value >= 5 compiles the same arithmetic.
! * module_wrf_error: the CAM files USE it for wrf_message/wrf_error_fatal,
!   which in WRF are external subroutines defined beside the module
!   (frame/module_wrf_error.F).  Messages are dropped; a fatal stops the
!   oracle with a non-zero status so no fixture is written after one.
! * modal_aero_data is USEd by module_bl_camuwpbl_driver.F under
!   #define MODAL_AERO, but every reference to its contents in that file sits
!   in commented-out code (driver lines 630-639 and 1034-1045); the empty
!   module is what the driver actually consumes.
module module_state_description
  implicit none
  integer, parameter :: param_num_moist = 16
  integer, parameter :: param_first_scalar = 2
end module module_state_description

module module_wrf_error
  implicit none
  character(len=256) :: wrf_err_message
end module module_wrf_error

module modal_aero_data
  implicit none
end module modal_aero_data

subroutine wrf_message(str)
  implicit none
  character(len=*), intent(in) :: str
end subroutine wrf_message

subroutine wrf_debug(level, str)
  implicit none
  integer, intent(in) :: level
  character(len=*), intent(in) :: str
end subroutine wrf_debug

subroutine wrf_error_fatal(str)
  implicit none
  character(len=*), intent(in) :: str
  write(0, '(a,a)') 'WRF FATAL: ', trim(str)
  stop 99
end subroutine wrf_error_fatal
