"""Bitwise parity of woof.core.noahmp_snow against the pinned WRF v4.6.1 oracle.

The fixture ``woof/data/noahmp/oracle/noahmp-snow.csv`` is generated by
``tools/noahmp_wrf461_oracle/build_snow.py`` from the unmodified WRF sources
(accessibility lift only, proven byte-neutral in the object code).  Every row
carries the raw IEEE binary32 bit pattern, so the comparison here is bitwise:
no tolerance is applied anywhere and the gate is ``max_ulp == 0``.
"""

from __future__ import annotations

import csv
from collections import defaultdict
from pathlib import Path

import numpy as np
import pytest

from woof.core.fp32_ulp import assert_bit_exact, max_ulp
from woof.core import noahmp_snow as S

FIXTURE = (Path(__file__).resolve().parent.parent
           / "woof" / "data" / "noahmp" / "oracle" / "noahmp-snow.csv")

NSNOW = 3
NSOIL = 4

STATE_SCALARS = ("snowh", "sneqv")
STATE_SNOW = ("snice", "snliq")
STATE_FULL = ("stc", "zsnso", "dzsnso")
STATE_SOIL = ("sh2o", "sice")


def _bits_to_f32(hexbits: str) -> np.float32:
    return np.uint32(int(hexbits, 16)).view(np.float32)


@pytest.fixture(scope="module")
def fixture():
    assert FIXTURE.is_file(), f"missing oracle fixture {FIXTURE}"
    rows = list(csv.DictReader(FIXTURE.open(newline="")))
    assert rows, "oracle fixture is empty"
    data: dict = defaultdict(dict)
    order: list = []
    for r in rows:
        key = (r["leaf"], r["case"])
        if key not in data:
            order.append(key)
        stage = data[key].setdefault(r["stage"], {})
        idx = int(r["index"])
        if r["dtype"] == "int":
            stage[(r["field"], idx)] = int(r["value"])
        else:
            v = _bits_to_f32(r["bits"])
            # The decimal column must round-trip to the same float32, or the
            # fixture is internally inconsistent.
            assert np.float32(r["value"]).view(np.uint32) == v.view(np.uint32), (
                f"{key} {r['field']}[{idx}]: decimal {r['value']} does not "
                f"round-trip to bits {r['bits']}"
            )
            stage[(r["field"], idx)] = v
    return data, order


def _vec(stage: dict, name: str, lo: int, hi: int) -> np.ndarray:
    return np.array([stage[(name, i)] for i in range(lo, hi + 1)], dtype=np.float32)


def _ivec(stage: dict, name: str, lo: int, hi: int) -> np.ndarray:
    return np.array([stage[(name, i)] for i in range(lo, hi + 1)], dtype=np.int32)


def _build_column(stage: dict) -> S.SnowColumn:
    return S.SnowColumn(
        nsnow=NSNOW, nsoil=NSOIL,
        isnow=stage[("isnow", 0)],
        snowh=stage[("snowh", 0)],
        sneqv=stage[("sneqv", 0)],
        snice=_vec(stage, "snice", -NSNOW + 1, 0),
        snliq=_vec(stage, "snliq", -NSNOW + 1, 0),
        stc=_vec(stage, "stc", -NSNOW + 1, NSOIL),
        zsnso=_vec(stage, "zsnso", -NSNOW + 1, NSOIL),
        dzsnso=_vec(stage, "dzsnso", -NSNOW + 1, NSOIL),
        sh2o=_vec(stage, "sh2o", 1, NSOIL),
        sice=_vec(stage, "sice", 1, NSOIL),
    )


def _run(leaf: str, inp: dict):
    """Drive one leaf from its fixture input rows; return (column, extras)."""
    if leaf == "combo":
        dz, wliq, wice, t = S.combo(
            inp[("dz", 0)], inp[("wliq", 0)], inp[("wice", 0)], inp[("t", 0)],
            inp[("dz2", 0)], inp[("wliq2", 0)], inp[("wice2", 0)], inp[("t2", 0)])
        return None, {"dz": dz, "wliq": wliq, "wice": wice, "t": t}

    col = _build_column(inp)

    if leaf == "snowfall":
        S.snowfall(col, inp[("dt", 0)], inp[("qsnow", 0)],
                   inp[("snowhin", 0)], inp[("sfctmp", 0)])
        return col, {}

    if leaf == "compact":
        S.compact(col, inp[("dt", 0)],
                  _ivec(inp, "imelt", -NSNOW + 1, 0),
                  _vec(inp, "ficeold", -NSNOW + 1, 0))
        return col, {}

    if leaf == "combine":
        p1, p2 = S.combine(col, inp[("ponding1", 0)], inp[("ponding2", 0)])
        return col, {"ponding1": p1, "ponding2": p2}

    if leaf == "divide":
        S.divide(col)
        return col, {}

    if leaf == "snowh2o":
        qsnbot, p1, p2 = S.snowh2o(
            col, inp[("dt", 0)], inp[("qsnfro", 0)], inp[("qsnsub", 0)],
            inp[("qrain", 0)], inp[("ssi", 0)], inp[("snow_ret_fac", 0)],
            inp[("ponding1", 0)], inp[("ponding2", 0)])
        return col, {"qsnbot": qsnbot, "ponding1": p1, "ponding2": p2}

    if leaf == "snowwater":
        qsnbot, snoflow, p1, p2 = S.snowwater(
            col, inp[("dt", 0)], _vec(inp, "zsoil", 1, NSOIL),
            _ivec(inp, "imelt", -NSNOW + 1, 0),
            _vec(inp, "ficeold", -NSNOW + 1, 0),
            inp[("sfctmp", 0)], inp[("snowhin", 0)], inp[("qsnow", 0)],
            inp[("qsnfro", 0)], inp[("qsnsub", 0)], inp[("qrain", 0)],
            inp[("ssi", 0)], inp[("snow_ret_fac", 0)])
        return col, {"qsnbot": qsnbot, "snoflow": snoflow,
                     "ponding1": p1, "ponding2": p2}

    raise AssertionError(f"unknown leaf {leaf!r}")


def _compare(leaf: str, case: str, col, extras: dict, out: dict) -> int:
    """Assert bitwise parity for every emitted output; return the max ULP."""
    worst = 0
    checked = set()

    for name, value in extras.items():
        want = out[(name, 0)]
        got = np.float32(value)
        assert_bit_exact(got, want, f"{leaf}/{case}:{name}")
        worst = max(worst, max_ulp(got, want))
        checked.add((name, 0))

    if col is not None:
        assert col.isnow == out[("isnow", 0)], (
            f"{leaf}/{case}: isnow {col.isnow} != {out[('isnow', 0)]}")
        checked.add(("isnow", 0))

        for name in STATE_SCALARS:
            got = np.float32(getattr(col, name))
            assert_bit_exact(got, out[(name, 0)], f"{leaf}/{case}:{name}")
            worst = max(worst, max_ulp(got, out[(name, 0)]))
            checked.add((name, 0))

        for names, lo, hi in ((STATE_SNOW, -NSNOW + 1, 0),
                              (STATE_FULL, -NSNOW + 1, NSOIL),
                              (STATE_SOIL, 1, NSOIL)):
            for name in names:
                got = getattr(col, name)
                want = _vec(out, name, lo, hi)
                assert_bit_exact(got, want, f"{leaf}/{case}:{name}")
                worst = max(worst, max_ulp(got, want))
                checked.update((name, i) for i in range(lo, hi + 1))

    missing = set(out) - checked
    assert not missing, f"{leaf}/{case}: fixture outputs never compared: {sorted(missing)}"
    return worst


def _cases(fixture, leaf):
    data, order = fixture
    return [(l, c) for (l, c) in order if l == leaf]


@pytest.mark.parametrize("leaf", ["combo", "snowfall", "compact", "combine",
                                  "divide", "snowh2o", "snowwater"])
def test_leaf_is_bit_exact(fixture, leaf):
    data, order = fixture
    cases = _cases(fixture, leaf)
    assert cases, f"fixture has no cases for {leaf}"
    worst = 0
    for key in cases:
        inp = data[key]["input"]
        out = data[key]["output"]
        col, extras = _run(leaf, inp)
        worst = max(worst, _compare(leaf, key[1], col, extras, out))
    assert worst == 0, f"{leaf}: max_ulp {worst} (gate is 0)"


def test_every_fixture_row_is_exercised(fixture):
    """No leaf and no case in the fixture may be silently skipped."""
    data, order = fixture
    leaves = {l for (l, _) in order}
    assert leaves == {"combo", "snowfall", "compact", "combine", "divide",
                      "snowh2o", "snowwater"}, leaves
    for key in order:
        assert set(data[key]) == {"input", "output"}, key


def test_port_stays_in_float32(fixture):
    """Every array the port writes must remain binary32."""
    data, order = fixture
    for key in order:
        if key[0] == "combo":
            _, extras = _run("combo", data[key]["input"])
            for name, v in extras.items():
                assert np.float32(v).dtype == np.float32, (key, name)
            continue
        col, extras = _run(key[0], data[key]["input"])
        for name in STATE_SNOW + STATE_FULL + STATE_SOIL:
            assert getattr(col, name).dtype == np.float32, (key, name)
        for name, v in extras.items():
            assert np.asarray(v).dtype == np.float32, (key, name)


def test_layer_transitions_are_bound(fixture):
    """The fixture must bind layer-count changes in both directions.

    COMBINE, DIVIDE and their callers restructure the pack, so a fixture that
    only held a steady layer count could not detect a restructuring bug.
    """
    data, order = fixture
    seen: dict[str, set] = defaultdict(set)
    for leaf, case in order:
        if leaf == "combo":
            continue
        a = data[(leaf, case)]["input"][("isnow", 0)]
        b = data[(leaf, case)]["output"][("isnow", 0)]
        if a != b:
            seen[leaf].add((a, b))

    # decreasing magnitude (layers merged away)
    assert (-3, -2) in seen["combine"]
    assert (-3, -1) in seen["combine"]
    assert (-2, 0) in seen["combine"]
    assert (-1, 0) in seen["combine"]
    assert (-3, 0) in seen["combine"]
    # increasing magnitude (layers created or split)
    assert (0, -1) in seen["snowfall"]
    assert (-1, -2) in seen["divide"]
    assert (-1, -3) in seen["divide"]
    assert (-2, -3) in seen["divide"]
    # inside SNOWH2O, via its internal COMBINE call
    assert (-2, -1) in seen["snowh2o"]
    assert (-1, 0) in seen["snowh2o"]
    # and through the composed driver, both directions
    assert (0, -1) in seen["snowwater"]
    assert (-1, -2) in seen["snowwater"]
    assert (-2, -1) in seen["snowwater"]
    assert (-1, 0) in seen["snowwater"]


def test_combine_leaves_unassigned_ponding_alone(fixture):
    """COMBINE's INTENT(OUT) ponding dummies are not assigned on every path.

    gfortran passes them by reference, so the caller's value survives.  The
    fixture enters every COMBINE case with a -999.0 sentinel; at least one case
    must return it untouched, or the port's pass-through semantics would be
    untested and a port that zeroed them would pass anyway.
    """
    data, order = fixture
    untouched = [c for (l, c) in order if l == "combine"
                 and data[(l, c)]["output"][("ponding2", 0)] == np.float32(-999.0)]
    assert untouched, "no COMBINE case leaves ponding2 unassigned"
    touched = [c for (l, c) in order if l == "combine"
               and data[(l, c)]["output"][("ponding2", 0)] != np.float32(-999.0)]
    assert touched, "no COMBINE case assigns ponding2"


def test_zsnso_incoming_value_is_dead(fixture):
    """The incoming ZSNSO can never influence an output.

    A mutation-study survivor: overwriting ``col.zsnso`` on entry to SNOWWATER
    changes nothing.  That is a property of the routines, not a fixture gap.

    * COMPACT declares ZSNSO ``INTENT(INOUT)`` but never mentions it in its
      executable body, so it is a pure pass-through.
    * SNOWWATER rewrites every element before anything reads it: layers below
      ``ISNOW+1`` are zeroed by the empty-layer loop, ``ISNOW+1`` is seeded
      from ``DZSNSO``, and the rest come from the running sum, which only ever
      reads the element written on the previous iteration.

    Poisoning the input with NaN turns both claims into checks.
    """
    data, order = fixture
    poison = np.float32(np.nan)

    sw = [k for k in order if k[0] == "snowwater"]
    assert sw
    for key in sw:
        inp = dict(data[key]["input"])
        for i in range(-NSNOW + 1, NSOIL + 1):
            inp[("zsnso", i)] = poison
        col, extras = _run("snowwater", inp)
        _compare("snowwater", key[1] + "[zsnso poisoned]", col, extras,
                 data[key]["output"])

    cp = [k for k in order if k[0] == "compact"]
    assert cp
    for key in cp:
        inp = dict(data[key]["input"])
        for i in range(-NSNOW + 1, NSOIL + 1):
            inp[("zsnso", i)] = poison
        col, _ = _run("compact", inp)
        # ZSNSO comes back exactly as poisoned: COMPACT never writes it ...
        assert np.all(np.isnan(col.zsnso)), (
            f"compact/{key[1]}: COMPACT wrote ZSNSO")
        # ... and nothing else moved because of it.
        for names, lo, hi in ((STATE_SNOW, -NSNOW + 1, 0),
                              (("stc", "dzsnso"), -NSNOW + 1, NSOIL),
                              (STATE_SOIL, 1, NSOIL)):
            for name in names:
                assert_bit_exact(getattr(col, name),
                                 _vec(data[key]["output"], name, lo, hi),
                                 f"compact/{key[1]}[zsnso poisoned]:{name}")


def test_compact_ficeold_floor_is_unreachable():
    """COMPACT's ``MAX(1.0E-6, FICEOLD)`` divisor can never change an output.

    The other mutation-study survivor.  The compaction block is guarded by
    ``SNICE(J) > 0.1``, so ``FICE = SNICE/(SNICE+SNLIQ)`` is bounded below by
    ``0.1/(0.1+SNLIQ)``.  The 1.0E-6 floor is only *selected* when
    ``FICEOLD < 1.0E-6``, and in that regime ``FICEOLD - FICE`` is already
    negative, so ``MAX(0.0, ...)`` returns zero and DDZ3 is zero whatever the
    divisor is.  Checked over the reachable domain rather than asserted.
    """
    rng = np.random.default_rng(20260725)
    n = 200_000
    # SNICE strictly above the 0.1 guard, spanning six decades of pack mass.
    snice = np.float32(10.0) ** np.float32(rng.uniform(-1, 4, n)) + np.float32(0.1)
    # SNLIQ up to a physically absurd 1e4 kg/m2, to stress the bound.
    snliq = np.float32(10.0) ** np.float32(rng.uniform(-6, 4, n))
    # FICEOLD anywhere strictly below the floor, including exactly zero.
    ficeold = np.float32(rng.uniform(0.0, 1.0, n)) * np.float32(1.0e-6)

    fice = (snice / (snice + snliq)).astype(np.float32)
    assert np.all(ficeold < np.float32(1.0e-6))
    numerator = (ficeold - fice).astype(np.float32)
    assert np.all(numerator <= np.float32(0.0)), (
        "FICEOLD can exceed FICE below the 1.0E-6 floor; the guard is live "
        "after all and the fixture must bind it"
    )
