"""LW extension geometry against an admitted WRF 4.7.1 solver boundary.

The stored native expectations are not regenerated by the implementation.
GPU-marked tests exercise the actual rp_prep kernel, including partial blocks.
"""
from hashlib import sha256
import json
import math
import os
from pathlib import Path

import numpy as np
import pytest

from woof.core import rrtmg_legacy_prep as prep

DATA = Path(__file__).parent / "data" / "wrf471_lw_extension"
FIELDS = ("plev", "play", "tlev", "tlay", "o3vmr")
SURFACES = {"tsk", "emiss", "xland", "xice", "snow", "xlat"}
F = np.float32


def assert_words(actual, expected, field):
    assert np.asarray(actual).dtype == np.dtype(F), field + " must be float32"
    actual = np.ascontiguousarray(actual, dtype=F)
    expected = np.ascontiguousarray(expected, dtype=F)
    assert actual.shape == expected.shape, field
    np.testing.assert_array_equal(actual.view(np.uint32),
                                  expected.view(np.uint32), err_msg=field)


@pytest.fixture(scope="module")
def native():
    provenance = json.loads((DATA / "provenance.json").read_text())
    file = DATA / provenance["array_file"]
    assert sha256(file.read_bytes()).hexdigest() == provenance["array_sha256"]
    assert provenance["accepted_source_artifact_sha256"]["main/wrf.exe"] == (
        "7680ed5b3483c7ab3d90589707a15fb2bb524cecd7de78948619b4ce794c2de8")
    with np.load(file, allow_pickle=False) as archive:
        values = {name: archive[name].copy() for name in archive.files}
    inputs = {name.removeprefix("input__"): value[()] if value.ndim == 0
              else value for name, value in values.items()
              if name.startswith("input__")}
    expected = {name: values["expected__" + name] for name in FIELDS}
    assert inputs["p8w"][-1] == F(5000)
    assert inputs["nlayers"] == 62 and inputs["p3d"].size == 49
    return inputs, expected


@pytest.fixture(autouse=True)
def cpu_profile_oracle(monkeypatch):
    # Force the independent NumPy profile tables even on a GPU test host.
    monkeypatch.setattr(prep, "_PERFWAVE_DEVICE_XP", None)


def batch_inputs(native, count, tops_pa=None):
    inputs, _ = native
    result = {}
    for name, value in inputs.items():
        if isinstance(value, np.ndarray):
            result[name] = np.repeat(value[None, :], count, axis=0)
        elif name in SURFACES:
            result[name] = np.full(count, value, dtype=F)
        else:
            result[name] = value
    if tops_pa is not None:
        result["p8w"][:, -1] = np.asarray(tops_pa, dtype=F)
        result["p3d"][:, -1] = F(.5) * (
            result["p8w"][:, -2] + result["p8w"][:, -1])
    return result


def scalar_inputs(batch, column):
    return {name: value[column] if isinstance(value, np.ndarray) else value
            for name, value in batch.items()}


def test_native_fixture_contains_original_four_hpa_grid(native):
    _, expected = native
    # Literal independent native words catch a fixture or count regression.
    assert_words(expected["plev"][-14:],
                 [50, 46, 42, 38, 34, 30, 26, 22, 18, 14, 10, 6, 2, 0],
                 "native interfaces")
    assert_words(expected["play"][-13:],
                 [48, 44, 40, 36, 32, 28, 24, 20, 16, 12, 8, 4, 1],
                 "native midpoints")


def test_scalar_prep_matches_native_pressure_temperature_and_ozone(native):
    inputs, expected = native
    actual = prep.lwrad_prep(**inputs)
    for field in FIELDS:
        assert_words(actual[field], expected[field], field)


def test_native_profile_words_do_not_call_platform_transcendentals(native, monkeypatch):
    # Pressure-linear temperature interpolation and pressure-thickness ozone
    # averaging must not pin glibc/UCRT exp/log/pow/trig results. The separate
    # trace-gas EXP uses the existing deterministic noahmp_libm transcription.
    def refused(*args, **kwargs):
        raise AssertionError("native LW profile words must not use platform libm")

    for name in ("exp", "expm1", "log", "log10", "log1p", "pow", "sqrt",
                 "sin", "cos", "tan", "asin", "acos", "atan", "atan2"):
        monkeypatch.setattr(math, name, refused)
    for name in ("exp", "expm1", "log", "log10", "log1p", "power", "sqrt",
                 "sin", "cos", "tan", "arcsin", "arccos", "arctan", "arctan2"):
        monkeypatch.setattr(np, name, refused)
    inputs, expected = native
    actual = prep.lwrad_prep(**inputs)
    for field in FIELDS:
        assert_words(actual[field], expected[field], field)


@pytest.mark.parametrize("count", [1, 5, 129])
def test_batched_native_columns_match_independent_native_words(native, count):
    _, expected = native
    actual = prep.lwrad_prep_batch(**batch_inputs(native, count))
    for field in FIELDS:
        assert_words(actual[field], np.repeat(expected[field][None, :],
                                              count, axis=0), field)


@pytest.mark.parametrize("top_pa,extras,levels", [
    (5000, 13, [50, 46, 42, 38, 34, 30, 26, 22, 18, 14, 10, 6, 2, 0]),
    (4800, 12, [48, 44, 40, 36, 32, 28, 24, 20, 16, 12, 8, 4, 0]),
    (5200, 13, [52, 48, 44, 40, 36, 32, 28, 24, 20, 16, 12, 8, 4, 0]),
    (200, 1, [2, 0]),
    (600, 2, [6, 2, 0]),
])
def test_ordinary_tops_keep_wrf_nint_count_and_four_hpa_grid(
        native, top_pa, extras, levels):
    inputs = batch_inputs(native, 1, [top_pa])
    inputs["nlayers"] = prep.compute_lw_nlayers(50, F(top_pa))
    assert inputs["nlayers"] == 49 + extras
    actual = prep.lwrad_prep(**scalar_inputs(inputs, 0))
    assert_words(actual["plev"][49:], levels, "ordinary top interfaces")


def test_nint_count_half_tie_and_adjacent_input_words():
    tie = F(5000)
    below = np.nextafter(tie, F(-np.inf))
    above = np.nextafter(tie, F(np.inf))
    assert prep.compute_lw_nlayers(50, below) == 49 + 12
    assert prep.compute_lw_nlayers(50, tie) == 49 + 13
    assert prep.compute_lw_nlayers(50, above) == 49 + 13


def edge_inputs(native):
    # Adjacent Pa words convert to the adjacent hPa words around 48.
    threshold = F(4800)
    tops = np.array([5000, np.nextafter(threshold, F(-np.inf)), threshold,
                     np.nextafter(threshold, F(np.inf)), 100], dtype=F)
    return batch_inputs(native, tops.size, tops)


def assert_edge_geometry(actual, inputs):
    tops = np.asarray(inputs["p8w"][:, -1] / F(100), dtype=F)
    assert_words(tops[1:4], [np.nextafter(F(48), F(-np.inf)), F(48),
                            np.nextafter(F(48), F(np.inf))],
                 "adjacent converted threshold words")
    levels = np.asarray(actual["plev"][:, 49:], dtype=F)
    assert np.all(levels[:, :-1] > 0)
    assert np.all(np.diff(levels, axis=1) < 0)
    assert np.all(np.asarray(actual["play"]) > 0)
    assert_words(levels[:, -1], np.zeros(tops.size, dtype=F), "terminal zero")
    # The safe adjacent-up column must keep four, even though 13*4 > top.
    assert_words(levels[[0, 3], 1], tops[[0, 3]] - F(4), "safe step")
    # Equality and next-down must preserve the original conservative fallback.
    for column in (1, 2, 4):
        step = F(tops[column] / F(13))
        want = [tops[column]]
        for _ in range(12):
            want.append(F(want[-1] - step))
        want.append(F(0))
        assert_words(levels[column], want, "retained shallow fallback")
    for field in FIELDS:
        assert np.isfinite(np.asarray(actual[field])).all(), field


def test_mixed_shallow_columns_and_threshold_words(native):
    inputs = edge_inputs(native)
    actual = prep.lwrad_prep_batch(**inputs)
    assert_edge_geometry(actual, inputs)
    for column in range(5):
        scalar = prep.lwrad_prep(**scalar_inputs(inputs, column))
        for field in FIELDS:
            assert_words(actual[field][column], scalar[field], field)


def test_single_extra_layer_has_only_the_terminal_zero(native):
    inputs = batch_inputs(native, 2, [200, 5000])
    inputs["nlayers"] = 50
    actual = prep.lwrad_prep_batch(**inputs)
    assert_words(actual["plev"][:, 49:], [[2, 0], [50, 0]], "one extra")
    assert_words(actual["play"][:, 49], [1, 25], "one extra midpoint")
    for column in range(2):
        scalar = prep.lwrad_prep(**scalar_inputs(inputs, column))
        for field in FIELDS:
            assert np.isfinite(actual[field]).all(), field
            assert_words(actual[field][column], scalar[field], field)


def test_zero_extra_layers_remain_refused(native):
    inputs = batch_inputs(native, 1)
    inputs["nlayers"] = 49
    for function, kwargs in ((prep.lwrad_prep_batch, inputs),
                             (prep.lwrad_prep, scalar_inputs(inputs, 0))):
        with pytest.raises(ValueError, match="at least kte\\+1"):
            function(**kwargs)


@pytest.mark.gpu
@pytest.mark.parametrize("count", [1, 5, 129])
def test_actual_device_prep_matches_native_at_partial_batch_widths(native, count):
    if os.environ.get("GPUWM_NO_LOCAL_GPU") == "1":
        pytest.skip("GPU execution requires an authorized remote device")
    cp = pytest.importorskip("cupy")
    from woof.core.rrtmg_legacy_device import lwrad_prep_batch_device
    inputs = batch_inputs(native, count)
    device = {name: cp.asarray(value) if isinstance(value, np.ndarray)
              else value for name, value in inputs.items()}
    actual = lwrad_prep_batch_device(**device)
    for field, expected in native[1].items():
        assert isinstance(actual[field], cp.ndarray)
        assert_words(cp.asnumpy(actual[field]),
                     np.repeat(expected[None, :], count, axis=0), field)


@pytest.mark.gpu
def test_actual_device_threshold_shallow_and_single_extra_paths(native):
    if os.environ.get("GPUWM_NO_LOCAL_GPU") == "1":
        pytest.skip("GPU execution requires an authorized remote device")
    cp = pytest.importorskip("cupy")
    from woof.core.rrtmg_legacy_device import lwrad_prep_batch_device
    inputs = edge_inputs(native)
    device = {name: cp.asarray(value) if isinstance(value, np.ndarray)
              else value for name, value in inputs.items()}
    actual = {field: cp.asnumpy(value) for field, value in
              lwrad_prep_batch_device(**device).items() if field in FIELDS}
    assert_edge_geometry(actual, inputs)
    host = prep.lwrad_prep_batch(**inputs)
    for field in FIELDS:
        assert_words(actual[field], host[field], field)
    device["nlayers"] = 50
    one = lwrad_prep_batch_device(**device)
    assert_words(cp.asnumpy(one["plev"])[:, 49:],
                 np.column_stack((inputs["p8w"][:, -1] / F(100),
                                  np.zeros(5, dtype=F))), "device one extra")
    inputs["nlayers"] = 50
    host_one = prep.lwrad_prep_batch(**inputs)
    for field in FIELDS:
        assert_words(cp.asnumpy(one[field]), host_one[field], field)
    device["nlayers"] = 49
    with pytest.raises(ValueError, match="at least kte\\+1"):
        lwrad_prep_batch_device(**device)
