"""The host mirror of Thompson's entry block agrees with WRF BIT FOR BIT.

:mod:`woof.core.thompson_entry` exists so a host repair gives the
scheme's own answer.  "The scheme's own answer" is a bit pattern, not an
approximation of one, so this file holds the mirror to the arithmetic
WRF actually performs rather than to the algebra WRF's source describes.

Two independent holds, because either alone can drift quietly:

* :func:`_wrf_cloud`, :func:`_wrf_ice` and :func:`_wrf_rain` transcribe
  ``phys/module_mp_thompson.F:1827-1898`` line by line, giving every
  intermediate the precision the Fortran DECLARES it at rather than the
  precision Python would pick.  The declarations that matter are
  :1580 (``rc``/``ri``/``rr`` and ``nc``/``ni``/``nr`` REAL),
  :1589 (``mvd_r`` REAL), :1597-1598 (``lamc``/``lami``/``ilami``/
  ``lamr`` DOUBLE) and :1599 (``xDc``/``xDi`` REAL).
* :data:`WRF_ORDER_VALUES` pins the numbers those functions produce, so
  a change made to the transcription and to the module together is still
  a failure.  The literals were computed once from the transcription and
  are not regenerated by this file.

WHY THIS IS NOT PEDANTRY.  Four of the places the precisions matter move
answers, not ULPs:

* the ``nu_c`` quotient (:1832) is REAL in WRF.  At
  ``nc = 666666688`` m^-3 the REAL quotient is exactly 1.5 and ``NINT``
  gives 2; formed in float64 it is 1.4999999520000016 and ``NINT``
  gives 1, so the mirror reads a DIFFERENT GAMMA-TABLE ROW and returns
  666667610.209 where the scheme returns 666667430.200.
* the rain number (:1885, :1893, :1897) divides by ``am_r`` AFTER the
  power, in DOUBLE, because Fortran's ``*`` and ``/`` associate to the
  left.  Dividing first, in REAL, moves one cell in five by a float32
  ULP.
* ``D0r*0.75`` (:1894) is a REAL product.  Formed in float64 it is one
  ULP higher, which moves the rebuilt lambda from 97920.0 to
  97919.9921875 and the number it rebuilds by two ULPs.
* ``xDc`` (:1834) and ``xDi`` (:1862) are REAL, and ``xDi`` is a
  MULTIPLY by ``ilami`` rather than a divide by ``lami``.  Both decide
  clamp branches.  Neither changed an answer on the dense sweeps in this
  file, and both are held anyway: an unreachable difference is still a
  difference, and the sweeps are what makes "unreachable" a measurement.
"""
import numpy as np
import pytest

from woof.core.thompson_aerosol_contract import (
    AM_R, CCE2, CCG1, CCG2, NT_C_MAX, OCG1, OCG2)
from woof.core import thompson_entry

R = np.float32
D = np.float64

_am_r = R(AM_R)
_bm_r = R(3.0)
_obmr = R(R(1.0) / R(3.0))
_am_i = R(R(R(3.1415926536) * R(890.0)) / R(6.0))
_bm_i = R(3.0)
_obmi = R(R(1.0) / R(3.0))
_mu_i = R(0.0)
_mu_r = R(0.0)
_D0c = R(1.0e-6)
_D0r = R(50.0e-6)
_R2 = R(1.0e-6)
_cie2 = R(_bm_i + _mu_i + R(1.0))
_cig1_oig2 = R(1.0 / 6.0)
_cig2_oig1 = R(6.0)
_crg2_org3 = R(1.0 / 6.0)
_crg3_org2 = R(6.0)
_Nt_c_max = R(NT_C_MAX)
_mvd_factor = R(R(R(3.0) + _mu_r) + R(0.672))


def _wrf_cloud(qc_per_volume, nc_per_volume):
    """:1829-1841, with :1842 omitted for the reason the module gives."""
    rc = R(qc_per_volume)
    nc = max(R(2.0), min(R(nc_per_volume), _Nt_c_max))              # :1830
    nu_c = min(15, int(np.floor(D(R(1000.0e6) / nc) + 0.5)) + 2)    # :1832
    lamc = D(np.power(R(nc * _am_r * R(CCG2[nu_c]) * R(OCG1[nu_c]) / rc),
                      _obmr))                                       # :1833
    x_dc = R(D(R(_bm_r + R(nu_c) + R(1.0))) / lamc)                 # :1834
    if x_dc < _D0c:                                                 # :1835
        lamc = D(R(CCE2[nu_c]) / _D0c)                              # :1836
    elif x_dc > R(_D0r * R(2.0)):                                   # :1837
        lamc = D(R(CCE2[nu_c]) / R(_D0r * R(2.0)))                  # :1838
    return min(D(_Nt_c_max),                                        # :1840
               D(R(R(R(CCG1[nu_c]) * R(OCG2[nu_c])) * rc) / _am_r)
               * lamc ** D(_bm_r))                                  # :1841


def _wrf_ice(qi_per_volume, ni_per_volume):
    """:1853-1869."""
    ri = R(qi_per_volume)
    ni = max(_R2, R(ni_per_volume))                                 # :1854

    def number(lami):
        # :1857 / :1865 / :1868  the REAL divide by am_i lands BEFORE the
        # DOUBLE power, because * and / associate to the left.
        return D(R(R(_cig1_oig2 * ri) / _am_i)) * lami ** D(_bm_i)

    if ni <= _R2:                                                   # :1855
        ni = R(min(D(999.0e3), number(D(_cie2 / R(5.0e-6)))))       # :1856-7
    lami = D(np.power(R(_am_i * _cig2_oig1 * ni / ri), _obmi))      # :1860
    ilami = D(1.0) / lami                                           # :1861
    x_di = R(R(_bm_i + _mu_i + R(1.0)) * ilami)                     # :1862
    if x_di < R(5.0e-6):                                            # :1863
        ni = R(min(D(999.0e3), number(D(_cie2 / R(5.0e-6)))))       # :1864-5
    elif x_di > R(300.0e-6):                                        # :1866
        ni = R(number(D(_cie2 / R(300.0e-6))))                      # :1867-8
    return D(ni)


def _wrf_rain(qr_per_volume, nr_per_volume):
    """:1880-1898."""
    rr = R(qr_per_volume)
    nr = max(_R2, R(nr_per_volume))                                 # :1881

    def number(lamr):
        # :1885 / :1893 / :1897  the divide by am_r lands AFTER the
        # power and is therefore done in DOUBLE.
        return R(D(R(_crg2_org3 * rr)) * lamr ** D(_bm_r) / D(_am_r))

    if nr <= _R2:                                                   # :1882
        nr = number(D(_mvd_factor / R(1.0e-3)))                     # :1883-5
    lamr = D(np.power(R(_am_r * _crg3_org2 * nr / rr), _obmr))      # :1888
    mvd = R(D(_mvd_factor) / lamr)                                  # :1889
    if mvd > R(2.5e-3):                                             # :1890
        nr = number(D(_mvd_factor / R(2.5e-3)))                     # :1891-3
    elif mvd < R(_D0r * R(0.75)):                                   # :1894
        nr = number(D(_mvd_factor / R(_D0r * R(0.75))))             # :1895-7
    return D(nr)


_WRF_ARMS = {"cloud": _wrf_cloud, "ice": _wrf_ice, "rain": _wrf_rain}

#: ``(species, mass per volume, number per volume, the value WRF's own
#: order produces)``.  Computed once from the transcriptions above and
#: written down, so the transcription and the module cannot drift
#: together.  Every branch of every arm is represented: the two number
#: repairs, both rain size clamps, the ice 300 um clamp, the ice cap, the
#: droplet ceiling, and the ``nu_c`` tie.
WRF_ORDER_VALUES = (
    ("cloud", 0.001, 666666688.0, 666667430.1998031),
    ("cloud", 0.0003, 100000000.0, 100000123.57862717),
    ("cloud", 1e-06, 0.0, 2675.5922111123405),
    ("ice", 0.0001, 0.0, 999000.0),
    ("ice", 0.0001, 1000.0, 84776.65625),
    ("ice", 2e-05, 4000000.0, 4000000.0),
    ("rain", 0.001, 0.0, 15760.0673828125),
    ("rain", 0.001, 100.0, 1008.6445922851562),
    ("rain", 1e-05, 10000000.0, 2988576.0),
)


@pytest.mark.parametrize("species,mass,number,expected", WRF_ORDER_VALUES)
def test_the_arms_return_the_hand_computed_wrf_order_value(
        species, mass, number, expected):
    """Each arm, on one input, against a number written down."""
    got = thompson_entry.ENTRY_ARMS[species](
        np.float32([mass]), np.float32([number]))
    assert float(got[0]) == expected


@pytest.mark.parametrize("species,mass,number,expected", WRF_ORDER_VALUES)
def test_the_transcription_still_produces_the_written_down_value(
        species, mass, number, expected):
    """The reference in this file has not drifted from its own literals."""
    assert float(_WRF_ARMS[species](mass, number)) == expected


@pytest.mark.parametrize("species", ("cloud", "ice", "rain"))
def test_the_arms_match_the_transcription_over_a_wide_random_field(species):
    """Bitwise, on 200k states that reach every branch."""
    rng = np.random.default_rng(1734)
    n = 200_000
    mass = np.float32(10.0 ** rng.uniform(-9.0, -2.0, n))
    number = np.where(rng.random(n) < 0.35, np.float32(0.0),
                      np.float32(10.0 ** rng.uniform(-3.0, 9.2, n)))
    got = thompson_entry.ENTRY_ARMS[species](mass, number)
    want = np.array([_WRF_ARMS[species](float(m), float(v))
                     for m, v in zip(mass, number)], dtype=np.float64)
    bad = np.flatnonzero(np.asarray(got) != want)
    assert bad.size == 0, (
        f"{bad.size} of {n} {species} states differ, first at "
        f"mass={mass[bad[0]]!r} number={number[bad[0]]!r}: "
        f"{got[bad[0]]!r} against {want[bad[0]]!r}")


def test_the_nu_c_quotient_is_formed_in_single_precision():
    """The tie that moves a gamma-table row, named in this file's header."""
    tie = np.float32([666666688.0])
    assert int(thompson_entry._nu_c(tie)[0]) == 4
    assert float(np.float32(1000.0e6) / tie[0]) == 1.5


def test_the_rain_minimum_diameter_is_the_real_product():
    """``D0r*0.75`` is a REAL product; in float64 it is one ULP higher."""
    assert (np.float32(thompson_entry.RAIN_MVD_MIN_M)
            == np.float32(np.float32(50.0e-6) * np.float32(0.75)))
    assert (np.float32(thompson_entry.RAIN_MVD_MIN_M)
            != np.float32(50.0e-6 * 0.75))


@pytest.mark.parametrize("threshold", (5.0e-6, 300.0e-6))
def test_the_ice_clamp_boundary_is_crossed_where_wrf_crosses_it(threshold):
    """A dense sweep straight through the xDi clamp, held bitwise.

    This is the measurement behind the claim that rounding xDi to REAL
    and forming it by multiplying by ilami changes no reachable answer:
    the sweep crosses the boundary, and the mirror agrees at every point.
    """
    ri = 1.0e-4
    lam = 4.0 / threshold
    centre = (lam ** 3) / (6.0 * float(thompson_entry.AM_I)) * ri
    ni = np.float32(centre * np.linspace(0.995, 1.005, 40_001))
    mass = np.full(ni.shape, np.float32(ri))
    got = thompson_entry.ice_number_m3(mass, ni)
    want = np.array([_wrf_ice(ri, float(v)) for v in ni], dtype=np.float64)
    assert np.array_equal(np.asarray(got), want)
    # The sweep is only evidence if it actually crosses the branch.
    assert len(np.unique(np.asarray(got))) > 1
