"""The Thompson column oracle must stay re-derivable from its stated inputs.

`woof/data/thompson/oracle/*.csv` is not test data; it is the authority the
CUDA Thompson port is judged against.  An authority that cannot be re-derived
from what it says its inputs were is not an authority, it is one machine's
memory.

These tests hold three separate promises.

1.  The receipt names the WRF source it was generated from, and the harness
    sources it was generated by, by SHA-256.  The harness hashes are checked
    against the working tree, so editing `run_column.F90` without regenerating
    fails here -- loudly, at the moment the harness moves, instead of silently
    at some later date when somebody notices two fixtures disagree.

2.  Every committed fixture hashes to what the receipt recorded, and the set
    rolls up to the recorded rollup.  Editing a CSV by hand fails here.

3.  The fixtures are internally self-consistent: `p_pa` and `pii` are built
    from `z` alone by code that does not depend on the scenario, so every
    fixture that shares a `dz` must agree on them exactly.

Promise 3 is the one that was broken.  `warm`, `mixed` and `ice` were written
when `run_column.F90` was 227 lines and GCC's vectoriser turned the base-state
`exp`/`**` loop into glibc libmvec SIMD calls; the other 43 were written after
the file grew past a thousand lines and the same `-O2` no longer vectorised
that loop.  libmvec is not bit-identical to scalar libm, so the committed set
disagreed with itself by 1-2 ULP on scenario-independent arithmetic, and no
build of any compiler could reproduce all of it at once.  `build.sh` now pins
`-fno-tree-vectorize`, which removes libmvec from the link entirely and makes
the fixtures invariant across gfortran 12/13/14/15 at -O1/-O2/-O3.
"""

from __future__ import annotations

import csv
import collections
import hashlib
import pathlib

import pytest


_REPO = pathlib.Path(__file__).parents[1]
_ORACLE = _REPO / "woof" / "data" / "thompson" / "oracle"
_HARNESS = _REPO / "tools" / "thompson_wrf461_oracle"
_RECEIPT = _ORACLE / "PROVENANCE.txt"

_HARNESS_FILES = ("build.sh", "stub_wrf.F90", "generate_tables.F90",
                  "dump_aux_tables.F90", "run_column.F90")


def _sha256(path: pathlib.Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _receipt() -> dict[str, dict[str, str]]:
    """Parse the INI-ish receipt `build.sh` writes."""
    sections: dict[str, dict[str, str]] = {}
    current: dict[str, str] | None = None
    for line in _RECEIPT.read_text(encoding="ascii").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("[") and line.endswith("]"):
            current = sections.setdefault(line[1:-1], {})
            continue
        assert current is not None, f"key outside a section: {line}"
        key, _, value = line.partition(" = ")
        current[key] = value
    return sections


def test_receipt_exists_and_names_every_input():
    assert _RECEIPT.is_file(), (
        "the oracle has no provenance receipt; regenerate it with "
        "tools/thompson_wrf461_oracle/build.sh")
    receipt = _receipt()
    for section in ("wrf_source", "harness_source", "toolchain", "binaries",
                    "table_cache", "fixtures", "fixture_sha256"):
        assert section in receipt, f"receipt is missing [{section}]"

    wrf = receipt["wrf_source"]
    assert wrf["commit"] == "d66e442fccc04111067e29274c9f9eaccc3cef28"
    assert wrf["tag"] == "v4.6.1"
    # The commit alone does not prove the checkout, so the two files that
    # actually get compiled are hashed too.
    assert wrf["phys/module_mp_thompson.F"] == (
        "fabf19e2a9073cff886e882b187080bfdf089d3fd40c0fce1d19bc93b1e5e802")
    assert wrf["phys/module_mp_radar.F"] == (
        "aa99da858be41efa579966680708d230123a7417560af0eb2e24f4c94e253688")

    tool = receipt["toolchain"]
    for key in ("fortran", "libc", "uname", "opt_flags", "compile",
                "compile_thompson", "link", "libmvec_symbols"):
        assert tool.get(key), f"receipt does not record toolchain.{key}"


def test_optimisation_flags_keep_the_oracle_compiler_invariant():
    """-fno-tree-vectorize is the property, not a preference.

    With it the oracle links no libmvec SIMD math and four gfortran majors at
    three optimisation levels agree byte for byte.  Without it the answer
    depends on which loops the vectoriser happened to pick, which depends on
    unrelated source elsewhere in the same file.
    """
    tool = _receipt()["toolchain"]
    assert "-fno-tree-vectorize" in tool["opt_flags"], (
        "the oracle was built without -fno-tree-vectorize, so its numbers "
        "depend on GCC's vectoriser cost model rather than on WRF")
    assert tool["libmvec_symbols"] == "0", (
        "the oracle binary links glibc libmvec SIMD math, whose results are "
        "not bit-identical to scalar libm")
    build_sh = (_HARNESS / "build.sh").read_text(encoding="utf-8")
    assert "-fno-tree-vectorize" in build_sh


@pytest.mark.parametrize("name", _HARNESS_FILES)
def test_harness_source_still_matches_the_receipt(name):
    """The fixtures and the harness that made them must not drift apart.

    Ninety of the ninety-two committed fixtures once predated the harness
    source in the tree beside them.  This is the check that would have caught
    that on the commit that introduced it.
    """
    recorded = _receipt()["harness_source"]
    assert name in recorded, f"receipt does not record {name}"
    actual = _sha256(_HARNESS / name)
    assert actual == recorded[name], (
        f"{name} has changed since the fixtures were generated "
        f"(receipt {recorded[name][:16]}..., tree {actual[:16]}...).  "
        "Regenerate the oracle with tools/thompson_wrf461_oracle/build.sh and "
        "commit the new fixtures together with the new receipt; do not edit "
        "the receipt by hand.")


def test_every_fixture_matches_the_receipt():
    recorded = _receipt()["fixture_sha256"]
    present = sorted(p.name for p in _ORACLE.glob("*.csv"))
    assert sorted(recorded) == present, (
        "the fixture set and the receipt disagree about which files exist")
    for name in present:
        assert _sha256(_ORACLE / name) == recorded[name], \
            f"{name} does not hash to what the receipt recorded"


def test_fixture_set_rolls_up_to_the_recorded_digest():
    fixtures = _receipt()["fixtures"]
    names = sorted(p.name for p in _ORACLE.glob("*.csv"))
    assert int(fixtures["count"]) == len(names) == 92
    rollup = hashlib.sha256()
    for name in names:
        rollup.update((_ORACLE / name).read_bytes())
    assert rollup.hexdigest() == fixtures["rollup"]


def test_base_state_is_consistent_across_every_scenario():
    """`p_pa` and `pii` come from `z` alone, so they cannot vary by scenario.

    run_column.F90 builds them as `p0*exp(-z/8000)` and `(p/p0)**rd_over_cp`
    inside a loop that never looks at the scenario id.  Two fixtures that
    share a `dz` and disagree here did not come from the same binary, which
    means the set is a stratigraphy of builds rather than one oracle run.
    """
    groups: dict[tuple, list[str]] = collections.defaultdict(list)
    for path in sorted(_ORACLE.glob("*-column.csv")):
        with path.open(newline="", encoding="ascii") as stream:
            rows = list(csv.DictReader(stream))
        before = [r for r in rows if r["phase"] == "before"]
        key = (tuple(sorted({r["dz_m"] for r in rows})),
               tuple((r["z_m"], r["p_pa"], r["pii"]) for r in before))
        groups[key].append(path.name)

    by_dz: dict[tuple, list[tuple]] = collections.defaultdict(list)
    for key in groups:
        by_dz[key[0]].append(key)
    for dz, keys in by_dz.items():
        assert len(keys) == 1, (
            f"fixtures at dz={dz} disagree about the scenario-independent "
            "base state (p_pa/pii), so they were not produced by one build: "
            + " | ".join(
                "{" + ", ".join(sorted(groups[k])) + "}" for k in keys))
