"""Bind the registry generator to the registry file it is supposed to produce.

``woof/physics_registry_v2.json`` is generated by ``tools/build_registry.py``
and hand-edited by whoever corrects a claim.  Nothing forced the two to agree,
so they drifted: the builder wrote its citations from a search that counted a
docstring mention as a read, and replaying it reverted every citation the last
registry fix had just corrected.  The byte-for-byte test below is what makes
that drift impossible to land unnoticed.

The builder also used to write the registry at module scope, so ``import
tools.build_registry`` was enough to clobber a tracked file.  That is asserted
here too, in a subprocess, because an import inside this process would already
have happened before the assertion ran.

Scope, stated plainly: the builder transforms the registry rather than
generating it.  Its tables own the parameter declarations it lists, their
citations, the two nest override columns and two authority sentences; the
components, the templates and the other declarers' parameter rows have no
source in the builder and are carried through from the file.  So this is a
fixpoint gate over the region the builder owns -- perturb a byte there and the
tests below fail, perturb a byte outside it and they cannot see it.  That is
the region the drift happened in.

Every test writes only under ``tmp_path``.  The tracked registry's digest is
checked before and after each subprocess so a regression that reintroduces the
write is reported as a defect rather than silently applied to the tree.
"""

from __future__ import annotations

import hashlib
import os
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
REGISTRY_PATH = REPO_ROOT / "woof" / "physics_registry_v2.json"
BUILDER_PATH = REPO_ROOT / "tools" / "build_registry.py"

if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from tools.build_registry import (  # noqa: E402
    OWNED,
    _check_remedy_label_describes_its_edit,
    consuming_read_candidates,
    find_consuming_read,
    reads_knob,
    registry_setting_names,
)
from woof.physics_registry import physics_registry  # noqa: E402


def _digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _run(*arguments: str) -> subprocess.CompletedProcess[str]:
    """Run a Python command from the repo root and require it to succeed."""

    environment = dict(os.environ)
    environment["PYTHONPATH"] = str(REPO_ROOT)
    completed = subprocess.run(
        [sys.executable, *arguments],
        cwd=REPO_ROOT,
        env=environment,
        capture_output=True,
        text=True,
        timeout=600,
    )
    assert completed.returncode == 0, (
        f"{arguments} failed ({completed.returncode})\n"
        f"stdout:\n{completed.stdout}\nstderr:\n{completed.stderr}")
    return completed


def test_importing_the_builder_writes_nothing() -> None:
    before = _digest(REGISTRY_PATH)
    _run("-c", "import tools.build_registry")
    assert _digest(REGISTRY_PATH) == before, (
        "importing tools.build_registry rewrote the tracked registry; the "
        "write belongs to main(), not to module scope")


def test_the_builder_reproduces_the_tracked_registry_byte_for_byte(
    tmp_path: Path,
) -> None:
    """The generator and the generated file must not be able to disagree.

    Run into a temporary path -- never over the tracked file -- so a
    disagreement is reported instead of applied.
    """

    before = _digest(REGISTRY_PATH)
    generated = tmp_path / "physics_registry_v2.json"
    _run(str(BUILDER_PATH), "--out", str(generated))

    assert _digest(REGISTRY_PATH) == before, (
        "the builder wrote the tracked registry even though --out named "
        "another path")
    expected = REGISTRY_PATH.read_bytes()
    actual = generated.read_bytes()
    if actual != expected:
        first = next(
            (index for index, (left, right)
             in enumerate(zip(expected, actual)) if left != right),
            min(len(expected), len(actual)))
        pytest.fail(
            "tools/build_registry.py no longer reproduces "
            "woof/physics_registry_v2.json: they first differ at byte "
            f"{first} ({len(expected)} tracked bytes vs {len(actual)} "
            f"generated).\ntracked  ...{expected[first:first + 120]!r}\n"
            f"generated...{actual[first:first + 120]!r}\n"
            "Whichever is right, land the builder change and the registry "
            "change together.")


def test_the_builder_retires_the_old_moisture_cq_disabled_rows(tmp_path):
    """Rebuilding from an old seed must not bring the CQ guard back."""
    import json

    registry = json.loads(REGISTRY_PATH.read_text())
    registry["parameters"]["moist_cq"]["default"] = False
    for option in ("off", "kessler-mp1", "wsm6-mp6"):
        registry["components"]["microphysics"]["options"][option][
            "parameters"]["moist_cq"] = False
    seed = tmp_path / "old.json"
    seed.write_text(json.dumps(registry))
    generated = tmp_path / "physics_registry_v2.json"
    _run(str(BUILDER_PATH), "--registry", str(seed), "--out", str(generated))
    assert generated.read_bytes() == REGISTRY_PATH.read_bytes()


def test_the_builder_reproduces_the_consumer_export_byte_for_byte(
    tmp_path: Path,
) -> None:
    """The JSON the Rust crates read is generated beside the registry."""

    export_path = REPO_ROOT / "woof" / "physics_consumer_export_v1.json"
    before = _digest(export_path)
    generated = tmp_path / "physics_registry_v2.json"
    _run(str(BUILDER_PATH), "--out", str(generated))
    assert _digest(export_path) == before, (
        "the builder wrote the tracked consumer export even though --out "
        "named another directory")
    produced = tmp_path / "physics_consumer_export_v1.json"
    assert produced.read_bytes() == export_path.read_bytes(), (
        "tools/build_registry.py no longer reproduces "
        "woof/physics_consumer_export_v1.json; land the builder change and "
        "the export together")


def test_generated_map_projection_enum_matches_the_runtime_contract() -> None:
    """Registry consumers may select every projection the runtime accepts."""
    assert physics_registry()["parameters"]["map_proj"]["enum"] == [0, 1, 2, 3]


#: A declaration whose whole spec the builder's own table pins, so its default
#: is one byte the builder rewrites unconditionally.
_OWNED_ROW = b'"num_soil_layers":{'
_DEFAULT_KEY = b'"default":'


def _perturb_one_owned_byte(tracked: bytes) -> bytes:
    """Change the declared default of an owned row, one byte, nothing else."""

    row = tracked.index(_OWNED_ROW)
    index = tracked.index(_DEFAULT_KEY, row) + len(_DEFAULT_KEY)
    digit = tracked[index:index + 1]
    assert digit.isdigit(), (
        f"expected a single-digit default at byte {index}, found {digit!r}")
    return tracked[:index] + (b"4" if digit == b"5" else b"5") \
        + tracked[index + 1:]


def test_the_builder_corrects_a_single_changed_byte_it_owns(
    tmp_path: Path,
) -> None:
    """Negative control: the gate above must be able to fail.

    Feeding the builder a registry whose declared default was edited by one
    byte must produce the tracked bytes back, which is only true if the
    builder is the authority for that field.  It also shows the comparison is
    byte-exact: a check that re-serialised the JSON or compared parsed objects
    would have passed on the citation reversal this gate exists to catch.
    """

    before = _digest(REGISTRY_PATH)
    tracked = REGISTRY_PATH.read_bytes()
    perturbed = _perturb_one_owned_byte(tracked)
    assert len(perturbed) == len(tracked) and perturbed != tracked

    source = tmp_path / "perturbed.json"
    source.write_bytes(perturbed)
    generated = tmp_path / "physics_registry_v2.json"
    _run(str(BUILDER_PATH), "--registry", str(source), "--out", str(generated))

    assert _digest(REGISTRY_PATH) == before
    actual = generated.read_bytes()
    assert actual != perturbed, (
        "the builder carried a one-byte edit of a field it declares straight "
        "through, so the byte-identity gate cannot see drift in it")
    assert actual == tracked, (
        "the builder neither reproduced nor corrected the perturbed default")


@pytest.mark.parametrize("name", sorted(OWNED))
def test_every_citation_the_builder_owns_resolves(name: str) -> None:
    """A citation this builder claims must satisfy the shipped claim gate."""

    citation = physics_registry()["parameters"][name].get("consuming_read")
    assert isinstance(citation, str) and citation, (
        f"{name}: the builder claims this row, so it must cite a read")
    assert reads_knob(citation, name), (
        f"{name}: {citation} does not read it in executable code")


def test_a_docstring_only_mention_is_not_a_candidate() -> None:
    """The defect this builder shipped: prose counted as a read.

    ``woof/core/mynn_surface.py`` used to name both surface-layer knobs in
    its module docstring and nowhere else, which is why the registry stopped
    citing it.  A builder that still accepted it would repoint them back on
    the next run.

    ``isftcflx`` is no longer one of those two: the over-water branches are
    ported, so that file now reads it in executable code and is a legitimate
    candidate.  ``iz0tlnd`` is still land-only and still prose there, which is
    what keeps this regression test accurate -- it is asserting that the builder
    can tell prose from code, not that this particular file is inert.
    """

    prose_only = "woof/core/mynn_surface.py"
    assert (REPO_ROOT / prose_only).is_file()
    assert prose_only not in consuming_read_candidates("iz0tlnd")
    assert not reads_knob(prose_only, "iz0tlnd")
    assert find_consuming_read("iz0tlnd", prose_only) != prose_only
    # ...and the same file IS a candidate for the knob it now consumes, so a
    # builder that stopped distinguishing them fails here too.
    assert prose_only in consuming_read_candidates("isftcflx")
    assert reads_knob(prose_only, "isftcflx")


def test_the_configuration_module_can_be_cited() -> None:
    """``woof/config.py`` was excluded outright and had to be reachable.

    ``num_soil_layers`` is validated there and consumed nowhere else, so a
    search that could never name the file could never produce the registry's
    own citation.
    """

    candidates = consuming_read_candidates("num_soil_layers")
    assert "woof/config.py" in candidates
    assert find_consuming_read("num_soil_layers", "woof/config.py") == (
        "woof/config.py")


def test_an_executable_read_outranks_a_string_literal_mention() -> None:
    """A namelist table spells a knob without reading it.

    ``woof/core/ruc_contract.py`` carries ``num_soil_layers`` only as a dict
    key, pinned to the geometry its ORACLE was generated at.  (It used to be
    "the unported nine-layer geometry"; the forecast column runs at both of
    WRF's counts now, and it is the oracle assets that are nine-level only.)
    Prose stripping cannot remove it -- a string literal can be a real read --
    so the ranking has to place it below a file that reads the knob as an
    identifier.
    """

    candidates = consuming_read_candidates("num_soil_layers")
    string_only = "woof/core/ruc_contract.py"
    assert string_only in candidates
    assert candidates.index("woof/config.py") < candidates.index(string_only)


def test_a_verified_citation_survives_a_lower_ranked_competitor() -> None:
    """The search proposes; it does not overrule a citation that still holds.

    Several files read ``moist``, and only one is the component that acts on
    it.  That is a judgement made by reading code, so the builder keeps the
    citation already in the registry as long as it resolves.
    """

    tracked = physics_registry()["parameters"]["moist"]["consuming_read"]
    assert find_consuming_read("moist", tracked) == tracked
    assert find_consuming_read("moist", None) in consuming_read_candidates(
        "moist")


def test_a_citation_that_stopped_resolving_is_replaced() -> None:
    """A claim cannot outlive the read that justified it."""

    replacement = find_consuming_read("km_opt", "woof/core/kernels")
    assert replacement is not None
    assert replacement != "woof/core/kernels"
    assert reads_knob(replacement, "km_opt")


def test_gfs_noahmp_is_declared_expert_with_its_existing_discipline() -> None:
    registry = physics_registry()
    route = registry["runner_routes"]["tools.prepared_single_domain_forecast"]
    noahmp = "wsm6-ysu-mm5-noahmp-no-radiation-expert-only-v1"

    assert noahmp in route["expert_template_ids"]["gfs"]
    assert route["expert_acknowledgement_id"] == (
        "noahmp-host-column-throughput-v1")
    assert noahmp not in route["source_template_ids"]["gfs"]


def test_ratified_nssl2_legacy_profile_follows_every_base_route() -> None:
    registry = physics_registry()
    base = (
        "nssl2-mp18-ysu-mm5-noah-kf-rte-rrtmgp-"
        "validation-candidate-v1")
    legacy = (
        "nssl2-mp18-ysu-mm5-noah-kf-rrtmg-legacy-"
        "validation-candidate-v1")
    template = registry["templates"][legacy]

    assert template["maturity"] == "wrf-matched-run-candidate"
    assert template["parameters"]["wrf_rrtmg_compatibility"] == (
        "wrf-rrtmg-4-4-legacy-v1")
    assert template["parameters"]["ra_rrtmg_variant"] == "rrtmg_legacy"
    for route in registry["runner_routes"].values():
        for source, declared in route.get("source_template_ids", {}).items():
            assert (legacy in declared) == (base in declared), source


def test_ratified_kessler_template_is_declared_only_on_hrrr_routes() -> None:
    registry = physics_registry()
    template_id = "kessler-mp1-ysu-mm5-noah-dudhia-v1"
    assert registry["templates"][template_id]["components"][
        "microphysics"] == "kessler-mp1"
    for route_id, route in registry["runner_routes"].items():
        for source_id, declared in route.get(
                "source_template_ids", {}).items():
            assert (template_id in declared) == (
                source_id == "hrrr"
                and route_id in {
                    "tools.hrrr_single_domain_benchmark",
                    "tools.prepared_domain_tree_forecast",
                })


def test_a_remedy_label_names_exactly_the_edit_its_remedy_settings_makes(
) -> None:
    """A repair's title and a repair's edit are the same repair.

    ``remedy_label`` is printed as the title of an applicable repair --
    woof/companion_physics.py offers it above a button that applies
    ``remedy_settings``, and the desktop physics panel renders that title
    -- so a label naming a second way out the edit does not take says the
    button does something it does not.  The shipped label named both
    ra_rrtmg_variant and the Dudhia pair while the edit set only the
    variant; the alternative moved into the rule's reason, where it is
    read and not applied.

    Held over the whole tracked registry, so a rule any later pass writes
    is measured by the same property.
    """

    registry = physics_registry()
    # The vocabulary is the registry's whole setting namespace, not its
    # parameter table: ra_lw_physics is a component selector, and a check
    # written over parameters alone could not see the label it was
    # written for.
    parameters = registry_setting_names(registry)
    assert {"ra_lw_physics", "ra_rrtmg_variant"} <= parameters
    checked = 0
    for component in registry["components"].values():
        for option_id, option in component["options"].items():
            for rule in option.get("constraints", {}).get("refused_when", []):
                label = rule.get("remedy_label")
                settings = rule.get("remedy_settings")
                if not label or not settings:
                    continue
                checked += 1
                assert all(name in label for name in settings), (
                    option_id, label)
                named = {name for name in parameters if name in label}
                assert named <= set(settings), (option_id, label)
    # Coordinate TKE retains the metric operator's PBL-off refusal as
    # one conditional rule with a machine-applicable remedy, and the run
    # door's two diffusion-selector refusals are stated on the closures:
    # diff_opt=1 on the three that supply no coordinate coefficients
    # (km_opt 0, 1, 3) and mix_full_fields=false under diff_opt=2 on all
    # five.  Terrain admission adds one topo_wind and one gwd_opt remedy
    # on each of those five closures; their labels name only the selector
    # their edit sets to zero.  1 + 3 + 5 + 5 + 5.
    assert checked == 19


def test_the_builder_refuses_a_remedy_label_that_promises_a_second_edit(
) -> None:
    """The guard measures the defect, in both directions."""

    registry = physics_registry()
    rule = {
        "reason": "the pairing has no coupling.",
        "remedy_label": ("Set ra_rrtmg_variant='rrtmg_legacy', or select "
                         "the Dudhia pair ra_lw_physics=0 / "
                         "ra_sw_physics=1."),
        "remedy_settings": {"ra_rrtmg_variant": "rrtmg_legacy"},
    }
    with pytest.raises(RuntimeError, match="ra_lw_physics"):
        _check_remedy_label_describes_its_edit(rule, registry, "a-scheme")
    silent = dict(rule, remedy_label="Choose another radiation arm.")
    with pytest.raises(RuntimeError, match="ra_rrtmg_variant"):
        _check_remedy_label_describes_its_edit(silent, registry, "a-scheme")
    accurate = dict(rule, remedy_label="Set ra_rrtmg_variant='rrtmg_legacy'.")
    _check_remedy_label_describes_its_edit(accurate, registry, "a-scheme")
