"""Strict bytes generated by the original namelist-tolerance parent."""
from datetime import datetime
import hashlib
import json
from pathlib import Path

import pytest

from woof.domain_wizard import render_config
from woof.namelist_import import import_namelists


FIXTURES = Path(__file__).parent / "fixtures/tolerance_parent_byte_controls"
PARENT = "683cd2620e5e0abdd245d5365e29a060a1ba072a"
NAMELISTS = (
    "omitted_legacy_defaults", "explicit_vertical_order3",
    "ordinary_fixed60_triplet", "ruc_monthly_omitted", "ruc_monthly_false0",
)
SOURCES = ("gfs", "era5", "rap", "rrfs")
PROFILE = "thompson-mp8-ysu-mm5-noah-rte-rrtmgp-v1"


def _controls(group, matrix_name):
    payload = (FIXTURES / matrix_name).read_bytes()
    pins = json.loads((FIXTURES / group / "historical-pins.json").read_bytes())
    assert pins["mode"] == "baseline"
    assert pins["audit_parent"] == PARENT
    assert hashlib.sha256(payload).hexdigest() == pins["matrix_sha256"]
    return json.loads(payload), pins


def _assert_old_bytes(group, pins, key, emitted):
    row = pins["cases"][key]
    relative = Path(row["file"])
    assert len(relative.parts) == 1 and relative.suffix == ".toml"
    old = (FIXTURES / group / relative).read_bytes()
    assert len(old) == row["bytes"]
    assert hashlib.sha256(old).hexdigest() == row["sha256"]
    assert emitted.encode("utf-8") == old


@pytest.mark.parametrize("case", NAMELISTS)
def test_ordinary_namelist_bytes_match_tolerance_original_parent(case, tmp_path):
    matrix, pins = _controls("original-nine", "original-matrix.json")
    documents = matrix["namelists"][case]
    wps, inp = tmp_path / "namelist.wps", tmp_path / "namelist.input"
    wps.write_bytes(documents["wps"].encode("utf-8"))
    inp.write_bytes(documents["input"].encode("utf-8"))
    emitted, _ = import_namelists(wps, inp)
    _assert_old_bytes("original-nine", pins, "namelist/" + case, emitted)


@pytest.mark.parametrize("source", SOURCES)
def test_ordinary_ysu_noah_recipe_bytes_match_tolerance_original_parent(source):
    matrix, pins = _controls("stable-recipes", "stable-recipes-matrix.json")
    recipe = matrix["recipes"]
    assert recipe["profile"] == PROFILE
    assert tuple(recipe["sources"]) == SOURCES
    emitted = render_config(
        name=recipe["name"], start_time=datetime.fromisoformat(recipe["start_time"]),
        hours=recipe["hours"], projection=recipe["projection"],
        dims=[tuple(row) for row in recipe["dims"]], ratios=tuple(recipe["ratios"]),
        root_dx_m=recipe["root_dx_m"], fetch_hints={"source": source},
        case_data=None, profile=recipe["profile"],
    )
    _assert_old_bytes("stable-recipes", pins, "recipe/" + source, emitted)
