# tests/test_diff6_boundary_face.py
"""Sixth-order diffusion: the WRF-computed high-side staggered faces.

Oracle: WRF v4.6.1 (reference bundle) ``sixth_order_diffusion``,
dyn_em/module_big_step_utilities_em.F --
  bounds    :6332-6444: for ``specified .or. nested`` (:6333-6334) the
            loops are, 1-based with mass cells ids..ide-1:
              'u'   i = ids+3..ide-3, j = jds+3..jde-4   (:6354-6359)
              'v'   i = ids+3..ide-4, j = jds+3..jde-3   (:6381-6386)
              'w'   i = ids+3..ide-4, j = jds+3..jde-4, k = kts+1..ktf
                                                         (:6408-6415)
              mass  i = ids+3..ide-4, j = jds+3..jde-4   (:6435-6440)
  arithmetic :6461-6624: Xue eq. 3 face fluxes, the diff_6th_opt=2
            up-gradient zeroing, the diff_6th_slopeopt taper, and the
            variant-specific hybrid face-mass averages, with
            coef = diff_6th_factor*0.015625/(2*dt) (:6321).

0-based mapping (woof ``nx = e_we - 1`` mass points, so ids=1 -> 0 and
ide = nx+1; ditto j/ny):
  u faces computed:  i in [3, nx-3], j in [3, ny-4]
  v faces computed:  j in [3, ny-3], i in [3, nx-4]
  w/mass computed:   i in [3, nx-4], j in [3, ny-4]

The single WRF read outside each staggered axis' periodic core happens at
the outermost computed face: u's ``dflux_x_p1`` at i = nx-3 reads
``field(i+3)`` = the stored true east-boundary datum u[..., nx] (WRF
:6465-6467 reading field(ide)), and v's ``dflux_y_p1`` at j = ny-3 reads
v[..., ny, :] (WRF :6547-6549 reading field(jde)).  woof at 4d2ce99
instead zeroed those two face sets (``_zero_open_strips`` width 3 with
``stag_high_extra=1``; kernel header note), because the periodic-wrap
stencil would have corrupted the read with the OPPOSITE boundary's value.
The dropped WRF-computed sets are exactly

  u:  (k, j in [3, ny-4], i = nx-3)      east high-side staggered face
  v:  (k, j = ny-3, i in [3, nx-4])      north high-side staggered face

and nothing else (all other sides/staggers already match WRF's width-3
exclusion, pinned below).

These pins were written RED against 4d2ce99 (the mirror and both
application paths zeroed the two face sets where the WRF-loop oracle is
nonzero) and must stay green forever after.  The base-behavior capture
``tests/data/diff6_base_4d2ce99.npz`` was generated by THIS file's
``--generate`` entry point running the UNMODIFIED 4d2ce99 kernel (dual
run, elementwise-identical), and pins that the fix leaves every face
other than the two seam sets bit-identical, and periodic behavior
bit-identical everywhere.
"""
import os
import sys

import numpy as np
import pytest

from conftest import requires_gpu

FACTOR = 0.12
DT = 2.0
NZ, NY, NX = 6, 12, 14
_DATA = os.path.join(os.path.dirname(__file__), "data",
                     "diff6_base_4d2ce99.npz")

# ---------------------------------------------------------------------------
# WRF-loop oracle: literal float64 transcription of sixth_order_diffusion
# ---------------------------------------------------------------------------


def _wrf_bounds(name, ny, nx, nlev):
    """0-based inclusive loop bounds for specified .or. nested domains.

    WRF module_big_step_utilities_em.F:6332-6444 (see module docstring for
    the 1-based originals and the ids=1/ide=nx+1 mapping)."""
    if name == "u":
        return (3, nx - 3), (3, ny - 4), (0, nlev - 1)
    if name == "v":
        return (3, nx - 4), (3, ny - 3), (0, nlev - 1)
    if name == "w":
        return (3, nx - 4), (3, ny - 4), (1, nlev - 2)
    return (3, nx - 4), (3, ny - 4), (0, nlev - 1)


def wrf_sixth_order_diffusion(field, mut, c1, c2, factor, dt, opt, name,
                              phb=None, msfu=None, msfv=None, slopeopt=0,
                              thresh=0.10, dx=0.0, dy=0.0,
                              mapx=None, mapy=None):
    """WRF v4.6.1 ``sixth_order_diffusion`` for a specified/nested domain.

    Independent float64 loop transcription (bounds :6332-6444, x fluxes
    :6461-6533, y fluxes :6543-6616, combine :6624), 0-based storage, NO
    periodic wrap anywhere: every stencil read is the stored datum, which
    inside the WRF bounds is always in range -- including the accurate
    boundary reads u[..., nx] / v[..., ny, :] at the outermost computed
    staggered faces.  ``mapx``/``mapy`` are the per-direction TENDENCY
    map factors (WRF msfux/msfuy for u, msfvx/msfvy for v, msftx/msfty
    for mass; field-shaped 2-D); they default to 1, the woof kernel's
    documented specialization.  ``msfu``/``msfv`` enter only the slopeopt
    dzmax scaling exactly as the Fortran's msfux/msfvy.  Returns the
    coupled tendency, zero outside the WRF loop bounds.

    Cross-checked against the blind independent derivation
    the diff6 cross-oracle record (2026-07-27): same bounds
    tables (its section 2), same flux-form/per-face-limiter/mass-average
    associations (its section 1), and digit-level agreement with its
    FP32 oracle's worked example (tests below).
    """
    f = np.asarray(field, dtype=np.float64)
    mut = np.asarray(mut, dtype=np.float64)
    c1 = np.asarray(c1, dtype=np.float64)
    c2 = np.asarray(c2, dtype=np.float64)
    nlev = f.shape[0]
    ny, nx = mut.shape
    assert nx >= 8 and ny >= 8, "domain too small for the WRF bounds"
    coef = factor * 0.015625 / (2.0 * dt)          # :6321
    slope = slopeopt >= 1 and phb is not None and np.ndim(phb) == 3
    if slope:
        ph = np.asarray(phb, dtype=np.float64)
        mfu = (np.ones((ny, nx + 1)) if msfu is None
               else np.asarray(msfu, dtype=np.float64))
        mfv = (np.ones((ny + 1, nx)) if msfv is None
               else np.asarray(msfv, dtype=np.float64))
        dzthr_x = thresh * 9.81 * dx               # :6489
        dzthr_y = thresh * 9.81 * dy               # :6571
    mapx = np.ones(f.shape[1:]) if mapx is None else np.asarray(
        mapx, dtype=np.float64)
    mapy = np.ones(f.shape[1:]) if mapy is None else np.asarray(
        mapy, dtype=np.float64)
    out = np.zeros_like(f)
    (i0, i1), (j0, j1), (k0, k1) = _wrf_bounds(name, ny, nx, nlev)

    def mu_avg(k, jj, ii):                         # c1(k)*MUT(i,j)+c2(k)
        return c1[k] * mut[jj, ii] + c2[k]

    for j in range(j0, j1 + 1):
        for k in range(k0, k1 + 1):
            for i in range(i0, i1 + 1):
                # ---- diffusion in x (:6461-6533) ----
                dflux_x_p0 = (10.0 * (f[k, j, i] - f[k, j, i - 1])
                              - 5.0 * (f[k, j, i + 1] - f[k, j, i - 2])
                              + (f[k, j, i + 2] - f[k, j, i - 3]))
                dflux_x_p1 = (10.0 * (f[k, j, i + 1] - f[k, j, i])
                              - 5.0 * (f[k, j, i + 2] - f[k, j, i - 1])
                              + (f[k, j, i + 3] - f[k, j, i - 2]))
                if opt == 2:                       # :6472-6482
                    if dflux_x_p0 * (f[k, j, i] - f[k, j, i - 1]) <= 0.0:
                        dflux_x_p0 = 0.0
                    if dflux_x_p1 * (f[k, j, i + 1] - f[k, j, i]) <= 0.0:
                        dflux_x_p1 = 0.0
                sdx_p0 = sdx_p1 = 1.0
                if slope:                          # :6487-6502
                    if name == "u":
                        dz0 = max(abs(ph[k, j, i] - ph[k, j, i - 1])
                                  * mfu[j, i],
                                  abs(ph[k, j, i - 1] - ph[k, j, i - 2])
                                  * mfu[j, i - 1])
                        dz1 = max(abs(ph[k, j, i + 1] - ph[k, j, i])
                                  * mfu[j, i + 1],
                                  abs(ph[k, j, i] - ph[k, j, i - 1])
                                  * mfu[j, i])
                    elif name == "v":
                        dz0 = max(abs(ph[k, j, i] - ph[k, j, i - 1])
                                  * mfu[j, i],
                                  abs(ph[k, j - 1, i] - ph[k, j - 1, i - 1])
                                  * mfu[j - 1, i])
                        dz1 = max(abs(ph[k, j, i + 1] - ph[k, j, i])
                                  * mfu[j, i + 1],
                                  abs(ph[k, j - 1, i + 1] - ph[k, j - 1, i])
                                  * mfu[j - 1, i + 1])
                    else:
                        dz0 = abs(ph[k, j, i] - ph[k, j, i - 1]) * mfu[j, i]
                        dz1 = (abs(ph[k, j, i + 1] - ph[k, j, i])
                               * mfu[j, i + 1])
                    sdx_p0 = max(1.0 - dz0 / dzthr_x, 0.0)
                    sdx_p1 = max(1.0 - dz1 / dzthr_x, 0.0)
                if name == "u":                    # :6506-6510
                    mu_p0 = mu_avg(k, j, i - 1)
                    mu_p1 = mu_avg(k, j, i)
                elif name == "v":                  # :6511-6523
                    mu_p0 = 0.25 * (mu_avg(k, j - 1, i - 1)
                                    + mu_avg(k, j - 1, i)
                                    + mu_avg(k, j, i - 1)
                                    + mu_avg(k, j, i))
                    mu_p1 = 0.25 * (mu_avg(k, j - 1, i)
                                    + mu_avg(k, j - 1, i + 1)
                                    + mu_avg(k, j, i)
                                    + mu_avg(k, j, i + 1))
                else:                              # :6524-6532
                    mu_p0 = 0.5 * (mu_avg(k, j, i - 1) + mu_avg(k, j, i))
                    mu_p1 = 0.5 * (mu_avg(k, j, i) + mu_avg(k, j, i + 1))
                tendency_x = (coef * mapx[j, i]
                              * (sdx_p1 * mu_p1 * dflux_x_p1
                                 - sdx_p0 * mu_p0 * dflux_x_p0))

                # ---- diffusion in y (:6543-6616) ----
                dflux_y_p0 = (10.0 * (f[k, j, i] - f[k, j - 1, i])
                              - 5.0 * (f[k, j + 1, i] - f[k, j - 2, i])
                              + (f[k, j + 2, i] - f[k, j - 3, i]))
                dflux_y_p1 = (10.0 * (f[k, j + 1, i] - f[k, j, i])
                              - 5.0 * (f[k, j + 2, i] - f[k, j - 1, i])
                              + (f[k, j + 3, i] - f[k, j - 2, i]))
                if opt == 2:                       # :6554-6564
                    if dflux_y_p0 * (f[k, j, i] - f[k, j - 1, i]) <= 0.0:
                        dflux_y_p0 = 0.0
                    if dflux_y_p1 * (f[k, j + 1, i] - f[k, j, i]) <= 0.0:
                        dflux_y_p1 = 0.0
                sdy_p0 = sdy_p1 = 1.0
                if slope:                          # :6569-6584
                    if name == "u":
                        dz0 = max(abs(ph[k, j, i] - ph[k, j - 1, i])
                                  * mfv[j, i],
                                  abs(ph[k, j, i - 1] - ph[k, j - 1, i - 1])
                                  * mfv[j, i - 1])
                        dz1 = max(abs(ph[k, j + 1, i] - ph[k, j, i])
                                  * mfv[j + 1, i],
                                  abs(ph[k, j + 1, i - 1] - ph[k, j, i - 1])
                                  * mfv[j + 1, i - 1])
                    elif name == "v":
                        dz0 = max(abs(ph[k, j, i] - ph[k, j - 1, i])
                                  * mfv[j, i],
                                  abs(ph[k, j - 1, i] - ph[k, j - 2, i])
                                  * mfv[j - 1, i])
                        dz1 = max(abs(ph[k, j + 1, i] - ph[k, j, i])
                                  * mfv[j + 1, i],
                                  abs(ph[k, j, i] - ph[k, j - 1, i])
                                  * mfv[j, i])
                    else:
                        dz0 = abs(ph[k, j, i] - ph[k, j - 1, i]) * mfv[j, i]
                        dz1 = (abs(ph[k, j + 1, i] - ph[k, j, i])
                               * mfv[j + 1, i])
                    sdy_p0 = max(1.0 - dz0 / dzthr_y, 0.0)
                    sdy_p1 = max(1.0 - dz1 / dzthr_y, 0.0)
                if name == "u":                    # :6588-6600
                    mu_p0 = 0.25 * (mu_avg(k, j - 1, i - 1)
                                    + mu_avg(k, j - 1, i)
                                    + mu_avg(k, j, i - 1)
                                    + mu_avg(k, j, i))
                    mu_p1 = 0.25 * (mu_avg(k, j, i - 1)
                                    + mu_avg(k, j, i)
                                    + mu_avg(k, j + 1, i - 1)
                                    + mu_avg(k, j + 1, i))
                elif name == "v":                  # :6602-6606
                    mu_p0 = mu_avg(k, j - 1, i)
                    mu_p1 = mu_avg(k, j, i)
                else:                              # :6607-6615
                    mu_p0 = 0.5 * (mu_avg(k, j - 1, i) + mu_avg(k, j, i))
                    mu_p1 = 0.5 * (mu_avg(k, j, i) + mu_avg(k, j + 1, i))
                tendency_y = (coef * mapy[j, i]
                              * (sdy_p1 * mu_p1 * dflux_y_p1
                                 - sdy_p0 * mu_p0 * dflux_y_p0))

                out[k, j, i] = tendency_x + tendency_y     # :6624
    return out


# ---------------------------------------------------------------------------
# fixtures
# ---------------------------------------------------------------------------

_STAG_NAME = {"": "m", "x": "u", "y": "v", "z": "w"}


def _forced_case(stagger, nz=NZ, ny=NY, nx=NX, seed=17):
    """Random fp32 field with INDEPENDENT boundary-face data.

    Unlike the periodic fixtures, the last staggered column/row is NOT a
    duplicate of column/row 0: on a specified/nested domain it is the
    boundary-installed datum WRF's outermost computed face reads, and the
    pins are vacuous unless it differs from the opposite boundary.
    """
    rng = np.random.default_rng(seed)
    nlev = nz + 1 if stagger == "z" else nz
    shape = {"": (nlev, ny, nx), "z": (nlev, ny, nx),
             "x": (nlev, ny, nx + 1), "y": (nlev, ny + 1, nx)}[stagger]
    f = rng.standard_normal(shape).astype(np.float32)
    mut = (1.0 + 0.5 * rng.random((ny, nx))).astype(np.float32)
    c1 = (0.5 + 0.5 * rng.random(nlev)).astype(np.float32)
    c2 = (0.5 * rng.random(nlev)).astype(np.float32)
    return f, mut, c1, c2


def _slope_inputs(nz=NZ, ny=NY, nx=NX, seed=23):
    """Terrain-like phb + non-identity staggered msf, taper-straddling."""
    rng = np.random.default_rng(seed)
    z = (60.0 * np.cumsum(rng.random((ny, nx)), axis=1)
         + 40.0 * np.cumsum(rng.random((ny, nx)), axis=0))
    phb = (9.81 * (z[None] + 200.0 * np.arange(nz + 2)[:, None, None])
           ).astype(np.float32)[:nz + 1]
    msfu = (1.0 + 0.1 * rng.random((ny, nx + 1))).astype(np.float32)
    msfv = (1.0 + 0.1 * rng.random((ny + 1, nx))).astype(np.float32)
    return phb, msfu, msfv


def _seam_mask(stagger, shape):
    """Boolean mask of the two newly-computed WRF face sets (else False)."""
    m = np.zeros(shape, dtype=bool)
    nlev, nys, nxs = shape
    if stagger == "x":
        m[:, 3:nys - 3, nxs - 4] = True     # u: j in [3, ny-4], i = nx-3
    if stagger == "y":
        m[:, nys - 4, 3:nxs - 3] = True     # v: j = ny-3, i in [3, nx-4]
    return m


def _forced_cfg(**flags):
    from woof.config import RunConfig
    return RunConfig(nx=NX, ny=NY, nz=NZ, dx=1.0, dy=1.0, ztop=1.0, dt=DT,
                     run_seconds=0.0, diff_6th_opt=2, diff_6th_factor=FACTOR,
                     **flags)


def _production_masked_tend(f, mut, c1, c2, opt, stagger, cfg, **slope_kw):
    """launch_diff6 + _zero_open_strips exactly as prepare_fixed_tendencies
    / apply_diff6 drive them (boundary-aware kernel + WRF width-3 mask)."""
    import cupy as cp

    from woof.core.dycore import (_boundary_x, _boundary_y,
                                   _zero_open_strips, launch_diff6)
    fd = cp.asarray(f, dtype=cp.float32)
    tend = cp.zeros_like(fd)
    launch_diff6(fd, tend, cp.asarray(mut, cp.float32),
                 cp.asarray(c1, cp.float32), cp.asarray(c2, cp.float32),
                 FACTOR, DT, opt, stagger=stagger,
                 bnd_x=_boundary_x(cfg), bnd_y=_boundary_y(cfg), **slope_kw)
    _zero_open_strips(tend, cfg, 3)
    return cp.asnumpy(tend)


# ---------------------------------------------------------------------------
# oracle geometry (CPU)
# ---------------------------------------------------------------------------

def test_oracle_support_is_exactly_the_wrf_bounds():
    """The oracle's nonzero support equals WRF's specified-domain loop set
    for every stagger, and the u/v supports INCLUDE the seam faces."""
    for stagger in ("", "x", "y", "z"):
        f, mut, c1, c2 = _forced_case(stagger)
        name = _STAG_NAME[stagger]
        out = wrf_sixth_order_diffusion(f, mut, c1, c2, FACTOR, DT, 1, name)
        nlev = f.shape[0]
        (i0, i1), (j0, j1), (k0, k1) = _wrf_bounds(name, NY, NX, nlev)
        inside = np.zeros(f.shape, dtype=bool)
        inside[k0:k1 + 1, j0:j1 + 1, i0:i1 + 1] = True
        assert (out[~inside] == 0.0).all(), stagger
        # opt=1 (no monotonic zeroing) on continuous noise: every computed
        # entry is nonzero, so the support is the full WRF loop set.
        assert (out[inside] != 0.0).all(), stagger
        seam = _seam_mask(stagger, f.shape)
        if stagger in ("x", "y"):
            assert seam.sum() == (nlev * (NY - 6) if stagger == "x"
                                  else nlev * (NX - 6))
            assert inside[seam].all(), stagger
            assert np.abs(out[seam]).min() > 0.0, stagger


def test_oracle_seam_face_reads_the_true_boundary_datum():
    """Perturbing ONLY the stored boundary face (u[..., nx] / v[:, ny, :])
    changes the oracle exactly on the seam set -- the WRF read woof's
    wrapped stencil could not make -- and nowhere else."""
    for stagger in ("x", "y"):
        f, mut, c1, c2 = _forced_case(stagger)
        name = _STAG_NAME[stagger]
        base = wrf_sixth_order_diffusion(f, mut, c1, c2, FACTOR, DT, 1, name)
        g = f.copy()
        if stagger == "x":
            g[:, :, -1] += 1.5
        else:
            g[:, -1, :] += 1.5
        pert = wrf_sixth_order_diffusion(g, mut, c1, c2, FACTOR, DT, 1, name)
        diff = pert - base
        seam = _seam_mask(stagger, f.shape)
        assert np.abs(diff[seam]).min() > 0.0, stagger
        assert (diff[~seam] == 0.0).all(), stagger


# ---------------------------------------------------------------------------
# mirror pins (CPU) -- RED at 4d2ce99
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("opt", [1, 2])
@pytest.mark.parametrize("stagger", ["", "x", "y", "z"])
def test_mirror_matches_wrf_loop_oracle_on_forced_bounds(stagger, opt):
    """np_diff6 with open_x/open_y (the mask np_diff6 shares between open
    and specified/nested forcing) must reproduce the WRF-loop oracle
    everywhere -- including the u east / v north seam faces the 4d2ce99
    mirror zeroed."""
    from woof.verify.npref import np_diff6
    f, mut, c1, c2 = _forced_case(stagger)
    name = _STAG_NAME[stagger]
    want = wrf_sixth_order_diffusion(f, mut, c1, c2, FACTOR, DT, opt, name)
    got = np_diff6(f.astype(np.float64), mut, c1, c2, FACTOR, DT, opt,
                   stagger=stagger, open_x=True, open_y=True)
    np.testing.assert_allclose(got, want, rtol=1e-12, atol=0.0,
                               err_msg=f"{stagger}/{opt}")
    seam = _seam_mask(stagger, f.shape)
    if stagger in ("x", "y") and opt == 1:
        assert np.abs(want[seam]).min() > 0.0     # non-vacuous


@pytest.mark.parametrize("stagger", ["", "x", "y", "z"])
def test_mirror_matches_wrf_loop_oracle_with_slope_taper(stagger):
    """Same equivalence with the diff_6th_slopeopt taper engaged (3-D phb,
    non-identity msf), covering the taper arithmetic at the seam faces."""
    from woof.verify.npref import np_diff6
    f, mut, c1, c2 = _forced_case(stagger, seed=31)
    name = _STAG_NAME[stagger]
    phb, msfu, msfv = _slope_inputs()
    dx = dy = 500.0
    want = wrf_sixth_order_diffusion(f, mut, c1, c2, FACTOR, DT, 2, name,
                                     phb=phb, msfu=msfu, msfv=msfv,
                                     slopeopt=1, thresh=0.10, dx=dx, dy=dy)
    got = np_diff6(f.astype(np.float64), mut, c1, c2, FACTOR, DT, 2,
                   stagger=stagger, open_x=True, open_y=True, phb=phb,
                   msfu=msfu, msfv=msfv, slopeopt=1, thresh=0.10,
                   dx=dx, dy=dy)
    np.testing.assert_allclose(got, want, rtol=1e-12, atol=0.0,
                               err_msg=stagger)
    if stagger in ("x", "y"):
        seam = _seam_mask(stagger, f.shape)
        assert np.abs(want[seam]).max() > 0.0     # non-vacuous under taper


# ---------------------------------------------------------------------------
# independent FP32 authority (CPU): blind source-only derivation
# the diff6 cross-oracle record (2026-07-27) section 3,
# transcribed verbatim (per-operation FP32 rounding in WRF's source
# association), plus its deterministic 8x8 worked example whose printed
# expected values are pinned digit-for-digit below.
# ---------------------------------------------------------------------------

_F = np.float32
_XO_Z, _XO_O, _XO_H, _XO_Q = _F(0.0), _F(1.0), _F(0.5), _F(0.25)
_XO_TWO, _XO_FIVE, _XO_TEN = _F(2.0), _F(5.0), _F(10.0)
_XO_1_64 = _F(0.015625)


def _xo_add(a, b):
    return _F(_F(a) + _F(b))


def _xo_sub(a, b):
    return _F(_F(a) - _F(b))


def _xo_mul(a, b):
    return _F(_F(a) * _F(b))


def _xo_div(a, b):
    return _F(_F(a) / _F(b))


def _xo_mass_at(mut, j, i, c1, c2):
    return _xo_add(_xo_mul(c1, mut[j, i]), c2)


def _xo_avg2(a, b):
    return _xo_mul(_XO_H, _xo_add(a, b))


def _xo_avg4(a, b, c, d):
    # Source-ordered (((a+b)+c)+d), then multiply by 0.25.
    return _xo_mul(_XO_Q, _xo_add(_xo_add(_xo_add(a, b), c), d))


def _xo_flux_x(a, j, i, shift):
    d0 = _xo_sub(a[j, i + shift], a[j, i - 1 + shift])
    q0 = _xo_mul(_XO_TEN, d0)
    d1 = _xo_sub(a[j, i + 1 + shift], a[j, i - 2 + shift])
    q1 = _xo_mul(_XO_FIVE, d1)
    q2 = _xo_sub(q0, q1)
    d2 = _xo_sub(a[j, i + 2 + shift], a[j, i - 3 + shift])
    return _xo_add(q2, d2)


def _xo_flux_y(a, j, i, shift):
    d0 = _xo_sub(a[j + shift, i], a[j - 1 + shift, i])
    q0 = _xo_mul(_XO_TEN, d0)
    d1 = _xo_sub(a[j + 1 + shift, i], a[j - 2 + shift, i])
    q1 = _xo_mul(_XO_FIVE, d1)
    q2 = _xo_sub(q0, q1)
    d2 = _xo_sub(a[j + 2 + shift, i], a[j - 3 + shift, i])
    return _xo_add(q2, d2)


def _xo_limited(flux, first_difference):
    product = _xo_mul(flux, first_difference)
    return _XO_Z if product <= _XO_Z else _F(flux)


def _xo_bounds(kind, nx, ny):
    if kind == "u":
        return 3, nx - 3, 3, ny - 4
    if kind == "v":
        return 3, nx - 4, 3, ny - 3
    if kind in ("m", "w"):
        return 3, nx - 4, 3, ny - 4
    raise ValueError("kind must be 'u', 'v', 'm', or 'w'")


def xoracle_diff6_slice(field, kind, nx, ny, mut, mapx, mapy,
                        dt, factor, c1, c2, tendency=None):
    """One horizontal k slice, per-op FP32 (the handoff report's oracle)."""
    a = np.asarray(field, dtype=np.float32)
    mut = np.asarray(mut, dtype=np.float32)
    mapx = np.asarray(mapx, dtype=np.float32)
    mapy = np.asarray(mapy, dtype=np.float32)
    if tendency is None:
        out = np.zeros_like(a, dtype=np.float32)
    else:
        out = np.asarray(tendency, dtype=np.float32).copy()
    tx = np.zeros_like(a, dtype=np.float32)
    ty = np.zeros_like(a, dtype=np.float32)
    coef = _xo_div(_xo_mul(_F(factor), _XO_1_64), _xo_mul(_XO_TWO, _F(dt)))
    ilo, ihi, jlo, jhi = _xo_bounds(kind, nx, ny)
    for j in range(jlo, jhi + 1):
        for i in range(ilo, ihi + 1):
            fx0 = _xo_flux_x(a, j, i, 0)
            fx1 = _xo_flux_x(a, j, i, 1)
            fx0 = _xo_limited(fx0, _xo_sub(a[j, i], a[j, i - 1]))
            fx1 = _xo_limited(fx1, _xo_sub(a[j, i + 1], a[j, i]))
            if kind == "u":
                mx0 = _xo_mass_at(mut, j, i - 1, c1, c2)
                mx1 = _xo_mass_at(mut, j, i, c1, c2)
            elif kind == "v":
                mx0 = _xo_avg4(_xo_mass_at(mut, j - 1, i - 1, c1, c2),
                               _xo_mass_at(mut, j - 1, i, c1, c2),
                               _xo_mass_at(mut, j, i - 1, c1, c2),
                               _xo_mass_at(mut, j, i, c1, c2))
                mx1 = _xo_avg4(_xo_mass_at(mut, j - 1, i, c1, c2),
                               _xo_mass_at(mut, j - 1, i + 1, c1, c2),
                               _xo_mass_at(mut, j, i, c1, c2),
                               _xo_mass_at(mut, j, i + 1, c1, c2))
            else:
                mx0 = _xo_avg2(_xo_mass_at(mut, j, i - 1, c1, c2),
                               _xo_mass_at(mut, j, i, c1, c2))
                mx1 = _xo_avg2(_xo_mass_at(mut, j, i, c1, c2),
                               _xo_mass_at(mut, j, i + 1, c1, c2))
            xp1 = _xo_mul(_xo_mul(_XO_O, mx1), fx1)
            xp0 = _xo_mul(_xo_mul(_XO_O, mx0), fx0)
            tx[j, i] = _xo_mul(_xo_mul(coef, mapx[j, i]),
                               _xo_sub(xp1, xp0))
            fy0 = _xo_flux_y(a, j, i, 0)
            fy1 = _xo_flux_y(a, j, i, 1)
            fy0 = _xo_limited(fy0, _xo_sub(a[j, i], a[j - 1, i]))
            fy1 = _xo_limited(fy1, _xo_sub(a[j + 1, i], a[j, i]))
            if kind == "u":
                my0 = _xo_avg4(_xo_mass_at(mut, j - 1, i - 1, c1, c2),
                               _xo_mass_at(mut, j - 1, i, c1, c2),
                               _xo_mass_at(mut, j, i - 1, c1, c2),
                               _xo_mass_at(mut, j, i, c1, c2))
                my1 = _xo_avg4(_xo_mass_at(mut, j, i - 1, c1, c2),
                               _xo_mass_at(mut, j, i, c1, c2),
                               _xo_mass_at(mut, j + 1, i - 1, c1, c2),
                               _xo_mass_at(mut, j + 1, i, c1, c2))
            elif kind == "v":
                my0 = _xo_mass_at(mut, j - 1, i, c1, c2)
                my1 = _xo_mass_at(mut, j, i, c1, c2)
            else:
                my0 = _xo_avg2(_xo_mass_at(mut, j - 1, i, c1, c2),
                               _xo_mass_at(mut, j, i, c1, c2))
                my1 = _xo_avg2(_xo_mass_at(mut, j, i, c1, c2),
                               _xo_mass_at(mut, j + 1, i, c1, c2))
            yp1 = _xo_mul(_xo_mul(_XO_O, my1), fy1)
            yp0 = _xo_mul(_xo_mul(_XO_O, my0), fy0)
            ty[j, i] = _xo_mul(_xo_mul(coef, mapy[j, i]),
                               _xo_sub(yp1, yp0))
            out[j, i] = _xo_add(_xo_add(out[j, i], tx[j, i]), ty[j, i])
    return out, tx, ty, coef


def _xo_pattern(nj, ni, seed):
    j, i = np.indices((nj, ni), dtype=np.int32)
    raw = ((17 * i + 31 * j + 7 * i * j + seed) % 29) - 14
    checker = ((i + j) & 1).astype(np.float32)
    return (raw.astype(np.float32) * _F(0.25)
            + checker * _F(0.125)).astype(np.float32)


def _xo_example():
    """The report's deterministic 8x8 worked-example fixtures."""
    nx = ny = 8
    jm, im = np.indices((ny, nx), dtype=np.int32)
    mut = (_F(1.0) + _F(0.01) * (_F(3.0) * im.astype(np.float32)
                                 + _F(5.0) * jm.astype(np.float32))
           ).astype(np.float32)
    cases = []
    for kind, shape, seed, points in [
            ("u", (ny, nx + 1), 3, [(3, 3), (3, 5), (4, 5), (4, 6)]),
            ("v", (ny + 1, nx), 5, [(3, 3), (5, 3), (5, 4), (6, 4)]),
            ("m", (ny, nx), 7, [(3, 3), (4, 4), (4, 5), (5, 4)])]:
        field = _xo_pattern(*shape, seed)
        j, i = np.indices(shape, dtype=np.int32)
        mapx = (_F(0.90) + _F(0.002) * i.astype(np.float32)
                + _F(0.003) * j.astype(np.float32)).astype(np.float32)
        mapy = (_F(1.10) + _F(0.004) * i.astype(np.float32)
                - _F(0.001) * j.astype(np.float32)).astype(np.float32)
        cases.append((kind, field, mapx, mapy, points))
    return nx, ny, mut, cases


#: The report's printed expected values (section 3), pinned verbatim.
_XO_EXPECTED = {
    "coef": "0.0001562499965",
    "u": [" 0.0116453776", "-0.00561431237", " 0.00603106525",
          "-0.0108378809", "-0.0147318328", "-0.0255697146",
          " 0.0204591788", " 0.0150952954", " 0.0355544761",
          " 0", " 0", " 0"],
    "v": ["-0.00447778124", "-0.00557688391", "-0.0100546647",
          "-0.0123166461", "-0.014783985", "-0.0271006301",
          " 0.00492189778", "-0.000436067523", " 0.0044858302",
          " 0", " 0", " 0"],
    "m": [" 0.000756304245", "-0.00567045528", "-0.00491415104",
          "-0.0202216022", " 0.000443410041", "-0.019778192",
          " 0", " 0", " 0",
          " 0", " 0", " 0"],
}


def test_xoracle_worked_example_digits():
    """The transcribed independent FP32 oracle reproduces every printed
    digit of the handoff report's worked example (coef and all four pin
    points per field), validating the transcription and this
    environment's FP32 arithmetic against the blind authority."""
    nx, ny, mut, cases = _xo_example()
    for kind, field, mapx, mapy, points in cases:
        out, tx, ty, coef = xoracle_diff6_slice(
            field, kind, nx, ny, mut, mapx, mapy,
            dt=_F(6.0), factor=_F(0.12), c1=_F(0.8), c2=_F(0.2))
        assert format(float(coef), ".10g") == _XO_EXPECTED["coef"]
        got = []
        for j0, i0 in points:
            got += [format(float(tx[j0, i0]), " .9g"),
                    format(float(ty[j0, i0]), " .9g"),
                    format(float(out[j0, i0]), " .9g")]
        assert got == _XO_EXPECTED[kind], (kind, got)


def test_oracle_matches_independent_fp32_authority():
    """My float64 WRF-loop oracle agrees with the blind FP32 authority on
    its own worked example: identical computed-point support (the same
    bounds tables, including u i=nx-3 / v j=ny-3 IN and u i=nx-2 /
    v j=ny-2 OUT) and values equal to within the FP32 per-op rounding
    envelope."""
    nx, ny, mut, cases = _xo_example()
    for kind, field, mapx, mapy, _points in cases:
        out, _tx, _ty, _coef = xoracle_diff6_slice(
            field, kind, nx, ny, mut, mapx, mapy,
            dt=_F(6.0), factor=_F(0.12), c1=_F(0.8), c2=_F(0.2))
        mine = wrf_sixth_order_diffusion(
            field[None].astype(np.float64), mut,
            np.array([0.8]), np.array([0.2]), 0.12, 6.0, 2,
            kind, mapx=mapx, mapy=mapy)[0]
        np.testing.assert_allclose(mine, out.astype(np.float64),
                                   rtol=1e-5, atol=1e-9, err_msg=kind)
        assert ((mine != 0.0) == (out != 0.0)).all(), kind
        if kind == "u":
            assert (mine[3:ny - 3, nx - 3] != 0.0).all()   # ide-3 IN
            assert (mine[:, nx - 2] == 0.0).all()          # ide-2 OUT
        if kind == "v":
            assert (mine[ny - 3, 3:nx - 3] != 0.0).all()   # jde-3 IN
            assert (mine[ny - 2, :] == 0.0).all()          # jde-2 OUT


# ---------------------------------------------------------------------------
# application-path pins (GPU) -- RED at 4d2ce99
# ---------------------------------------------------------------------------

@requires_gpu
@pytest.mark.gpu
@pytest.mark.parametrize("flags", [{"specified": True}, {"nested": True}],
                         ids=["specified", "nested"])
def test_apply_diff6_computes_wrf_boundary_faces(flags):
    """apply_diff6 on a specified/nested domain must advance u at the east
    seam faces and v at the north seam faces by dt*tend/chm with the
    WRF-loop oracle tendency -- 4d2ce99 left them exactly unchanged."""
    import cupy as cp

    from woof.config import RunConfig
    from woof.core.dycore import _PROGNOSTICS, apply_diff6
    from woof.verify.npref import random_acoustic_state

    s, cfg0 = random_acoustic_state(seed=41, nz=NZ, ny=NY, nx=NX)
    cfg = RunConfig(**{**cfg0.__dict__, "diff_6th_opt": 2,
                       "diff_6th_factor": FACTOR, **flags})
    rng = np.random.default_rng(43)
    # Independent boundary-installed data on the last staggered column/row
    # (random_acoustic_state enforces periodic duplicates; a duplicate east
    # face would make the accurate read indistinguishable from the wrap).
    s.u[:, :, -1] = cp.asarray(
        2.0 * rng.standard_normal(s.u.shape[:2]), dtype=s.u.dtype)
    s.v[:, -1, :] = cp.asarray(
        2.0 * rng.standard_normal((s.v.shape[0], s.v.shape[2])),
        dtype=s.v.dtype)
    for name in _PROGNOSTICS:
        getattr(s, name + "0")[...] = getattr(s, name)
    host = {n: cp.asnumpy(getattr(s, n)).astype(np.float64)
            for n in ("u", "v", "mup", "mup0", "mub2d", "c1h", "c2h")}
    apply_diff6(s, cfg)

    mu_t = host["mub2d"] + host["mup0"]
    mu = host["mub2d"] + host["mup"]
    mux = 0.5 * (mu + np.roll(mu, 1, axis=1))
    mux = np.concatenate([mux, mux[:, :1]], axis=1)
    muy = 0.5 * (mu + np.roll(mu, 1, axis=0))
    muy = np.concatenate([muy, muy[:1, :]], axis=0)
    c1h = host["c1h"][:, None, None]
    c2h = host["c2h"][:, None, None]
    for name, stag, chm in (("u", "x", c1h * mux[None] + c2h),
                            ("v", "y", c1h * muy[None] + c2h)):
        tend = wrf_sixth_order_diffusion(
            host[name], mu_t, host["c1h"], host["c2h"], FACTOR, cfg.dt,
            cfg.diff_6th_opt, _STAG_NAME[stag])
        want = host[name] + cfg.dt * tend / chm
        got = cp.asnumpy(getattr(s, name))
        seam = _seam_mask(stag, host[name].shape)
        assert np.abs(want - host[name])[seam].max() > 1e-6, "vacuous seam"
        np.testing.assert_allclose(
            got[seam], want[seam], rtol=1e-4, atol=1e-6,
            err_msg=f"{name}: WRF-computed high-side face (RED at 4d2ce99: "
                    "woof zeroed this face's tendency)")
        # And the whole field agrees with WRF's specified-domain operator.
        np.testing.assert_allclose(got, want, rtol=1e-4, atol=1e-6,
                                   err_msg=name)


@requires_gpu
@pytest.mark.gpu
def test_prepare_fixed_tendencies_holds_wrf_boundary_faces():
    """Production wiring: prepare_fixed_tendencies on a specified domain
    (diff6-only, slopeopt=1 production shape) must hold the WRF-loop
    oracle tendency at the seam faces in its carried u/v buffers."""
    import cupy as cp

    from woof.config import RunConfig
    from woof.core.dycore import prepare_fixed_tendencies
    from woof.verify.npref import random_acoustic_state

    s, cfg0 = random_acoustic_state(seed=47, nz=NZ, ny=NY, nx=NX,
                                    hybrid_opt=2, hill_height=800.0)
    cfg = RunConfig(**{**cfg0.__dict__, "specified": True,
                       "diff_6th_opt": 2, "diff_6th_factor": FACTOR,
                       "diff_6th_slopeopt": 1})
    rng = np.random.default_rng(53)
    s.u[:, :, -1] = cp.asarray(
        2.0 * rng.standard_normal(s.u.shape[:2]), dtype=s.u.dtype)
    s.v[:, -1, :] = cp.asarray(
        2.0 * rng.standard_normal((s.v.shape[0], s.v.shape[2])),
        dtype=s.v.dtype)
    for name in ("u", "v", "w", "thp"):
        getattr(s, name + "0")[...] = getattr(s, name)
    host = {n: cp.asnumpy(getattr(s, n)).astype(np.float64)
            for n in ("u0", "v0", "mup0", "mub2d", "c1h", "c2h",
                      "phb", "msfu", "msfv")}
    prepare_fixed_tendencies(s, cfg)

    mu_t = host["mub2d"] + host["mup0"]
    for name, stag in (("u0", "x"), ("v0", "y")):
        want = wrf_sixth_order_diffusion(
            host[name], mu_t, host["c1h"], host["c2h"], FACTOR, cfg.dt,
            cfg.diff_6th_opt, _STAG_NAME[stag], phb=host["phb"],
            msfu=host["msfu"], msfv=host["msfv"], slopeopt=1,
            thresh=cfg.diff_6th_thresh, dx=cfg.dx, dy=cfg.dy)
        held = cp.asnumpy(s.scratch(getattr(s, name).shape,
                                    "smag_r" + name[0]))
        seam = _seam_mask(stag, want.shape)
        assert np.abs(want[seam]).max() > 0.0, "vacuous seam"
        np.testing.assert_allclose(
            held[seam], want[seam], rtol=1e-4, atol=1e-7,
            err_msg=f"{name}: held seam-face tendency (RED at 4d2ce99)")
        np.testing.assert_allclose(held, want, rtol=1e-4, atol=1e-7,
                                   err_msg=name)


# ---------------------------------------------------------------------------
# bitwise non-regression pins (GPU) -- capture generated at 4d2ce99
# ---------------------------------------------------------------------------

def _capture_cases():
    """(key, stagger, opt, slope_kwargs) rows shared by capture and pins."""
    rows = []
    for stagger in ("", "x", "y", "z"):
        tag = _STAG_NAME[stagger]
        for opt in (1, 2):
            rows.append((f"{tag}_{opt}", stagger, opt, {}))
        phb, msfu, msfv = _slope_inputs()
        rows.append((f"{tag}_slope", stagger, 2,
                     dict(phb=phb, msfu=msfu, msfv=msfv, slopeopt=1,
                          thresh=0.10, dx=500.0, dy=500.0)))
    return rows


def _periodic_tend(f, mut, c1, c2, opt, stagger, **slope_kw):
    """The plain periodic launch (no boundary flags), as periodic configs
    drive it -- pre- and post-fix this call is byte-for-byte the same
    request, so its output pins the kernel edit's periodic neutrality."""
    import cupy as cp

    from woof.core.dycore import launch_diff6
    fd = cp.asarray(f, dtype=cp.float32)
    tend = cp.zeros_like(fd)
    if slope_kw:
        slope_kw = dict(slope_kw)
        for key in ("phb", "msfu", "msfv"):
            slope_kw[key] = cp.asarray(slope_kw[key], cp.float32)
    launch_diff6(fd, tend, cp.asarray(mut, cp.float32),
                 cp.asarray(c1, cp.float32), cp.asarray(c2, cp.float32),
                 FACTOR, DT, opt, stagger=stagger, **slope_kw)
    return cp.asnumpy(tend)


def _periodic_case(stagger, seed=61):
    f, mut, c1, c2 = _forced_case(stagger, seed=seed)
    if stagger == "x":                    # periodic duplicates, as periodic
        f[..., -1] = f[..., 0]            # storage carries them
    if stagger == "y":
        f[:, -1, :] = f[:, 0, :]
    return f, mut, c1, c2


def generate_base_capture(path=_DATA):
    """Run on the UNMODIFIED 4d2ce99 tree (GPU): record the kernel's
    periodic outputs and the production-masked forced outputs."""
    import subprocess

    import woof
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    pkg = os.path.dirname(os.path.abspath(woof.__file__))
    assert os.path.normcase(pkg) == os.path.normcase(
        os.path.join(root, "woof")), (
        "capture must run the SAME tree as this test file, got " + pkg)
    out = {"provenance": np.array(
        "generated at 4d2ce99 (fix/diff6-boundary-face base) by "
        "tests/test_diff6_boundary_face.py:generate_base_capture; "
        "dual-run elementwise-verified; git head: " + subprocess.run(
            ["git", "rev-parse", "HEAD"], capture_output=True, text=True,
            cwd=os.path.dirname(os.path.dirname(__file__))).stdout.strip())}
    from woof.core.dycore import _zero_open_strips
    import cupy as cp
    cfg = _forced_cfg(specified=True)
    for key, stagger, opt, slope_kw in _capture_cases():
        f, mut, c1, c2 = _periodic_case(stagger)
        out["per_" + key] = _periodic_tend(f, mut, c1, c2, opt, stagger,
                                           **slope_kw)
        f, mut, c1, c2 = _forced_case(stagger)
        # The 4d2ce99 production path: plain wrapped kernel + width-3 mask
        # with the extra zeroed high-side staggered face.
        t = cp.asarray(
            _periodic_tend(f, mut, c1, c2, opt, stagger, **slope_kw))
        _zero_open_strips(t, cfg, 3, stag_high_extra=1)
        out["forced_" + key] = cp.asnumpy(t)
    np.savez_compressed(path, **out)
    return out


def _card_capture():
    """The base capture for THIS card, or a skip.

    PER CARD since 2026-09-17 (tests/_card_pins.py).  The 4d2ce99 capture
    (2026-07-27, card unrecorded) against the same requests on a development machine's
    RTX 4090 (compute capability 8.9, driver 610.57.04): every one of the
    24 rows differs, by at most 7.45e-09 (m_1: 113 of 1008 words, max
    relative 6.8e-06; u_2: 98 of 1080, max relative 2.4e-05; w_slope: 45 of
    1176), ULP-scale in 3 to 11 percent of each row's words and the same
    on the scalar rows as on u, v and w: the card, as for the phase-2 pin
    in tests/test_coriolis_map.py, not the kernel.  The 4090 file
    (tests/data/diff6_base_4d2ce99.rtx4090.npz) was written by
    tools/recapture_card_pins.py --pin diff6_base_4d2ce99 through
    generate_base_capture below (dual run, elementwise-verified) with its
    per-row reading beside it in tests/data/receipts/pin-gates/.  A card
    with no file skips.
    """
    import _card_pins
    reason = _card_pins.skip_reason("diff6_base_4d2ce99")
    if reason is not None:
        pytest.skip(reason)
    return np.load(_card_pins.path("diff6_base_4d2ce99"))


@requires_gpu
@pytest.mark.gpu
@pytest.mark.parametrize("row", _capture_cases(), ids=lambda r: r[0])
def test_periodic_path_bitwise_identical_to_base(row):
    """Periodic configs never set the boundary flags: the kernel's output
    for the identical periodic request must be bit-identical to the
    4d2ce99 capture (the fix may not perturb non-forced domains)."""
    key, stagger, opt, slope_kw = row
    data = _card_capture()
    f, mut, c1, c2 = _periodic_case(stagger)
    got = _periodic_tend(f, mut, c1, c2, opt, stagger, **slope_kw)
    np.testing.assert_array_equal(got, data["per_" + key], err_msg=key)


@requires_gpu
@pytest.mark.gpu
@pytest.mark.parametrize("row", _capture_cases(), ids=lambda r: r[0])
def test_forced_path_changes_only_the_seam_faces(row):
    """On the forced path, every face OTHER than the two newly-computed
    seam sets must be bit-identical to the 4d2ce99 capture; the seam sets
    themselves must be nonzero (u east / v north) or empty (mass/w).

    RED at 4d2ce99: launch_diff6 has no boundary-awareness to request
    (TypeError on the bnd kwargs, recorded as fix-introduced-symbol RED
    evidence per house convention)."""
    key, stagger, opt, slope_kw = row
    data = _card_capture()
    cfg = _forced_cfg(specified=True)
    f, mut, c1, c2 = _forced_case(stagger)
    if slope_kw:
        import cupy as cp
        slope_kw = dict(slope_kw)
        for name in ("phb", "msfu", "msfv"):
            slope_kw[name] = cp.asarray(slope_kw[name], cp.float32)
    got = _production_masked_tend(f, mut, c1, c2, opt, stagger, cfg,
                                  **slope_kw)
    base = data["forced_" + key]
    seam = _seam_mask(stagger, f.shape)
    np.testing.assert_array_equal(got[~seam], base[~seam], err_msg=key)
    assert (base[seam] == 0.0).all()            # what 4d2ce99 shipped
    if stagger in ("x", "y") and opt == 1:
        assert np.abs(got[seam]).min() > 0.0    # now WRF-computed
    if stagger in ("x", "y"):
        # And the computed values are WRF's: seam faces vs the oracle.
        host_slope = {}
        if slope_kw:
            import cupy as cp
            host_slope = dict(slope_kw)
            for name in ("phb", "msfu", "msfv"):
                host_slope[name] = cp.asnumpy(host_slope[name])
        want = wrf_sixth_order_diffusion(
            f, mut, c1, c2, FACTOR, DT, opt, _STAG_NAME[stagger],
            **host_slope)
        np.testing.assert_allclose(got[seam], want[seam], rtol=1e-4,
                                   atol=1e-8, err_msg=key)


if __name__ == "__main__":
    if "--generate" in sys.argv:
        first = generate_base_capture(_DATA)
        second = generate_base_capture(_DATA + ".dualrun.npz")
        for key in first:
            a, b = first[key], np.load(_DATA + ".dualrun.npz")[key]
            if key == "provenance":
                continue
            assert (a == b).all(), f"dual-run mismatch: {key}"
        os.remove(_DATA + ".dualrun.npz")
        print("capture written + dual-run verified:", _DATA)
