"""The metric extraction moved arithmetic, and moved nothing else.

Two halves, and the second is the essential one:

* the campaign scorer, re-pointed at ``woof.verify.field_metrics``, returns
  the SAME numbers it returned before the move -- compared as ``float.hex()``
  strings against a baseline generated by the pre-move code, so "the same"
  means the same bits and not merely the same to a printed precision; and
* the regression can fail: perturbing one carrier in the synthetic pair moves
  the affected metric off the baseline.  A comparison that cannot fail proves
  nothing about a refactor.

The third pin is the one the extraction exists for: FSS takes its domain's
grid spacing as an argument, so a two-domain pair is scored on BOTH domains
with no key or gate naming either of them.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pytest

import n5s_delegation_fixture as fixture
from woof.verify import field_metrics, n5s_metrics
from woof.verify.n5s_common import write_json

BASELINE_PATH = (
    Path(__file__).with_name("data") / "field_metrics_delegation_baseline.json")


def _baseline() -> dict:
    return json.loads(BASELINE_PATH.read_text(encoding="utf-8"))


def _score_campaign_pair(root: Path, *, perturb_left_seed: int = 0
                         ) -> dict[str, str]:
    """Build the fixture pair and score it through the campaign entry point."""
    baseline = _baseline()
    registration = n5s_metrics.make_registration(
        run_minutes=int(baseline["run_minutes"]),
        history_minutes=int(baseline["history_minutes"]),
        commit="4" * 40, start_time=str(baseline["start_time"]))
    cadence = int(registration["cadence_seconds"])
    duration = int(registration["run_duration_seconds"])
    left = fixture.build_run(
        root, "left", seed=11 + perturb_left_seed,
        domains=n5s_metrics.N5S_DOMAINS, cadence_seconds=cadence,
        duration_seconds=duration, object_second=cadence)
    right = fixture.build_run(
        root, "right", seed=907, domains=n5s_metrics.N5S_DOMAINS,
        cadence_seconds=cadence, duration_seconds=duration,
        object_second=2 * cadence)
    for run in (left, right):
        write_json(run / "n5s-preregistration.json", registration)
        (run / "exit.status").write_text("0\n", encoding="utf-8")
        n5s_metrics._artifact(
            run, root, run_id=run.name, registration=registration)
    return fixture.as_hex(
        n5s_metrics.score_run_pair(left, right, registration, registration))


@pytest.fixture(scope="module")
def delegated_scores(tmp_path_factory) -> dict[str, str]:
    return _score_campaign_pair(tmp_path_factory.mktemp("delegation"))


def test_the_baseline_was_measured_before_the_move(delegated_scores):
    """Every registered number survives the delegation, bit for bit."""
    expected = _baseline()["scores_hex"]
    assert delegated_scores == expected
    assert len(expected) == 61, sorted(expected)


def test_the_regression_can_fail(tmp_path):
    """CONTROL: perturb one side's fields and the comparison must break."""
    perturbed = _score_campaign_pair(tmp_path, perturb_left_seed=1)
    expected = _baseline()["scores_hex"]
    assert set(perturbed) == set(expected)
    assert perturbed != expected


def test_the_campaign_scorer_calls_the_generic_metrics(monkeypatch, tmp_path):
    """The delegation is real: break the generic function, lose the score."""
    def refuse(*args, **kwargs):
        raise AssertionError("generic metric was bypassed")

    monkeypatch.setattr(field_metrics, "state_and_boundary_rmse", refuse)
    with pytest.raises(AssertionError, match="bypassed"):
        _score_campaign_pair(tmp_path)


# --------------------------------------------------------------------------
# the point of the extraction: no domain is privileged
# --------------------------------------------------------------------------


def _echo_pair(shape=(9, 11)):
    left = np.zeros(shape, dtype=np.float64)
    right = np.zeros(shape, dtype=np.float64)
    left[2:5, 2:5] = 50.0
    right[4:7, 5:8] = 50.0
    return left, right


def test_fss_is_scored_on_every_domain_of_a_two_domain_pair():
    """A parent and a child, same physical radius, different spacings."""
    left, right = _echo_pair()
    fields = {600: left[None, ...], 1200: left[None, ...]}
    other = {600: right[None, ...], 1200: right[None, ...]}
    scored = {
        domain: field_metrics.mean_fss_distance(
            fields, other, threshold=40.0, radius_m=5000.0, dx_m=dx,
            times=(600, 1200))
        for domain, dx in (("parent", 12000.0), ("child", 3000.0))
    }
    assert set(scored) == {"parent", "child"}
    assert all(0.0 <= value <= 1.0 for value in scored.values())
    # The radius is physical, so the coarse domain sees the two echoes inside
    # one neighborhood and the fine domain does not: the distances differ, and
    # neither call named a domain.
    assert scored["parent"] != scored["child"]


def test_the_neighborhood_radius_follows_the_grid_spacing():
    assert field_metrics.half_width_cells(5000.0, 12000.0) == 0
    assert field_metrics.half_width_cells(5000.0, 1000.0) == 5
    assert field_metrics.half_width_cells(5000.0, 1000.0 / 3.0) == 15
    assert field_metrics.minimum_object_cells(25.0, 500.0) == 100
    assert field_metrics.minimum_object_cells(25.0, 12000.0) == 1


def test_identical_fields_score_zero_and_disjoint_echoes_score_one():
    left, right = _echo_pair()
    assert field_metrics.fss_distance(
        left, left, threshold=40.0, half_width=1) == 0.0
    assert field_metrics.fss_distance(
        left, right, threshold=40.0, half_width=0) == 1.0


def test_pooled_rmse_does_not_average_a_loud_window_away():
    """Pooling is by element count, and over equal windows it dominates.

    The pooled value is the quadratic mean of the per-window RMSEs, which is
    strictly above their arithmetic mean whenever the windows differ -- so one
    loud window survives a run of quiet ones instead of being averaged out.
    """
    quiet = np.zeros(100, dtype=np.float64)
    loud = np.full(100, 10.0, dtype=np.float64)
    pooled = field_metrics.aggregate_rmse([quiet, quiet, quiet, loud])
    per_window_mean = 0.25 * (3.0 * field_metrics.rmse(quiet, quiet)
                              + field_metrics.rmse(loud, quiet))
    assert pooled > per_window_mean
    assert pooled == pytest.approx(np.sqrt(100.0 * 100.0 / 400.0), rel=1e-12)


def test_object_timing_returns_the_quiet_sentinel_it_is_given():
    quiet = {300: np.zeros((1, 5, 5)), 600: np.zeros((1, 5, 5))}
    assert field_metrics.first_object_time(
        quiet, threshold=40.0, min_cells=1, quiet_time_seconds=900) == 900.0
    active = dict(quiet)
    active[600] = np.full((1, 5, 5), 45.0)
    assert field_metrics.first_object_time(
        active, threshold=40.0, min_cells=1, quiet_time_seconds=900) == 600.0


def test_the_generic_module_carries_no_campaign_pin():
    source = (Path(field_metrics.__file__)).read_text(encoding="utf-8")
    for pin in ("d01", "d02", "d03", "d04", "REFL_10CM", "12000", "3000.0",
                "40.0", "QVAPOR"):
        assert pin not in source, pin


def test_the_registration_requires_its_start_instant():
    with pytest.raises(TypeError, match="start_time"):
        n5s_metrics.make_registration(run_minutes=30, history_minutes=5)
