"""SASE-M2 S4-5c SURFACE-BASED saturated-layer real d02 column
(CODE-GENERATED by the session scratchpad probe s45c_emit.py -- do not
hand-edit).

PROVENANCE: F:\\gpuwm-runs\\sase-yolo-d\\wrfout_d02_1974-04-03_11_00_00
(the S3-15 yolo-d 10Z-init d02 run, 3 km, 49 levels), read via the
mandated wrf-rust reader (``import wrf``, WrfFile raw fields; woof
wrfouts store FULL pressure in ``P``).  Fields are the wrfout's own
values widened to FP64; THICK from the geopotential interfaces
(PH + PHB)/g, so centers reconstruct by the authority cumsum convention
z = cumsum(THICK) - THICK/2 (AGL).  Same reader, same frame and the
same construction as :mod:`vent_columns_yolod_11z` and
:mod:`vent_columns_yolod_binding`; this column is selected for a third
property.

WHY THIS COLUMN (S4-5c; design doc SASE-M section 4, amendment "a
surface-based saturated layer stands the limb down").  The M2 grow-zone
shape factor normalises on the CLOUD-BASE face,
``M_hat = (z_f[j]/z_f[k_base])**VENT_ENT_COEF``.  When the saturated run
is based in the LOWEST MODEL LEVEL there is no cloud base distinct from
the ground -- ``z_f[0] = 0`` identically -- and the pre-amendment
``z_f[max(k_base, 1)]`` guard silently substituted the lowest layer's
THICKNESS for a height, making the amplitude a function of the vertical
grid rather than of the state.  The amendment stands such a column DOWN
as a fourth registered stand-down condition (a saturated layer sitting
on the ground is fog or surface-based stratus -- ED-limb business, M1,
not a plume launched from a cloud base that does not exist).

No column of the registered M2 corpus was surface-based, so the whole
branch was fixture-invisible: any change confined to it is bitwise-inert
on all 14 device parity columns and on every active column the CPU
corpus evaluates (measured, S4-5c).  That is exactly why this fixture
exists -- without it the ruling is unpinned in both engines.

MEASURED THIS SESSION on the stored arrays (design-point turbulence,
see TURBULENCE below):

* the lowest qualifying member run is k0..k17, i.e. k_base = 0 -- the
  SURFACE-BASED case -- with the root falling back to the run's own
  base, k_r = 0;
* the termination search does find a neutral-buoyancy level (LFC k1,
  buoyancy peak k1, NB k2, ceiling k_lid = 19), so NONE of the three
  older stand-down conditions fires here: pre-amendment this column
  FIRED, and only the new rule stands it down;
* pre-amendment it carried exactly ONE live face, face 1, at
  z_f[1] = 17.158959716345805 m -- which is the lowest layer THICKNESS
  the guard substituted for a cloud-base height.  MEASURED over the
  19495 post-step-4 active columns of this frame at the design point
  (S4-5c survey): the median anchor face z_f[k_base] is 610.38 m on the
  19404 columns with k_base > 0 and 17.08 m on the 91 surface-based
  ones, i.e. the guard replaces a cloud base by a cell thickness 36x
  smaller.  On this column face 1 is 1.14% of the run's own top face
  z_f[18] = 1783.42 m.  The pre-amendment values there were
  F_theta = 1.0936614241370526e-04 K kg m^-2 s^-1,
  F_qv = -2.5045341775200348e-08, F_qc = +5.7495439187758184e-08 and
  export F_qv + F_qc = 3.2450097412557837e-08 kg m^-2 s^-1.

  NOTE, and it is the accurate reading of this fixture: the single live
  face IS the anchor face, so M_hat = (z_f[1]/z_f[1])**VENT_ENT_COEF =
  1 exactly on it.  This column therefore pins the RULING (a
  surface-based run stands the limb down) and does NOT by itself
  exhibit the grid-dependent amplification -- on it the rejected
  "M_hat = 1 on the branch" disposition and the pre-amendment build
  agree bitwise, and only the ruling separates from both.  The
  amplification is a population measurement (S4-5c survey: the frame
  MAXIMUM export is a surface-based column in all three surveyed
  frames);
* the same arrays with MEMBERSHIP VETOED at k0 -- identical
  thermodynamics, the run's base one cell off the ground -- fire at
  17 live faces and export 7.665561399182368e-04, which is what makes
  this fixture non-vacuous: nothing else about this column stands it
  down.

TURBULENCE (registered survey standard, design doc SASE-M section 4,
amendment "two survey standards" (a)): the yolo-d frames are output of
the defective run and their TKE_SASE sits below the G-M5 reference
floor of 0.5 m2/s2 -- the column max here is 0.03757721930742264 m2/s2
(pinned below).  Amplitude is therefore evaluated at DESIGN-POINT
turbulence inside the G-M5 band [0.5, 1.6] m2/s2: ``SURVEY_E`` = 1.0
m2/s2 uniform, the same value :mod:`vent_columns_yolod_binding` uses.
The frame's own profile is kept as ``SURF_E_FRAME`` for provenance;
nothing in the suite draws an amplitude conclusion from it.  The rule
this column binds is an INDEX-structure rule and is independent of
e_sgs entirely (e enters only the scalar amplitude M_used).

The import-time assertions at the bottom re-derive the saturation state
and every premise above from the stored arrays, so a fixture that
stopped exhibiting them fails loudly at import instead of going quietly
vacuous.
"""
import numpy as np


# --- SURF: j=13 i=205 34.5182 N -85.4787 E ---
SURF_THETA = np.array([
    294.6542053222656,
    294.75787353515625,
    294.8857421875,
    295.04620361328125,
    295.2569885253906,
    295.5198974609375,
    295.8431091308594,
    296.2470703125,
    296.71563720703125,
    297.2129211425781,
    297.75140380859375,
    298.34375,
    298.9970397949219,
    299.7646484375,
    300.58673095703125,
    301.5303039550781,
    302.39569091796875,
    303.0295715332031,
    304.5058288574219,
    307.2634582519531,
    310.2637939453125,
    311.7995300292969,
    312.35333251953125,
    312.7314758300781,
    313.2945556640625,
    314.44683837890625,
    316.3758544921875,
    318.0958557128906,
    319.3734436035156,
    320.87310791015625,
    323.12066650390625,
    325.6959228515625,
    327.3650817871094,
    328.64544677734375,
    330.65960693359375,
    333.85296630859375,
    337.6400146484375,
    341.51202392578125,
    346.7457275390625,
    354.2816162109375,
    362.57830810546875,
    369.4302062988281,
    374.2611999511719,
    377.9913024902344,
    381.11407470703125,
    383.8103942871094,
    386.3934326171875,
    390.7191467285156,
    391.96087646484375,
])

SURF_QV = np.array([
    0.013813299126923084,
    0.013770553283393383,
    0.013727380894124508,
    0.013687356375157833,
    0.013650059700012207,
    0.013624344952404499,
    0.013602963648736477,
    0.013598507270216942,
    0.013585570268332958,
    0.013522954657673836,
    0.013406696729362011,
    0.01323129516094923,
    0.012989889830350876,
    0.012704209424555302,
    0.012308115139603615,
    0.01183448825031519,
    0.011119621805846691,
    0.01007850281894207,
    0.007692897692322731,
    0.004324977286159992,
    0.002096513519063592,
    0.0017031917814165354,
    0.0017262498149648309,
    0.0015014689415693283,
    0.0012523100012913346,
    0.0008484682766720653,
    0.0004245556192472577,
    0.0004130383604206145,
    0.00040825328323990107,
    0.0002762079529929906,
    0.0001638018584344536,
    0.00010263976582791656,
    8.861096284817904e-05,
    6.908951763762161e-05,
    4.497236659517512e-05,
    2.8197362553328276e-05,
    1.7553458746988326e-05,
    1.3093341294734273e-05,
    1.1962951248278841e-05,
    1.04009259302984e-05,
    7.249307145684725e-06,
    4.223568794259336e-06,
    2.755971763690468e-06,
    2.3267721189768054e-06,
    2.3180396055977326e-06,
    2.354253865632927e-06,
    2.3617669739905978e-06,
    2.38141819863813e-06,
    2.3958571091498015e-06,
])

SURF_QC = np.array([
    4.7270423237932846e-05,
    8.716268348507583e-05,
    0.00012587607488967478,
    0.00016091216821223497,
    0.00020306532678660005,
    0.00023694340779911727,
    0.00022179305960889906,
    0.00020680492161773145,
    0.00022710999473929405,
    0.0003033724788110703,
    0.0003789213369600475,
    0.00044377229642122984,
    0.0004865465743932873,
    0.0005111293285153806,
    0.0005352225853130221,
    0.0003967628290411085,
    0.0002605236368253827,
    4.1337276343256235e-05,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
])

SURF_P = np.array([
    96118.4453125,
    95907.4296875,
    95660.9375,
    95372.859375,
    95021.34375,
    94617.8828125,
    94140.1875,
    93580.03125,
    92923.390625,
    92153.203125,
    91250.796875,
    90196.5234375,
    88970.7890625,
    87544.25,
    85892.65625,
    83987.328125,
    81798.109375,
    79295.9453125,
    76456.1171875,
    73254.1953125,
    69670.484375,
    65687.8203125,
    61299.12890625,
    56668.0859375,
    52198.02734375,
    48106.515625,
    44358.6640625,
    40923.31640625,
    37773.05078125,
    34884.765625,
    32237.24609375,
    29810.697265625,
    27589.025390625,
    25562.1015625,
    23718.6875,
    22042.1875,
    20517.216796875,
    19129.98046875,
    17868.658203125,
    16722.126953125,
    15679.2685546875,
    14730.6923828125,
    13867.427734375,
    13082.3642578125,
    12367.267578125,
    11721.1953125,
    11124.5947265625,
    10592.080078125,
    10115.375,
])

SURF_THICK = np.array([
    17.158959716345805,
    20.384402231338868,
    24.01686463273387,
    28.454933788676783,
    33.5553189665535,
    39.72485899074604,
    46.91094525849542,
    55.463316875617124,
    65.4191852223496,
    77.30137691828338,
    91.18768845615523,
    107.42157791246575,
    126.4677741841075,
    148.80469708146165,
    174.9115425755367,
    205.20875641086923,
    240.43538349241044,
    280.59525018316776,
    327.05438363078156,
    381.5157051358624,
    444.87232515449796,
    516.3894637765993,
    596.2546314546698,
    642.0928675100349,
    623.9734023596775,
    607.7623155381943,
    593.6199907619775,
    579.6722443218014,
    565.2224541682599,
    550.7691549598621,
    538.0462926462151,
    525.4492834559769,
    510.6461240124863,
    492.50799367673244,
    475.2342107463701,
    460.00852127930557,
    445.2640202917937,
    430.64932944699285,
    417.19304978179207,
    406.7538106842512,
    396.4016011244894,
    383.69339720310927,
    369.45636527618626,
    353.6672360792545,
    337.24202225089175,
    321.5734203778047,
    305.2686592125374,
    290.5335654784667,
    274.1521526185006,
])

#: the FRAME's own TKE_SASE profile (provenance only --
#: below the G-M5 floor; SURVEY_E sets the amplitude).
SURF_E_FRAME = np.array([
    0.03757721930742264,
    0.03672405704855919,
    0.0156607273966074,
    0.0036284506786614656,
    0.0014467949513345957,
    0.001158377155661583,
    0.0007118007051758468,
    0.000244804221438244,
    3.896316047757864e-05,
    3.279848669990315e-06,
    1.0000003385357559e-06,
    9.999999974752427e-07,
    9.999999974752427e-07,
    9.999999974752427e-07,
    9.999999974752427e-07,
    9.999999974752427e-07,
    9.999999974752427e-07,
    9.999999974752427e-07,
    9.999999974752427e-07,
    9.999999974752427e-07,
    9.999999974752427e-07,
    9.999999974752427e-07,
    9.999999974752427e-07,
    9.999999974752427e-07,
    9.999999974752427e-07,
    9.999999974752427e-07,
    9.999999974752427e-07,
    9.999999974752427e-07,
    9.999999974752427e-07,
    9.999999974752427e-07,
    9.999999974752427e-07,
    9.999999974752427e-07,
    9.999999974752427e-07,
    9.999999974752427e-07,
    9.999999974752427e-07,
    9.999999974752427e-07,
    9.999999974752427e-07,
    9.999999974752427e-07,
    9.999999974752427e-07,
    9.999999974752427e-07,
    9.999999974752427e-07,
    9.999999974752427e-07,
    9.999999974752427e-07,
    9.999999974752427e-07,
    9.999999974752427e-07,
    9.999999974752427e-07,
    9.999999974752427e-07,
    1.4387655937753152e-06,
    9.999999974752427e-07,
])

SURF_LAT = 34.5181884765625
SURF_LON = -85.47868347167969
SURF_HGT = 406.2795104980469
SURF_LANDMASK = 1.0
SURF_J = 13
SURF_I = 205

N_LEVELS = 49

#: Design-point subgrid energy [m2/s2] inside the G-M5 band [0.5, 1.6]
#: -- the registered survey standard (see the module docstring).
SURVEY_E = 1.0

# --- import-time premise assertions ---------------------------------
_P0 = 1.0e5
_RD, _CP, _XLV = 287.0, 1004.5, 2.5e6
_SVP1, _SVP2, _SVP3, _SVPT0 = 0.6112, 17.67, 29.65, 273.15
_EP2 = 0.6217504


def _sat(th, qv, qc, p):
    """(membership on the registered qt >= qs test, theta_es) from the
    same Tetens-liquid constants woof.verify.sase_ref.moist_n2 uses."""
    t = th * (p / _P0) ** (_RD / _CP)
    es = 1000.0 * _SVP1 * np.exp(_SVP2 * (t - _SVPT0) / (t - _SVP3))
    qs = _EP2 * es / (p - es)
    return (qv + qc) >= qs, th * np.exp(_XLV * qs / (_CP * t))


def _lowest_run(memb, min_cells=2):
    """The lowest contiguous run of >= min_cells member cells -- the
    authority's step 1 (its bulk theta_es reading is asserted below)."""
    k = 0
    while k < len(memb):
        if not memb[k]:
            k += 1
            continue
        s = k
        while k + 1 < len(memb) and memb[k + 1]:
            k += 1
        if k - s >= min_cells - 1:
            return s, k
        k += 1
    return None


assert len(SURF_THETA) == N_LEVELS and len(SURF_THICK) == N_LEVELS
_memb, _thes = _sat(SURF_THETA, SURF_QV, SURF_QC, SURF_P)
_run = _lowest_run(_memb)
assert _run is not None, "must have a >=2-cell saturated run"
_kb, _kt = _run
assert _thes[_kt] < _thes[_kb], "run must be moist-unstable"
# THE PREMISE THIS FIXTURE EXISTS FOR: the run is based in the LOWEST
# MODEL LEVEL -- there is no cloud base distinct from the ground.
assert (_kb, _kt) == (0, 17), (_kb, _kt)
# ... and the guard the amendment removes would have substituted the
# lowest layer THICKNESS for the cloud-base height: face 1 sits at 17.16
# m, ~1% of this column's own run-top face.
_zf = np.concatenate([[0.0], np.cumsum(SURF_THICK)])
assert _zf[0] == 0.0
assert 15.0 < _zf[1] < 20.0, _zf[1]
assert _zf[_kt + 1] / _zf[1] > 100.0, (_zf[_kt + 1], _zf[1])
# ... the frame's own turbulence is below the G-M5 floor, which is why
# SURVEY_E and not SURF_E_FRAME sets the amplitude.
assert SURF_E_FRAME.max() < 0.5, SURF_E_FRAME.max()
# ... and NO older stand-down condition fires here: the run's own top is
# well inside the column and well inside VENT_DEPTH_CAP of the root, so
# the ceiling k_lid = k_top + 2 exists and is reachable.
assert _kt + 2 < N_LEVELS, _kt
_zc = np.cumsum(SURF_THICK) - 0.5 * SURF_THICK
assert _zc[_kt + 2] - _zc[_kb] < 4000.0, _zc[_kt + 2] - _zc[_kb]
