"""Run both compiled legacy references and pack a retained word-level fixture.

Usage: python legacy_pack.py BUILD_DIRECTORY FIXTURE_DIRECTORY OUTPUT.npz
FIXTURE_DIRECTORY is generated by synth.py. No GPU is accessed.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import subprocess

import numpy as np


def pack(build: Path, fixture: Path, output: Path) -> None:
    def read_outputs():
        return {p.stem: np.fromfile(p, dtype=np.float32)
                for p in fixture.glob("wrf_*.bin")}

    subprocess.run([str(build / "original/legacy_oracle"), str(fixture), "chain"], check=True)
    original = read_outputs()
    subprocess.run([str(build / "corrected/legacy_oracle"), str(fixture), "chain"], check=True)
    corrected = read_outputs()
    for name in original:
        if name != "wrf_rw_t" and original[name].tobytes() != corrected[name].tobytes():
            raise ValueError(f"lower-boundary correction changed {name}")
    arrays = {p.stem: np.fromfile(p, dtype=np.float32)
              for p in fixture.glob("*.bin")}
    arrays["original_rw_t"] = original["wrf_rw_t"]
    arrays["meta"] = np.array((fixture / "meta.txt").read_text().split())
    arrays["provenance"] = np.array(json.dumps(json.loads((build / "receipt.json").read_text()),
                                             sort_keys=True))
    if (fixture / "coordinate.json").exists():
        arrays["coordinate"] = np.array((fixture / "coordinate.json").read_text())
    np.savez_compressed(output, **arrays)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("build", type=Path)
    parser.add_argument("fixture", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    pack(args.build.resolve(), args.fixture.resolve(), args.output.resolve())
