#!/usr/bin/env python3
"""Lift TRANSFER_MP_PARAMETERS and SNOW_INIT out of the pinned Noah-MP driver.

Why this exists
---------------
``patches/noahmp-lsm-leaf-visibility.patch`` makes every ``private ::`` routine
of ``phys/module_sf_noahmplsm.F`` public, which is what lets a harness call
ENERGY directly.  That same lift makes the leaf routine ``ALBEDO`` public, and
``phys/module_sf_noahmpdrv.F:227`` declares a dummy argument of the same name,
so the driver **cannot be compiled against the patched module**
(``Name 'albedo' ... is an ambiguous reference``).  ``build_visibility_cross
check.sh`` stage 4 pins that fact deliberately: it is the reason the patched
module can never reach a forecast build.

The ENERGY fixture nevertheless needs two driver-side services, and both must
be WRF's own code rather than a transcription:

* ``TRANSFER_MP_PARAMETERS`` -- fills ``noahmp_parameters`` from the pinned
  MPTABLE/SOILPARM/GENPARM.  Its output is already pinned independently in
  ``woof/data/noahmp/oracle/noahmp-parameters.csv``.
* ``SNOW_INIT`` -- builds ISNOW/ZSNSO/SNICE/SNLIQ/STC exactly as WRF does, so
  the ENERGY cases sit on a snow topology a forecast can actually present.

This script copies those two subroutines **verbatim, byte for byte** out of the
pristine driver into a standalone module.  It refuses to run if the extracted
text is not a contiguous slice of the pinned source, if either routine mentions
``ALBEDO`` (which would re-create the collision), or if the driver's sha256 is
not the pinned one.  Nothing is hand-written here but the module wrapper.
"""

from __future__ import annotations

import argparse
import hashlib
import re
import sys
from pathlib import Path

# phys/module_sf_noahmpdrv.F, WRF v4.6.1, pinned tree commit
# d66e442fccc04111067e29274c9f9eaccc3cef28.
PRISTINE_DRV_SHA256 = None  # filled from --expect-sha; see build_energy.sh

_BEGIN = {
    "TRANSFER_MP_PARAMETERS": re.compile(
        r"^\s*SUBROUTINE\s+TRANSFER_MP_PARAMETERS\s*\(", re.IGNORECASE),
    "SNOW_INIT": re.compile(
        r"^\s*SUBROUTINE\s+SNOW_INIT\s*\(", re.IGNORECASE),
}


def _slice(lines: list[str], name: str) -> tuple[int, int]:
    begin = _BEGIN[name]
    end = re.compile(r"^\s*END\s+SUBROUTINE\s+" + name + r"\s*$", re.IGNORECASE)
    first = last = None
    for i, line in enumerate(lines):
        if first is None and begin.match(line):
            first = i
        elif first is not None and end.match(line.rstrip()):
            last = i
            break
    if first is None or last is None:
        raise SystemExit(f"{name}: could not locate a complete subroutine body")
    return first, last


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("driver", type=Path,
                    help="pristine phys/module_sf_noahmpdrv.F")
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--expect-sha", required=True,
                    help="sha256 of the pristine driver source")
    args = ap.parse_args(argv)

    raw = args.driver.read_bytes()
    got = hashlib.sha256(raw).hexdigest()
    if got != args.expect_sha:
        raise SystemExit(
            f"driver sha256 mismatch\n  expected {args.expect_sha}\n  got      {got}")

    lines = raw.decode("utf-8", errors="surrogateescape").splitlines()

    bodies = []
    for name in ("TRANSFER_MP_PARAMETERS", "SNOW_INIT"):
        first, last = _slice(lines, name)
        body = lines[first:last + 1]
        # The collision that keeps the driver out of a patched build is the
        # name ALBEDO.  Neither extracted routine may mention it, or the
        # extraction would simply move the problem.
        for offset, line in enumerate(body):
            if re.search(r"\bALBEDO\b", line, re.IGNORECASE):
                raise SystemExit(
                    f"{name} line {first + offset + 1} mentions ALBEDO; "
                    "extraction would recreate the driver name collision")
        # Verify the slice really is contiguous pinned text.
        assert "\n".join(body) == "\n".join(lines[first:last + 1])
        bodies.append((name, first + 1, last + 1, body))

    out = ["! GENERATED by tools/noahmp_wrf461_oracle/extract_drv_helpers.py.",
           "! Do not edit.  Every line between the CONTAINS and END MODULE is a",
           "! byte-for-byte copy of phys/module_sf_noahmpdrv.F from the pinned WRF",
           f"! v4.6.1 tree, sha256 {args.expect_sha}.",
           "!"]
    for name, first, last, _ in bodies:
        out.append(f"!   {name}: module_sf_noahmpdrv.F lines {first}-{last}")
    out += ["",
            "module noahmp_drv_helpers",
            "  implicit none",
            "  public",
            "contains",
            ""]
    for _, _, _, body in bodies:
        out.extend(body)
        out.append("")
    out.append("end module noahmp_drv_helpers")

    args.out.write_text("\n".join(out) + "\n", encoding="utf-8", newline="\n")
    digest = hashlib.sha256(args.out.read_bytes()).hexdigest()
    for name, first, last, body in bodies:
        print(f"lifted {name} ({len(body)} lines, driver {first}-{last})")
    print(f"sha256({args.out.name}) = {digest}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
