# ======================================================================
# THIRD-PARTY NOTICE.  Parts of this file are hand transcriptions of
# third-party work.  ArWen distributes the file under the Apache License
# 2.0; the notices below belong to the transcribed parts and are kept here
# because their own licences require it.  Full texts are in the repository
# NOTICE and in the licenses/ directory.
#
#   RRTMG longwave/shortwave, transcribed from WRF v4.6.1
#   phys/module_ra_rrtmg_lw.F and phys/module_ra_rrtmg_sw.F, which carry
#   AER's own notice seven and nine times respectively:
#
#       Copyright 2002-2008, Atmospheric & Environmental Research, Inc. (AER).
#       This software may be used, copied, or redistributed as long as it is
#       not sold and this copyright notice is reproduced on each copy made.
#       This model is provided as is without any express or implied warranties.
#                             (http://www.rtweb.aer.com/)
#
#   ArWen takes this material under AER's own current grant instead: BSD
#   3-Clause, "Copyright (c) 2020, Atmospheric and Environmental
#   Research", published by AER at github.com/AER-RC/RRTMG_LW and
#   .../RRTMG_SW.  Text in licenses/LICENSE-AER-RRTMG-BSD-3-Clause.txt and
#   beside the packaged coefficients in woof/data/wrf_radiation/.
# ======================================================================
"""Bit-exact NumPy port of WRF v4.6.1's RRTMG McICA subcolumn generators.

Source authority: ``module mcica_subcol_gen_lw`` in
``phys/module_ra_rrtmg_lw.F`` and ``module mcica_subcol_gen_sw`` in
``phys/module_ra_rrtmg_sw.F`` (WRF v4.6.1, FP32 ``kind_rb`` build).  WRF's
legacy RRTMG option-4 drivers call these with the kissvec generator
(``irng = 0``), per-column seeds derived from the fractional parts of the
four bottom-layer pressures, and fixed permute seeds:

* longwave  (``rrtmg_lwrad``): ``irng = 0``, ``permuteseed = 150``
* shortwave (``rrtmg_swrad``): ``irng = 0``, ``permuteseed = 1``

and ``icld = cldovrlp`` from the WRF namelist (default 2, maximum-random
overlap).  ``idcor``, ``juldat`` and ``lat`` select the decorrelation
length for the exponential overlaps (``icld = 4, 5``).

FROZEN CONTRACT (consumed by the RRTMG LW/SW compute lanes)
-----------------------------------------------------------
:func:`generate_lw_subcolumns` / :func:`generate_sw_subcolumns` mirror the
Fortran dummy argument names of ``mcica_subcol_lw`` / ``mcica_subcol_sw``
one for one (``iplon`` is accepted and unused, exactly like the Fortran
dummy).  Arrays use the Fortran dimension order: per-column inputs are
``(ncol, nlay)``, band inputs ``(nbnd, ncol, nlay)``, and the returned
dict carries the Fortran output names with subcolumn arrays shaped
``(ngpt, ncol, nlay)`` (``ngptlw = 140``, ``ngptsw = 112``), all float32.
Layer index 0 is the layer nearest the surface (WRF passes bottom-up
columns; the kissvec seed requires ``pmid`` non-increasing across the
bottom four layers).

Every float32 operation reproduces the gfortran -O0 sequence of the
Fortran (multiplies/adds rounded singly, no FMA); integer RNG state is
exact 32-bit wraparound arithmetic; ``exp`` on float32 goes through
:mod:`woof.core.noahmp_libm`'s bit-exact glibc 2.39 ``expf``.  The gate
is ``tests/test_rrtmg_mcica.py`` against fixtures generated by the
unmodified WRF Fortran (``tools/rrtmg_wrf461_oracle/mcica_fixture_lw`` /
``_sw``), matched bit for bit.

Documented fail-closed divergences from WRF-undefined behaviour
---------------------------------------------------------------
* ``icld = 0``: the Fortran returns with every ``intent(out)`` array left
  undefined (the WRF driver never calls the generator in that state).
  This port raises instead of inventing output values.
* ``icld`` outside ``0..5``: the LW Fortran executes ``STOP``; the SW
  Fortran falls through its ``select case`` and uses an uninitialized
  CDF array (undefined behaviour).  This port raises for both.
* ``irng /= 0`` selects the Mersenne-Twister path, which WRF's option-4
  drivers never use; it is not ported and raises rather than silently
  substituting a different RNG.

CUDA device twin (forecast path)
--------------------------------
:func:`gpu_generate_lw_subcolumns` / :func:`gpu_generate_sw_subcolumns`
are device twins of the NumPy entries for ``icld = 2`` (maximum-random)
ONLY -- any other ``icld`` raises :class:`NotImplementedError` host-side
before any launch, and the NumPy generators above keep serving the other
overlaps.  They accept the same logical inputs (numpy or cupy float32),
return cupy arrays in the frozen output shapes, and are gated bitwise
against the NumPy port (hence transitively against the WRF Fortran) by
the device section of ``tests/test_rrtmg_mcica.py``.  Kernels live in
``woof/core/kernels/rrtmg_mcica_wrf.cu``.
"""

from __future__ import annotations

import numpy as np
# numpy >= 2 is essential for the FP32 max_ulp-0 discipline in this
# module: NEP-50 weak promotion keeps float32 op python-scalar in
# float32, while numpy 1.x would silently widen those chains to float64
# and break bitwise parity with the WRF oracle.  Fail closed at import.
if tuple(int(part) for part in np.__version__.split(".")[:2]) < (2, 0):
    raise ImportError(
        f"{__name__} requires numpy >= 2 (NEP-50 weak promotion is part "
        f"of its bitwise FP32 contract); found numpy {np.__version__}")


from woof.core.noahmp_libm import expf

__all__ = [
    "NGPTLW", "NGPTSW", "NBNDLW", "NBNDSW",
    "LW_PERMUTESEED", "SW_PERMUTESEED",
    "generate_lw_subcolumns", "generate_sw_subcolumns",
    "MCICA_DEVICE_ICLD", "MCICA_DEVICE_COLUMN_CHUNK",
    "MCICA_GPU_KERNEL_NAMES", "mcica_gpu_preflight",
    "mcica_gpu_local_frame_bytes", "mcica_device_vram_bytes",
    "gpu_generate_lw_subcolumns", "gpu_generate_sw_subcolumns",
]

NBNDLW = 16
NGPTLW = 140
NBNDSW = 14
NGPTSW = 112

#: permuteseed WRF v4.6.1 hardwires in rrtmg_lwrad / rrtmg_swrad.
LW_PERMUTESEED = 150
SW_PERMUTESEED = 1

# ngb data statements from lwcmbdat / swcmbdat: the band index of every
# reduced g-point (LW bands 1..16, SW bands 16..29).
_LW_NGC = (10, 12, 16, 14, 16, 8, 12, 8, 12, 6, 8, 8, 4, 2, 2, 2)
_SW_NGC = (6, 12, 8, 8, 10, 10, 2, 10, 8, 6, 6, 8, 6, 12)
_LW_NGB = np.repeat(np.arange(1, 17), _LW_NGC)          # 140 entries
_SW_NGB = np.repeat(np.arange(16, 30), _SW_NGC)         # 112 entries
assert _LW_NGB.shape == (NGPTLW,) and _SW_NGB.shape == (NGPTSW,)

_F32_ONE = np.float32(1.0)
_F32_ZERO = np.float32(0.0)
_CLDMIN = np.float32(1.0e-20)
_KISS_SCALE = np.float32(2.328306e-10)
_KISS_HALF = np.float32(0.5)
_PMID_SCALE = np.float32(1.0e2)
_SEED_SCALE = np.float32(1000000000.0)   # 1000000000_im converted to REAL(4)

# Decorrelation-length constants (mcica_subcol_lw/sw locals).
_AM1 = np.float32(1.4315)
_AM2 = np.float32(2.1219)
_AM4 = np.float32(-25.584)
_AMR = np.float32(7.0)
_ZO_DEFAULT = np.float32(2500.0)


def _expf32(values: np.ndarray) -> np.ndarray:
    """Elementwise glibc-2.39 expf on a float32 array."""
    flat = values.ravel()
    out = np.empty(flat.shape, dtype=np.float32)
    for i, x in enumerate(flat):
        out[i] = np.float32(expf(float(x)))
    return out.reshape(values.shape)


def _kissvec(seeds: list[np.ndarray]) -> np.ndarray:
    """One kissvec call: advance the four uint32 seed vectors, return the
    float32 random vector.  Bitwise identical to WRF's int32 kissvec (all
    Fortran ishft shifts are logical, hence the uint32 carrier)."""
    s1, s2, s3, s4 = seeds
    s1 = (np.uint32(69069) * s1 + np.uint32(1327217885)).astype(np.uint32)
    s2 = s2 ^ ((s2 << np.uint32(13)) & np.uint32(0xFFFFFFFF))
    s2 = s2 ^ (s2 >> np.uint32(17))
    s2 = s2 ^ ((s2 << np.uint32(5)) & np.uint32(0xFFFFFFFF))
    s3 = (np.uint32(18000) * (s3 & np.uint32(0xFFFF)) +
          (s3 >> np.uint32(16))).astype(np.uint32)
    s4 = (np.uint32(30903) * (s4 & np.uint32(0xFFFF)) +
          (s4 >> np.uint32(16))).astype(np.uint32)
    kiss = (s1 + s2 + ((s3 << np.uint32(16)) & np.uint32(0xFFFFFFFF)) + s4
            ).astype(np.uint32)
    seeds[0], seeds[1], seeds[2], seeds[3] = s1, s2, s3, s4
    # REAL(kiss): signed int32 value converted to float32 (round-nearest),
    # then a single float32 multiply and add.
    kiss_signed = kiss.view(np.int32).astype(np.float32)
    return (kiss_signed * _KISS_SCALE + _KISS_HALF).astype(np.float32)


def _make_seeds(pmid: np.ndarray, change_seed: int) -> list[np.ndarray]:
    """Per-column kissvec seeds from the bottom-four-layer pressures,
    advanced ``changeSeed`` times, exactly as generate_stochastic_clouds."""
    ncol = pmid.shape[0]
    if pmid.shape[1] < 4:
        raise ValueError("kissvec seeding requires at least four layers")
    if np.any(pmid[:, 0] < pmid[:, 1]):
        raise ValueError(
            "MCICA_SUBCOL: KISSVEC SEED GENERATOR REQUIRES PMID FROM "
            "BOTTOM FOUR LAYERS.")
    seeds = []
    for layer in range(4):
        col = pmid[:, layer]
        ipart = col.astype(np.int32)                    # Fortran INT(): trunc
        frac = (col - ipart.astype(np.float32)).astype(np.float32)
        scaled = (frac * _SEED_SCALE).astype(np.float32)
        seeds.append(scaled.astype(np.int32).view(np.uint32).copy())
    rand = np.empty(ncol, dtype=np.float32)
    for _ in range(change_seed):
        rand = _kissvec(seeds)
    del rand
    return seeds


def _decorr_len(ncol: int, idcor: int, juldat: int,
                lat: np.float32) -> np.ndarray:
    if idcor == 1:
        if juldat > 181:
            am3 = np.float32(np.float32(np.float32(np.float32(-4.0) * _AMR)
                                        / np.float32(365.0))
                             * np.float32(juldat - 272))
        else:
            am3 = np.float32(np.float32(np.float32(np.float32(4.0) * _AMR)
                                        / np.float32(365.0))
                             * np.float32(juldat - 91))
        diff = np.float32(np.float32(lat) - am3)
        arg = np.float32(-np.float32(np.float32(diff * diff)
                                     / np.float32(_AM4 * _AM4)))
        value = np.float32(
            np.float32(_AM1 + np.float32(
                _AM2 * np.float32(expf(float(arg)))))
            * np.float32(1.0e3))
    else:
        value = _ZO_DEFAULT
    return np.full(ncol, value, dtype=np.float32)


def _generate_stochastic_clouds(ncol, nlay, nsubcol, icld, irng, pmid,
                                cldf, hgt, decorr_len, change_seed):
    """Port of generate_stochastic_clouds[_sw] through the CDF stage.

    Returns the boolean iscloudy mask, shape (nsubcol, ncol, nlay).
    ``cldf`` is the already cldmin-thresholded cloud fraction.
    """
    if irng != 0:
        raise NotImplementedError(
            "irng != 0 selects the Mersenne-Twister generator, which WRF's "
            "RRTMG option-4 drivers never use; only kissvec (irng = 0) is "
            "ported")
    overlap = int(icld)
    seeds = _make_seeds(pmid, change_seed)
    cdf = np.empty((nsubcol, ncol, nlay), dtype=np.float32)

    if overlap == 1:
        for isubcol in range(nsubcol):
            for ilev in range(nlay):
                cdf[isubcol, :, ilev] = _kissvec(seeds)
    elif overlap == 2:
        for isubcol in range(nsubcol):
            for ilev in range(nlay):
                cdf[isubcol, :, ilev] = _kissvec(seeds)
        for ilev in range(1, nlay):
            below = cdf[:, :, ilev - 1]
            clear_frac = (_F32_ONE - cldf[:, ilev - 1]).astype(np.float32)
            keep = below > clear_frac[None, :]
            scaled = (cdf[:, :, ilev] * clear_frac[None, :]).astype(
                np.float32)
            cdf[:, :, ilev] = np.where(keep, below, scaled)
    elif overlap == 3:
        for isubcol in range(nsubcol):
            rand = _kissvec(seeds)
            cdf[isubcol, :, :] = rand[:, None]
    elif overlap in (4, 5):
        zo_inv = (_F32_ONE / decorr_len).astype(np.float32)
        alpha = np.zeros((ncol, nlay), dtype=np.float32)
        diff = (hgt[:, 1:] - hgt[:, :-1]).astype(np.float32)
        arg = -(diff * zo_inv[:, None]).astype(np.float32)
        alpha[:, 1:] = _expf32(arg)
        if overlap == 5:
            # Decorrelate where a clear layer follows a cloudy layer.
            decorrelate = (cldf[:, 1:] == _F32_ZERO) & \
                (cldf[:, :-1] > _F32_ZERO)
            alpha[:, 1:][decorrelate] = _F32_ZERO
        cdf2 = np.empty_like(cdf)
        for isubcol in range(nsubcol):
            for ilev in range(nlay):
                cdf[isubcol, :, ilev] = _kissvec(seeds)
                cdf2[isubcol, :, ilev] = _kissvec(seeds)
        for ilev in range(1, nlay):
            correlated = cdf2[:, :, ilev] < alpha[None, :, ilev]
            cdf[:, :, ilev] = np.where(
                correlated, cdf[:, :, ilev - 1], cdf[:, :, ilev])
    else:
        raise ValueError(
            f"MCICA_SUBCOL: INVALID ICLD {icld}: the WRF LW Fortran STOPs "
            "and the SW Fortran would read an uninitialized CDF array "
            "(undefined behaviour); woof fails closed for both")

    threshold = (_F32_ONE - cldf).astype(np.float32)    # (ncol, nlay)
    return cdf >= threshold[None, :, :]


def _common_inputs(ncol, nlay, play, cldfrac, hgt):
    play = np.asarray(play, dtype=np.float32)
    cldfrac = np.asarray(cldfrac, dtype=np.float32)
    hgt = np.asarray(hgt, dtype=np.float32)
    for name, arr in (("play", play), ("cldfrac", cldfrac), ("hgt", hgt)):
        if arr.shape != (ncol, nlay):
            raise ValueError(f"{name} must have shape (ncol, nlay) = "
                             f"({ncol}, {nlay}); got {arr.shape}")
    pmid = (play * _PMID_SCALE).astype(np.float32)
    cldf = cldfrac.copy()
    cldf[cldf < _CLDMIN] = _F32_ZERO
    return pmid, cldf, hgt


def _check_icld(icld: int) -> None:
    if icld == 0:
        raise ValueError(
            "icld=0 (clear sky): the WRF Fortran returns with every McICA "
            "output left undefined; the woof radiation driver must skip "
            "the generator instead of calling it")
    if icld < 0 or icld > 5:
        raise ValueError(
            f"MCICA_SUBCOL: INVALID ICLD {icld} (legal cloud-overlap "
            "settings are 1..5)")


def generate_lw_subcolumns(iplon, ncol, nlay, icld, permuteseed, irng,
                           play, cldfrac, ciwp, clwp, cswp, rei, rel, res,
                           tauc, hgt, idcor, juldat, lat):
    """Port of ``mcica_subcol_lw``; argument names mirror the Fortran.

    ``tauc`` is ``(nbndlw, ncol, nlay)``.  Returns a dict with the Fortran
    output names: ``cldfmcl``, ``ciwpmcl``, ``clwpmcl``, ``cswpmcl``,
    ``taucmcl`` shaped ``(ngptlw, ncol, nlay)`` and ``reicmcl``,
    ``relqmcl``, ``resnmcl`` shaped ``(ncol, nlay)``, all float32.
    """
    del iplon  # unused Fortran dummy
    _check_icld(icld)
    pmid, cldf, hgt = _common_inputs(ncol, nlay, play, cldfrac, hgt)
    tauc = np.asarray(tauc, dtype=np.float32)
    if tauc.shape != (NBNDLW, ncol, nlay):
        raise ValueError(
            f"tauc must have shape (nbndlw, ncol, nlay) = "
            f"({NBNDLW}, {ncol}, {nlay}); got {tauc.shape}")
    decorr = _decorr_len(ncol, idcor, juldat, lat)
    iscloudy = _generate_stochastic_clouds(
        ncol, nlay, NGPTLW, icld, irng, pmid, cldf, hgt, decorr,
        permuteseed)
    return _fill_outputs_lw(iscloudy, ciwp, clwp, cswp, rei, rel, res, tauc)


def generate_sw_subcolumns(iplon, ncol, nlay, icld, permuteseed, irng,
                           play, cldfrac, ciwp, clwp, cswp, rei, rel, res,
                           tauc, ssac, asmc, fsfc, hgt, idcor, juldat, lat):
    """Port of ``mcica_subcol_sw``; argument names mirror the Fortran.

    Band inputs are ``(nbndsw, ncol, nlay)``.  Returns a dict with the
    Fortran output names: ``cldfmcl``, ``ciwpmcl``, ``clwpmcl``,
    ``cswpmcl``, ``taucmcl``, ``ssacmcl``, ``asmcmcl``, ``fsfcmcl`` shaped
    ``(ngptsw, ncol, nlay)`` and ``reicmcl``, ``relqmcl``, ``resnmcl``
    shaped ``(ncol, nlay)``, all float32.
    """
    del iplon  # unused Fortran dummy
    _check_icld(icld)
    pmid, cldf, hgt = _common_inputs(ncol, nlay, play, cldfrac, hgt)
    band_arrays = {}
    for name, arr in (("tauc", tauc), ("ssac", ssac), ("asmc", asmc),
                      ("fsfc", fsfc)):
        arr = np.asarray(arr, dtype=np.float32)
        if arr.shape != (NBNDSW, ncol, nlay):
            raise ValueError(
                f"{name} must have shape (nbndsw, ncol, nlay) = "
                f"({NBNDSW}, {ncol}, {nlay}); got {arr.shape}")
        band_arrays[name] = arr
    decorr = _decorr_len(ncol, idcor, juldat, lat)
    iscloudy = _generate_stochastic_clouds(
        ncol, nlay, NGPTSW, icld, irng, pmid, cldf, hgt, decorr,
        permuteseed)

    ciwp = np.asarray(ciwp, dtype=np.float32)
    clwp = np.asarray(clwp, dtype=np.float32)
    cswp = np.asarray(cswp, dtype=np.float32)
    cloudy = iscloudy
    # n = ngb(isubcol) - (ngb(1) - 1): 1-based SW band index per g-point.
    band_index = _SW_NGB - (_SW_NGB[0] - 1)             # 1..14
    out = {
        "cldfmcl": np.where(cloudy, _F32_ONE, _F32_ZERO).astype(np.float32),
        "ciwpmcl": np.where(cloudy, ciwp[None, :, :], _F32_ZERO).astype(
            np.float32),
        "clwpmcl": np.where(cloudy, clwp[None, :, :], _F32_ZERO).astype(
            np.float32),
        "cswpmcl": np.where(cloudy, cswp[None, :, :], _F32_ZERO).astype(
            np.float32),
        "taucmcl": np.where(cloudy, band_arrays["tauc"][band_index - 1],
                            _F32_ZERO).astype(np.float32),
        "ssacmcl": np.where(cloudy, band_arrays["ssac"][band_index - 1],
                            _F32_ONE).astype(np.float32),
        "asmcmcl": np.where(cloudy, band_arrays["asmc"][band_index - 1],
                            _F32_ZERO).astype(np.float32),
        "fsfcmcl": np.where(cloudy, band_arrays["fsfc"][band_index - 1],
                            _F32_ZERO).astype(np.float32),
        "reicmcl": np.asarray(rei, dtype=np.float32).copy(),
        "relqmcl": np.asarray(rel, dtype=np.float32).copy(),
        "resnmcl": np.asarray(res, dtype=np.float32).copy(),
    }
    return out


def _fill_outputs_lw(iscloudy, ciwp, clwp, cswp, rei, rel, res, tauc):
    ciwp = np.asarray(ciwp, dtype=np.float32)
    clwp = np.asarray(clwp, dtype=np.float32)
    cswp = np.asarray(cswp, dtype=np.float32)
    cloudy = iscloudy
    return {
        "cldfmcl": np.where(cloudy, _F32_ONE, _F32_ZERO).astype(np.float32),
        "ciwpmcl": np.where(cloudy, ciwp[None, :, :], _F32_ZERO).astype(
            np.float32),
        "clwpmcl": np.where(cloudy, clwp[None, :, :], _F32_ZERO).astype(
            np.float32),
        "cswpmcl": np.where(cloudy, cswp[None, :, :], _F32_ZERO).astype(
            np.float32),
        # n = ngb(isubcol): 1-based LW band index per g-point.
        "taucmcl": np.where(cloudy, tauc[_LW_NGB - 1], _F32_ZERO).astype(
            np.float32),
        "reicmcl": np.asarray(rei, dtype=np.float32).copy(),
        "relqmcl": np.asarray(rel, dtype=np.float32).copy(),
        "resnmcl": np.asarray(res, dtype=np.float32).copy(),
    }


# ---------------------------------------------------------------------------
# CUDA device twin -- icld=2 (maximum-random) forecast path.
#
# Kernels: woof/core/kernels/rrtmg_mcica_wrf.cu, compiled through the
# same direct-NVRTC pattern as rrtmg_lw.py Section 10 (cupy.RawModule
# cannot be used: CuPy appends '-ftz=true' AFTER user options, so
# compile_using_nvrtc + cuda.function.Module keeps --ftz=false
# effective, and mcica_gpu_preflight proves subnormal survival plus the
# seed/kissvec chain on the live device every process).  cupy is
# imported lazily; everything above stays importable without a GPU.
#
# gpu_generate_lw_subcolumns / gpu_generate_sw_subcolumns take the same
# logical inputs as the NumPy entries (numpy or cupy float32) and
# return DEVICE (cupy) arrays in the frozen output shapes -- subcolumn
# arrays (ngpt, ncol, nlay), pass-throughs (ncol, nlay) -- which is
# exactly the layout the batched compute engines consume (rrtmg_lw.py
# Section 11 takes mcica arrays as (NGPTLW, ncol, nlay)), so no
# alternate layout or transpose helper is needed.
#
# Only icld=2 is implemented on the device; every other icld raises
# NotImplementedError HOST-SIDE before any upload or launch, and the
# NumPy port above keeps serving icld 1/3/4/5.  hgt, idcor, juldat and
# lat are accepted and shape-checked for signature parity, but cannot
# influence icld=2 output (the decorrelation length only feeds the
# icld=4/5 exponential overlaps), so hgt is never uploaded.
#
# Chunking: columns are processed in ncol_chunk-wide chunks whose only
# transient is the raw CDF slab (mcica_device_vram_bytes); each
# column's seeds and RNG stream depend only on that column's play
# values and permuteseed, so the chunk size is bitwise invisible
# (gated by tests/test_rrtmg_mcica.py).
# ---------------------------------------------------------------------------

MCICA_DEVICE_ICLD = 2

#: Default columns per internal chunk.  The chunk transient is the raw
#: (ngpt, nlay, ncol_chunk) float32 CDF slab: ~679 MiB at the LW width
#: (ngpt=140) and nlay=74 -- under the ~2 GiB budget with margin for
#: deeper grids -- while giving the one-thread-per-column seed/draw
#: kernel 16384 resident threads.
MCICA_DEVICE_COLUMN_CHUNK = 16384

#: Every kernel in the McICA device module (local-frame audit surface).
MCICA_GPU_KERNEL_NAMES = ("rmcw_probe", "rmcw_fill_cdf",
                          "rmcw_walk_mask", "rmcw_fill_outputs", "rmcw_fill_outputs_column")

# Output source kinds -- FROZEN, mirrored by rrtmg_mcica_wrf.cu.
_MCICA_SRC_CONST1 = 0
_MCICA_SRC_PERCOL = 1
_MCICA_SRC_BAND = 2

_MCICA_GPU_THREADS = 128
_MCICA_GPU_MODULE = None
_MCICA_GPU_KERNELS = {}
_MCICA_GPU_PREFLIGHTED = False


def _mcica_gpu_module():
    """Compile kernels/rrtmg_mcica_wrf.cu via NVRTC directly and load
    the PTX (see the section header for why RawModule is unusable).

    ``-arch`` is deliberately absent, for the reason spelled out at
    ``rrtmg_lw._gpu_module``: cupy appends its own and NVRTC 13.0 rejects
    the duplicate, so an explicit ``-arch=compute_{arch}`` made this
    module uncompilable on CUDA 13 while compiling fine on CUDA 12.
    """
    global _MCICA_GPU_MODULE
    if _MCICA_GPU_MODULE is None:
        import os
        import cupy as cp
        from cupy.cuda import compiler as _cc
        path = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                            "kernels", "rrtmg_mcica_wrf.cu")
        with open(path, encoding="utf-8") as fh:
            source = fh.read()
        ptx, _mapping = _cc.compile_using_nvrtc(
            source,
            ("-std=c++17", "--ftz=false"),
            None, "rrtmg_mcica_wrf.cu")
        mod = cp.cuda.function.Module()
        mod.load(ptx.encode() if isinstance(ptx, str) else ptx)
        _MCICA_GPU_MODULE = mod
    return _MCICA_GPU_MODULE


def _mcica_gpu_kernel(name):
    if name not in _MCICA_GPU_KERNELS:
        _MCICA_GPU_KERNELS[name] = _mcica_gpu_module().get_function(name)
    return _MCICA_GPU_KERNELS[name]


def mcica_gpu_preflight(force=False):
    """Prove, on the live device, that FP32 subnormals survive our
    compile options and that the seed-derivation + kissvec chain equals
    the certified NumPy port bitwise on a probe column."""
    global _MCICA_GPU_PREFLIGHTED
    if _MCICA_GPU_PREFLIGHTED and not force:
        return
    import cupy as cp
    probe_play = np.array([1013.2478, 991.7534, 962.4989, 927.0031],
                          dtype=np.float32)
    x = cp.asarray(np.concatenate(
        [np.array([1.0e-30, 1.0e-10], dtype=np.float32), probe_play]))
    out = cp.zeros(3, dtype=cp.float32)
    _mcica_gpu_kernel("rmcw_probe")((1,), (32,), (x, out))
    got = cp.asnumpy(out)
    pmid = (probe_play * _PMID_SCALE).astype(np.float32)[None, :]
    seeds = _make_seeds(pmid, 0)
    want = np.array([np.float32(1.0e-30) * np.float32(1.0e-10),
                     _kissvec(seeds)[0], _kissvec(seeds)[0]],
                    dtype=np.float32)
    if got.view(np.uint32).tolist() != want.view(np.uint32).tolist():
        raise RuntimeError(
            "rrtmg_mcica GPU preflight failed: got %r want %r "
            "(subnormal flush or seed/kissvec divergence on this "
            "toolchain)" % (got, want))
    _MCICA_GPU_PREFLIGHTED = True


def mcica_gpu_local_frame_bytes():
    """CU_FUNC_ATTRIBUTE_LOCAL_SIZE_BYTES for every McICA kernel.

    KF_KMAX lesson: a frame of F bytes reserves ~F x 1536 x 170 bytes
    machine-wide at first launch on the RTX 5090, so frames are audited
    and bounded by tests/test_rrtmg_mcica.py."""
    from cupy.cuda import driver
    out = {}
    for name in MCICA_GPU_KERNEL_NAMES:
        fn = _mcica_gpu_kernel(name)
        out[name] = int(driver.funcGetAttribute(
            driver.CU_FUNC_ATTRIBUTE_LOCAL_SIZE_BYTES, fn.ptr))
    return out


def _mcica_r512(nbytes):
    """Round up to CuPy's 512-byte pool allocation quantum."""
    return (int(nbytes) + 511) & ~511


def mcica_device_vram_bytes(ncol_chunk, nlay, ngpt):
    """Peak transient device bytes of ONE internal chunk of the device
    generators: the raw (ngpt, nlay, ncol_chunk) float32 CDF slab, the
    (ngpt, ncol_chunk, nlay) uint8 iscloudy mask and the descriptor
    tables, rounded to CuPy's 512-byte pool quantum.

    Inputs and the returned output slabs are priced by the caller --
    they scale with the full ncol request, not the chunk (each
    (ngpt, ncol, nlay) float32 output slab costs ngpt*nlay*4 bytes per
    column: 41,440 B/col at the LW width for nlay=74)."""
    cells = int(ngpt) * int(nlay) * int(ncol_chunk)
    return (_mcica_r512(cells * 4)             # CDF slab (f32)
            + _mcica_r512(cells)               # iscloudy mask (u8)
            + _mcica_r512(int(ngpt) * 4)       # bandoff table
            + 2 * _mcica_r512(8 * 8)           # outptrs / srcptrs
            + 2 * _mcica_r512(8 * 4))          # srckind / clearval


def _mcica_dev_f32(cp, arr, shape, name):
    """arr as a C-contiguous float32 device array of the given shape.

    numpy inputs are cast host-side (np.asarray float32) exactly like
    the NumPy entries; cupy float32 inputs never leave the device (a
    f32->f32 copy/cast is pure data movement and bit-preserving)."""
    if isinstance(arr, cp.ndarray):
        out = cp.ascontiguousarray(arr.astype(cp.float32, copy=False))
    else:
        out = cp.asarray(np.ascontiguousarray(
            np.asarray(arr, dtype=np.float32)))
    if out.shape != tuple(shape):
        raise ValueError(f"{name} must have shape {tuple(shape)}; "
                         f"got {out.shape}")
    return out


def _gpu_generate_subcolumns(ncol, nlay, ngpt, icld, permuteseed, irng,
                             play, cldfrac, hgt, percol_srcs, band_srcs,
                             nbnd, band_offsets, out_specs, passthrough,
                             ncol_chunk, stage_probe=None, layout="gpoint"):
    """Shared device driver for both generator sides (see wrappers)."""
    # Fail closed BEFORE any cupy import, upload or launch.
    if int(icld) != MCICA_DEVICE_ICLD:
        raise NotImplementedError(
            f"the device McICA subcolumn path implements only icld=2 "
            f"(maximum-random overlap); got icld={int(icld)}.  Other "
            f"overlap settings stay on the NumPy generators")
    if int(irng) != 0:
        raise NotImplementedError(
            "irng != 0 selects the Mersenne-Twister generator, which "
            "WRF's RRTMG option-4 drivers never use; only kissvec "
            "(irng = 0) is ported")
    if layout not in ("gpoint", "column"):
        raise ValueError("layout must be gpoint or column")
    ncol = int(ncol)
    nlay = int(nlay)
    if nlay < 4:
        raise ValueError("kissvec seeding requires at least four layers")
    chunk = (MCICA_DEVICE_COLUMN_CHUNK if ncol_chunk is None
             else int(ncol_chunk))
    if chunk < 1:
        raise ValueError("ncol_chunk must be >= 1")

    import cupy as cp
    mcica_gpu_preflight()
    play_d = _mcica_dev_f32(cp, play, (ncol, nlay), "play")
    cldf_d = _mcica_dev_f32(cp, cldfrac, (ncol, nlay), "cldfrac")
    # hgt cannot influence icld=2 output; validate the shape only.
    hgt_shape = tuple(hgt.shape if hasattr(hgt, "shape")
                      else np.shape(hgt))
    if hgt_shape != (ncol, nlay):
        raise ValueError(f"hgt must have shape ({ncol}, {nlay}); "
                         f"got {hgt_shape}")
    # The Fortran seed guard, on the same singly rounded pmid = play*100
    # (generate_stochastic_clouds lines 2424-2427 / _make_seeds).
    pm0 = play_d[:, 0] * _PMID_SCALE
    pm1 = play_d[:, 1] * _PMID_SCALE
    if bool((pm0 < pm1).any()):
        raise ValueError(
            "MCICA_SUBCOL: KISSVEC SEED GENERATOR REQUIRES PMID FROM "
            "BOTTOM FOUR LAYERS.")
    del pm0, pm1

    srcs = {}
    for name, arr in percol_srcs.items():
        srcs[name] = _mcica_dev_f32(cp, arr, (ncol, nlay), name)
    for name, arr in band_srcs.items():
        srcs[name] = _mcica_dev_f32(cp, arr, (nbnd, ncol, nlay), name)

    outs = {}
    optrs, sptrs, kinds, clears = [], [], [], []
    for name, kind, src, clear in out_specs:
        o = cp.empty((ngpt, ncol, nlay) if layout == "gpoint" else
                     (ncol, nlay, ngpt), dtype=cp.float32)
        outs[name] = o
        optrs.append(o.data.ptr)
        sptrs.append(0 if src is None else srcs[src].data.ptr)
        kinds.append(kind)
        clears.append(clear)
    nout = len(out_specs)
    outptrs_d = cp.asarray(np.asarray(optrs, dtype=np.uint64))
    srcptrs_d = cp.asarray(np.asarray(sptrs, dtype=np.uint64))
    kinds_d = cp.asarray(np.asarray(kinds, dtype=np.int32))
    clears_d = cp.asarray(np.asarray(clears, dtype=np.float32))
    bandoff_d = cp.asarray(np.ascontiguousarray(
        np.asarray(band_offsets, dtype=np.int32)))

    fill_cdf = _mcica_gpu_kernel("rmcw_fill_cdf")
    walk = _mcica_gpu_kernel("rmcw_walk_mask")
    fill_out = _mcica_gpu_kernel("rmcw_fill_outputs" if layout == "gpoint"
                                 else "rmcw_fill_outputs_column")
    tb = _MCICA_GPU_THREADS
    for col0 in range(0, ncol, chunk):
        nc = min(chunk, ncol - col0)
        cdf_d = cp.empty(ngpt * nlay * nc, dtype=cp.float32)
        mask_d = cp.empty(ngpt * nc * nlay, dtype=cp.uint8)
        fill_cdf(((nc + tb - 1) // tb,), (tb,),
                 (np.int32(col0), np.int32(nc), np.int32(nlay),
                  np.int32(ngpt), np.int32(int(permuteseed)), play_d,
                  cdf_d))
        pairs = ngpt * nc
        walk(((pairs + tb - 1) // tb,), (tb,),
             (np.int32(col0), np.int32(nc), np.int32(nlay),
              np.int32(ngpt), cdf_d, cldf_d, mask_d))
        cells = ngpt * nc * nlay
        fill_out(((cells + tb - 1) // tb,), (tb,),
                 (np.int32(ncol), np.int32(col0), np.int32(nc),
                  np.int32(nlay), np.int32(ngpt), mask_d,
                  np.int32(nout), outptrs_d, srcptrs_d, kinds_d,
                  clears_d, bandoff_d))
        if stage_probe is not None:
            cp.cuda.runtime.deviceSynchronize()
            stage_probe(col0, nc)
        del cdf_d, mask_d

    for name, arr in passthrough.items():
        d = _mcica_dev_f32(cp, arr, (ncol, nlay), name)
        # Mirror the NumPy entries' .copy() when the device array IS the
        # caller's (a caller mutation must not alias the output).
        outs[name] = d.copy() if d is arr else d
    return outs


def gpu_generate_lw_subcolumns(iplon, ncol, nlay, icld, permuteseed,
                               irng, play, cldfrac, ciwp, clwp, cswp,
                               rei, rel, res, tauc, hgt, idcor, juldat,
                               lat, ncol_chunk=None, _stage_probe=None, *,
                               layout="gpoint"):
    """Device twin of :func:`generate_lw_subcolumns` (icld=2 only).

    Same logical arguments (numpy or cupy float32; ``iplon`` unused like
    the Fortran dummy) plus ``ncol_chunk`` to bound the internal chunk
    transient (:func:`mcica_device_vram_bytes`; chunking is bitwise
    invisible).  Returns cupy arrays in the frozen shapes.  ``idcor``,
    ``juldat`` and ``lat`` are accepted for signature parity; they
    cannot influence icld=2 output. ``layout="column"`` returns the five
    g-point slabs as (ncol, nlay, NGPTLW); the default stays unchanged."""
    del iplon, idcor, juldat, lat
    out_specs = (
        ("cldfmcl", _MCICA_SRC_CONST1, None, np.float32(0.0)),
        ("ciwpmcl", _MCICA_SRC_PERCOL, "ciwp", np.float32(0.0)),
        ("clwpmcl", _MCICA_SRC_PERCOL, "clwp", np.float32(0.0)),
        ("cswpmcl", _MCICA_SRC_PERCOL, "cswp", np.float32(0.0)),
        ("taucmcl", _MCICA_SRC_BAND, "tauc", np.float32(0.0)),
    )
    return _gpu_generate_subcolumns(
        ncol, nlay, NGPTLW, icld, permuteseed, irng, play, cldfrac, hgt,
        {"ciwp": ciwp, "clwp": clwp, "cswp": cswp}, {"tauc": tauc},
        NBNDLW, _LW_NGB - 1, out_specs,
        {"reicmcl": rei, "relqmcl": rel, "resnmcl": res},
        ncol_chunk, _stage_probe, layout)


def gpu_generate_sw_subcolumns(iplon, ncol, nlay, icld, permuteseed,
                               irng, play, cldfrac, ciwp, clwp, cswp,
                               rei, rel, res, tauc, ssac, asmc, fsfc,
                               hgt, idcor, juldat, lat, ncol_chunk=None,
                               _stage_probe=None, layout="gpoint"):
    """Device twin of :func:`generate_sw_subcolumns` (icld=2 only).

    See :func:`gpu_generate_lw_subcolumns`; the SW roster adds the
    ``ssac``/``asmc``/``fsfc`` band inputs, with ``ssacmcl``'s clear-sky
    value 1.0 exactly like the NumPy entry. ``layout="column"`` returns
    the eight slabs as (ncol, nlay, NGPTSW)."""
    del iplon, idcor, juldat, lat
    out_specs = (
        ("cldfmcl", _MCICA_SRC_CONST1, None, np.float32(0.0)),
        ("ciwpmcl", _MCICA_SRC_PERCOL, "ciwp", np.float32(0.0)),
        ("clwpmcl", _MCICA_SRC_PERCOL, "clwp", np.float32(0.0)),
        ("cswpmcl", _MCICA_SRC_PERCOL, "cswp", np.float32(0.0)),
        ("taucmcl", _MCICA_SRC_BAND, "tauc", np.float32(0.0)),
        ("ssacmcl", _MCICA_SRC_BAND, "ssac", np.float32(1.0)),
        ("asmcmcl", _MCICA_SRC_BAND, "asmc", np.float32(0.0)),
        ("fsfcmcl", _MCICA_SRC_BAND, "fsfc", np.float32(0.0)),
    )
    # n = ngb(isubcol) - (ngb(1) - 1): 0-based SW band offset per g-point.
    return _gpu_generate_subcolumns(
        ncol, nlay, NGPTSW, icld, permuteseed, irng, play, cldfrac, hgt,
        {"ciwp": ciwp, "clwp": clwp, "cswp": cswp},
        {"tauc": tauc, "ssac": ssac, "asmc": asmc, "fsfc": fsfc},
        NBNDSW, _SW_NGB - _SW_NGB[0], out_specs,
        {"reicmcl": rei, "relqmcl": rel, "resnmcl": res},
        ncol_chunk, _stage_probe, layout)
