"""WRF v4.6.1 Thompson ``mp_physics=8`` state and table contract.

This module is intentionally CPU-only.  It pins the state categories and the
Fortran lookup-table record layout before the CUDA process kernel is admitted.
The numerical authority is NCAR WRF v4.6.1 commit
``d66e442fccc04111067e29274c9f9eaccc3cef28``, specifically
``phys/module_mp_thompson.F``.  Classic Thompson (8) is distinct from the
aerosol-aware (28) and graupel/hail-predicting (38) packages.

WRF generates three large sequential-unformatted files on first
``thompson_init``.  woof packages their validated values later, but this
reader remains the provenance gate: every record marker, shape, dtype, and
trailing byte is checked rather than treating an arbitrary binary blob as a
coefficient set.
"""

from __future__ import annotations

from concurrent.futures import ThreadPoolExecutor
import contextlib
from dataclasses import dataclass
import hashlib
from pathlib import Path
import struct
from types import MappingProxyType
from typing import Mapping

import numpy as np


MP_PHYSICS = 8

# Registry.EM_COMMON:3024.  woof drops WRF's leading q in attribute names.
MASS_SPECIES = ("qv", "qc", "qr", "qi", "qs", "qg")
NUMBER_SPECIES = ("ni", "nr")
TRANSPORTED_SPECIES = MASS_SPECIES + NUMBER_SPECIES
EFFECTIVE_RADIUS_FIELDS = ("effc", "effi", "effs")

# share/module_model_constants.F:62-64, converted from metres to the micron
# convention already used by woof's radiation-facing state.
BACKGROUND_EFFECTIVE_RADIUS_UM = {
    "effc": 2.49,
    "effi": 4.99,
    "effs": 9.99,
}

# Classic mp=8 omits optional qng, so thompson_init selects idx_bg1=5
# (Fortran one-based) and a single graupel-density table dimension.
CLASSIC_GRAUPEL_DENSITY_KG_M3 = 400.0


@dataclass(frozen=True)
class TableRecord:
    """One real(kind=8) array in a WRF sequential-unformatted file."""

    name: str
    shape: tuple[int, ...]

    @property
    def values(self) -> int:
        return int(np.prod(self.shape, dtype=np.int64))

    @property
    def payload_bytes(self) -> int:
        return self.values * np.dtype("<f8").itemsize


# Allocation order and WRITE order are taken directly from
# module_mp_thompson.F:624-648, 4091-4303, 4313-4598, and 4600-4791.
GENERATED_TABLE_FILES: dict[str, tuple[TableRecord, ...]] = {
    "qr_acr_qg_V4.dat": tuple(
        TableRecord(name, (37, 37, 1, 37, 37))
        for name in ("tcg_racg", "tmr_racg", "tcr_gacr",
                     "tnr_racg", "tnr_gacr")
    ),
    "qr_acr_qsV2.dat": tuple(
        TableRecord(name, (37, 9, 37, 37))
        for name in ("tcs_racs1", "tmr_racs1", "tcs_racs2",
                     "tmr_racs2", "tcr_sacr1", "tms_sacr1",
                     "tcr_sacr2", "tms_sacr2", "tnr_racs1",
                     "tnr_racs2", "tnr_sacr1", "tnr_sacr2")
    ),
    "freezeH2O.dat": (
        TableRecord("tpi_qrfz", (37, 37, 45, 55)),
        TableRecord("tni_qrfz", (37, 37, 45, 55)),
        TableRecord("tpg_qrfz", (37, 37, 45, 55)),
        TableRecord("tnr_qrfz", (37, 37, 45, 55)),
        TableRecord("tpi_qcfz", (37, 100, 45, 55)),
        TableRecord("tni_qcfz", (37, 100, 45, 55)),
    ),
}

# Smaller tables are generated by the same official thompson_init call but
# are not included in WRF's three cache files.  The pinned oracle harness
# writes them in this order to a fourth provenance file.
AUXILIARY_TABLE_RECORDS = tuple(
    TableRecord(name, shape) for name, shape in (
        ("tps_iaus", (64, 55)),
        ("tni_iaus", (64, 55)),
        ("tpi_ide", (64, 55)),
        ("t_Efrw", (100, 100)),
        ("t_Efsw", (100, 100)),
        ("tpc_wev", (100, 37, 100)),
        ("tnc_wev", (100, 37, 100)),
    )
)
AUXILIARY_TABLE_FILE = "thompson_aux_tables.dat"


@dataclass(frozen=True)
class TableAsset:
    """Content-addressed canonical coefficient asset."""

    filename: str
    bytes: int
    sha256: str


# Canonical assets generated by the official-source oracle on Ubuntu 24.04.4
# with GNU Fortran 13.3.0.  A runtime using different bytes is a different
# numerical setup even if it came from the same WRF tag, and must not silently
# cross a restart boundary.
CLASSIC_TABLE_ASSETS = (
    TableAsset(
        "qr_acr_qg_V4.dat", 74_966_480,
        "89b779855847b2acdca1b40e24c5f1bd89b0c6ed105ca91a5a076d80c2437c3f"),
    TableAsset(
        "qr_acr_qsV2.dat", 43_764_288,
        "47350be20bd59c9f31378dd5805ce7d35fd14bebcfafb4ade56626f6eed818d7"),
    TableAsset(
        "freezeH2O.dat", 254_944_848,
        "c235d1ce6f8750a671b2273d0e216ed3acf9a869bfd52a14676826f87aab5c02"),
    TableAsset(
        AUXILIARY_TABLE_FILE, 6_164_536,
        "a1bda803cdb53aedce8a2970c04c355fad19e3744398e1c9b13a876f09730547"),
)

WRF_REFERENCE_VERSION = "v4.6.1"
WRF_REFERENCE_COMMIT = "d66e442fccc04111067e29274c9f9eaccc3cef28"
TABLE_SET_ID = "wrf-v4.6.1-classic-thompson-mp8-gfortran13-v1"


# ---------------------------------------------------------------------------
# The operational WRF 3.9 fork's table set (RunConfig.thompson_version =
# "wrf_39_noaa").
# ---------------------------------------------------------------------------
#
# NOAA-EMC/HRRR tag v4.1.21, sorc/hrrr_wrfarw.fd/WRFV3.9/phys/
# module_mp_thompson.F (SHA-256 4d600111...).  Its snow and graupel axes have
# 28 entries starting at 1e-5 kg m-3 and its graupel intercept axis runs
# 1e4..1e7 (:219-221, :271-293), its graupel tables carry no density axis
# and one more record, tmg_gacr (:614-622, write order :3940-3945), and D0s
# is 200 microns (:205), which changes the ice-to-snow and snow-collects-
# cloud tables built from it.  The fork writes its caches under the WRF 3.9
# names.  tools/thompson_fork_oracle/build.sh generates every record from
# the fork's own thompson_init.
FORK_GENERATED_TABLE_FILES: dict[str, tuple[TableRecord, ...]] = {
    "qr_acr_qg.dat": tuple(
        TableRecord(name, (28, 28, 37, 37))
        for name in ("tcg_racg", "tmr_racg", "tcr_gacr", "tmg_gacr",
                     "tnr_racg", "tnr_gacr")
    ),
    "qr_acr_qs.dat": tuple(
        TableRecord(name, (28, 9, 37, 37))
        for name in ("tcs_racs1", "tmr_racs1", "tcs_racs2",
                     "tmr_racs2", "tcr_sacr1", "tms_sacr1",
                     "tcr_sacr2", "tms_sacr2", "tnr_racs1",
                     "tnr_racs2", "tnr_sacr1", "tnr_sacr2")
    ),
    # Same shapes and write order as v4.6.1 (:4393-4398).
    "freezeH2O.dat": GENERATED_TABLE_FILES["freezeH2O.dat"],
}

#: The fork set as tools/thompson_fork_oracle/build.sh generated it on
#: a development machine (GNU Fortran 15.2.0, -O2 -fno-tree-vectorize, no libmvec);
#: receipt tools/thompson_fork_oracle/PROVENANCE-node2.txt.
FORK_TABLE_ASSETS = (
    TableAsset(
        "qr_acr_qg.dat", 51_518_256,
        "8b9b5039ec560748c6261cc9ecbc4366332473a9a1d0666ee5a7f04686abf402"),
    TableAsset(
        "qr_acr_qs.dat", 33_118_944,
        "39b4fd363d440a867cc8c37a22ebf2651c8ffcf54f8c05ab7a6f5e753e630ac0"),
    TableAsset(
        "freezeH2O.dat", 254_944_848,
        "28c12192251969cd79a02e08e3174f26113de51490689f728cfc44af9cf76b2c"),
    TableAsset(
        AUXILIARY_TABLE_FILE, 6_164_536,
        "13d304911e5322fb5bcc2a0639effc20ad5381c59f076ced2386b56f2fb441ae"),
)

FORK_REFERENCE_SOURCE = (
    "NOAA-EMC/HRRR v4.1.21 sorc/hrrr_wrfarw.fd/WRFV3.9/phys/"
    "module_mp_thompson.F "
    "sha256:4d60011188443eb432294f7693beb64bdbc8f812541a15c7800013060c877283")
FORK_TABLE_SET_ID = "wrf-3.9-noaa-fork-thompson-gfortran15-v1"

#: RunConfig.thompson_version -> (generated files, assets, table-set id).
TABLE_SETS_BY_VERSION = {
    "wrf_461": (GENERATED_TABLE_FILES, CLASSIC_TABLE_ASSETS, TABLE_SET_ID),
    "wrf_39_noaa": (FORK_GENERATED_TABLE_FILES, FORK_TABLE_ASSETS,
                    FORK_TABLE_SET_ID),
}


@dataclass(frozen=True)
class ClassicTableSet:
    """Validated immutable host tables plus restart-safe asset identity."""

    root: Path
    arrays: Mapping[str, np.ndarray]
    assets: tuple[TableAsset, ...] = CLASSIC_TABLE_ASSETS

    @property
    def payload_bytes(self) -> int:
        return sum(array.nbytes for array in self.arrays.values())

    @property
    def identity(self) -> dict[str, object]:
        if self.assets == FORK_TABLE_ASSETS:
            return {
                "schema": 1,
                "table_set": FORK_TABLE_SET_ID,
                "wrf_version": "3.9-noaa-fork",
                "wrf_source": FORK_REFERENCE_SOURCE,
                "assets": [
                    {"filename": item.filename, "bytes": item.bytes,
                     "sha256": item.sha256}
                    for item in self.assets
                ],
            }
        return {
            "schema": 1,
            "table_set": TABLE_SET_ID,
            "wrf_version": WRF_REFERENCE_VERSION,
            "wrf_commit": WRF_REFERENCE_COMMIT,
            "assets": [
                {"filename": item.filename, "bytes": item.bytes,
                 "sha256": item.sha256}
                for item in self.assets
            ],
        }

    def to_device(self, backend) -> Mapping[str, object]:
        """Upload exact float64 tables while preserving Fortran index order.

        No float32 table path is admitted here.  It would be a separately
        quantified numerical variant, not a harmless storage optimization.
        """
        return MappingProxyType({
            name: backend.asarray(array, dtype=backend.float64, order="F")
            for name, array in self.arrays.items()
        })


def _sha256_file(path: Path, *, block_bytes: int = 8 * 1024 * 1024) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        while block := stream.read(block_bytes):
            digest.update(block)
    return digest.hexdigest()


def validate_table_assets(
        path: str | Path, assets: tuple[TableAsset, ...] = CLASSIC_TABLE_ASSETS,
        ) -> tuple[TableAsset, ...]:
    """Fail closed on absent, resized, or byte-substituted table assets."""
    root = Path(path)
    for asset in assets:
        current = root / asset.filename
        if not current.is_file():
            raise FileNotFoundError(
                f"missing Thompson table asset {current}")
        actual_bytes = current.stat().st_size
        if actual_bytes != asset.bytes:
            raise ValueError(
                f"Thompson table asset {current} has {actual_bytes} bytes; "
                f"expected {asset.bytes}")
        actual_sha256 = _sha256_file(current)
        if actual_sha256 != asset.sha256:
            raise ValueError(
                f"Thompson table asset {current} SHA-256 {actual_sha256}; "
                f"expected {asset.sha256}")
    return assets


def read_validated_table_asset(path: str | Path, asset: TableAsset) -> bytes:
    """One asset's bytes, read once and held to validate_table_assets' checks.

    The loader parses these immutable bytes in place, where it used to hash
    the file and then read it a second time to parse it.
    """
    current = Path(path) / asset.filename
    if not current.is_file():
        raise FileNotFoundError(
            f"missing Thompson table asset {current}")
    data = current.read_bytes()
    if len(data) != asset.bytes:
        raise ValueError(
            f"Thompson table asset {current} has {len(data)} bytes; "
            f"expected {asset.bytes}")
    actual_sha256 = hashlib.sha256(data).hexdigest()
    if actual_sha256 != asset.sha256:
        raise ValueError(
            f"Thompson table asset {current} SHA-256 {actual_sha256}; "
            f"expected {asset.sha256}")
    return data


class _BufferReader:
    """``read(count)`` over immutable bytes, returning views, never copies."""

    def __init__(self, data: bytes):
        self._view = memoryview(data)
        self._offset = 0

    def read(self, count: int) -> memoryview:
        chunk = self._view[self._offset:self._offset + count]
        self._offset += len(chunk)
        return chunk


def sequential_file_bytes(records: tuple[TableRecord, ...], *,
                          marker_bytes: int = 4) -> int:
    """Exact file size with one leading/trailing marker per record."""
    if marker_bytes not in (4, 8):
        raise ValueError("Fortran record markers must be 4 or 8 bytes")
    return sum(record.payload_bytes + 2 * marker_bytes for record in records)


def read_sequential_records(
        path: str | Path, records: tuple[TableRecord, ...], *,
        marker_bytes: int = 4, byteorder: str = "little",
        data: bytes | None = None,
        ) -> dict[str, np.ndarray]:
    """Read and strictly validate WRF/gfortran sequential records.

    Arrays are returned in native-endian float64 with their documented
    Fortran shapes.  ``order='F'`` is essential: WRF's first index is the
    contiguous dimension, while NumPy otherwise assumes the last one is.

    ``data``, when given, is the file's content already in memory (``path``
    then only names it in messages); its native-endian records come back
    as read-only views of those bytes instead of copies.
    """
    source = Path(path)
    if data is not None and not isinstance(data, bytes):
        raise TypeError("sequential record data must be immutable bytes")
    if marker_bytes not in (4, 8):
        raise ValueError("Fortran record markers must be 4 or 8 bytes")
    if byteorder not in ("little", "big"):
        raise ValueError("byteorder must be 'little' or 'big'")
    marker_format = ("<" if byteorder == "little" else ">") + (
        "i" if marker_bytes == 4 else "q")
    dtype = np.dtype("<f8" if byteorder == "little" else ">f8")
    result: dict[str, np.ndarray] = {}
    opened = (source.open("rb") if data is None
              else contextlib.nullcontext(_BufferReader(data)))
    with opened as stream:
        for record in records:
            head = stream.read(marker_bytes)
            if len(head) != marker_bytes:
                raise ValueError(
                    f"{source}: missing leading marker for {record.name}")
            declared = struct.unpack(marker_format, head)[0]
            if declared != record.payload_bytes:
                raise ValueError(
                    f"{source}: {record.name} marker declares {declared} "
                    f"bytes, expected {record.payload_bytes}")
            payload = stream.read(record.payload_bytes)
            if len(payload) != record.payload_bytes:
                raise ValueError(
                    f"{source}: truncated {record.name} payload "
                    f"({len(payload)} != {record.payload_bytes} bytes)")
            tail = stream.read(marker_bytes)
            if len(tail) != marker_bytes or struct.unpack(
                    marker_format, tail)[0] != declared:
                raise ValueError(
                    f"{source}: mismatched trailing marker for "
                    f"{record.name}")
            values = np.frombuffer(payload, dtype=dtype, count=record.values)
            shaped = values.reshape(record.shape, order="F")
            if data is not None and dtype.isnative:
                result[record.name] = shaped
            else:
                result[record.name] = np.array(
                    shaped, dtype=np.float64, order="F", copy=True)
        extra = stream.read(1)
        if extra:
            raise ValueError(f"{source}: unexpected bytes after final record")
    return result


def read_generated_table_directory(path: str | Path) -> dict[str, np.ndarray]:
    """Read all three classic Thompson WRF-generated cache files."""
    root = Path(path)
    tables: dict[str, np.ndarray] = {}
    for filename, records in GENERATED_TABLE_FILES.items():
        current = read_sequential_records(root / filename, records)
        overlap = tables.keys() & current.keys()
        if overlap:
            raise RuntimeError(f"duplicate Thompson table names: {overlap}")
        tables.update(current)
    return tables


def read_classic_table_directory(path: str | Path) -> dict[str, np.ndarray]:
    """Read the complete classic mp=8 generated coefficient set."""
    root = Path(path)
    tables = read_generated_table_directory(root)
    auxiliary = read_sequential_records(
        root / AUXILIARY_TABLE_FILE, AUXILIARY_TABLE_RECORDS)
    overlap = tables.keys() & auxiliary.keys()
    if overlap:
        raise RuntimeError(f"duplicate Thompson table names: {overlap}")
    tables.update(auxiliary)
    return tables


def load_validated_classic_tables(
        path: str | Path, version: str = "wrf_461") -> ClassicTableSet:
    """Verify canonical bytes, parse every record, and freeze host arrays.

    Each asset is read once, checked against its pinned size and SHA-256 and
    parsed from those same bytes, the four assets on parallel threads (the
    hashing and the finite checks release the GIL).  The records are
    exactly the ones :func:`read_classic_table_directory` returns.

    ``version`` is RunConfig.thompson_version: ``"wrf_461"`` reads the WRF
    v4.6.1 set, ``"wrf_39_noaa"`` the operational WRF 3.9 fork's
    (:data:`FORK_GENERATED_TABLE_FILES`, :data:`FORK_TABLE_ASSETS`).
    """
    root = Path(path).resolve()
    try:
        generated_files, assets, _set_id = TABLE_SETS_BY_VERSION[version]
    except KeyError:
        raise ValueError(
            f"no Thompson table set for thompson_version={version!r}; "
            f"known: {sorted(TABLE_SETS_BY_VERSION)}") from None

    def parse(asset: TableAsset) -> dict[str, np.ndarray]:
        data = read_validated_table_asset(root, asset)
        records = (AUXILIARY_TABLE_RECORDS
                   if asset.filename == AUXILIARY_TABLE_FILE
                   else generated_files[asset.filename])
        current = read_sequential_records(
            root / asset.filename, records, data=data)
        for name, array in current.items():
            if not np.isfinite(array).all():
                raise ValueError(
                    f"Thompson table {name} contains non-finite values")
            array.flags.writeable = False
        return current

    with ThreadPoolExecutor(max_workers=len(assets)) as pool:
        groups = list(pool.map(parse, assets))
    arrays: dict[str, np.ndarray] = {}
    for current in groups:
        overlap = arrays.keys() & current.keys()
        if overlap:
            raise RuntimeError(f"duplicate Thompson table names: {overlap}")
        arrays.update(current)
    frozen = MappingProxyType(dict(arrays))
    result = ClassicTableSet(root=root, arrays=frozen, assets=assets)
    expected_payload = sum(
        record.payload_bytes
        for records in generated_files.values() for record in records
    ) + sum(record.payload_bytes for record in AUXILIARY_TABLE_RECORDS)
    if result.payload_bytes != expected_payload:
        raise RuntimeError(
            f"Thompson payload inventory is {result.payload_bytes} bytes; "
            f"expected {expected_payload}")
    return result


__all__ = [
    "AUXILIARY_TABLE_RECORDS",
    "AUXILIARY_TABLE_FILE",
    "BACKGROUND_EFFECTIVE_RADIUS_UM",
    "CLASSIC_TABLE_ASSETS",
    "CLASSIC_GRAUPEL_DENSITY_KG_M3",
    "ClassicTableSet",
    "EFFECTIVE_RADIUS_FIELDS",
    "FORK_GENERATED_TABLE_FILES",
    "FORK_REFERENCE_SOURCE",
    "FORK_TABLE_ASSETS",
    "FORK_TABLE_SET_ID",
    "GENERATED_TABLE_FILES",
    "MASS_SPECIES",
    "MP_PHYSICS",
    "NUMBER_SPECIES",
    "TRANSPORTED_SPECIES",
    "TABLE_SET_ID",
    "TABLE_SETS_BY_VERSION",
    "TableAsset",
    "TableRecord",
    "WRF_REFERENCE_COMMIT",
    "WRF_REFERENCE_VERSION",
    "load_validated_classic_tables",
    "read_generated_table_directory",
    "read_classic_table_directory",
    "read_sequential_records",
    "read_validated_table_asset",
    "sequential_file_bytes",
    "validate_table_assets",
]
