// New Tiedtke frame probe -- COMPILE ONLY, never launched.
// Not physics.  The declarations and the access pattern of the real port,
// with the arithmetic replaced by dependent FMAs, so ptxas allocates the
// same frame it would for the transcription.
#ifndef NT_KP
#define NT_KP 49
#endif

extern "C" __global__ void nt_skeleton_stack(
    const float* __restrict__ in, float* __restrict__ out, int nz) {
  int i = blockIdx.x * blockDim.x + threadIdx.x;
  size_t base_in = (size_t)i * (size_t)NT_KP;
  float pum1[NT_KP];
  float pvm1[NT_KP];
  float ztt[NT_KP];
  float ptte[NT_KP];
  float pqte[NT_KP];
  float pvom[NT_KP];
  float pvol[NT_KP];
  float pverv[NT_KP];
  float pgeo[NT_KP];
  float zqq[NT_KP];
  float pcte[NT_KP];
  float ztp1[NT_KP];
  float zqp1[NT_KP];
  float ztu[NT_KP];
  float zqu[NT_KP];
  float zlu[NT_KP];
  float zlude[NT_KP];
  float zmfu[NT_KP];
  float zmfd[NT_KP];
  float zqsat[NT_KP];
  float pmfude_rate[NT_KP];
  float pmfdde_rate[NT_KP];
  float zdpmel[NT_KP];
  float zmfuus[NT_KP];
  float zmfdus[NT_KP];
  float zuv2[NT_KP];
  float ztenu[NT_KP];
  float ztenv[NT_KP];
  float ztenh[NT_KP];
  float zqenh[NT_KP];
  float zqsenh[NT_KP];
  float ztd[NT_KP];
  float zqd[NT_KP];
  float zmfus[NT_KP];
  float zmfds[NT_KP];
  float zmfuq[NT_KP];
  float zmfdq[NT_KP];
  float zdmfup[NT_KP];
  float zdmfdp[NT_KP];
  float zmful[NT_KP];
  float zuu[NT_KP];
  float zvu[NT_KP];
  float zud[NT_KP];
  float zvd[NT_KP];
  float zlglac[NT_KP];
  float dh[NT_KP];
  float dhen[NT_KP];
  float kup[NT_KP];
  float vptu[NT_KP];
  float vten[NT_KP];
  float ptu[NT_KP];
  float pqu[NT_KP];
  float plu[NT_KP];
  float zbuo[NT_KP];
  float abuoy[NT_KP];
  float plude[NT_KP];
  float zlrain[NT_KP];
  float zodetr[NT_KP];
  float pdmfen[NT_KP];
  float ztenwb[NT_KP];
  float zqenwb[NT_KP];
  float pdpmel[NT_KP];
  float plglac[NT_KP];
  float zdtdt[NT_KP];
  float zdqdt[NT_KP];
  float zdp[NT_KP];
  float zdudt[NT_KP];
  float zdvdt[NT_KP];
  float zuen[NT_KP];
  float zven[NT_KP];
  float zmfuu[NT_KP];
  float zmfdu[NT_KP];
  float zmfuv[NT_KP];
  float zmfdv[NT_KP];
  float pgeoh[NT_KP + 1];
  float pmflxr[NT_KP + 1];
  float pmflxs[NT_KP + 1];
  int ilab[NT_KP];
  int klab[NT_KP];
  for (int k = 0; k < nz; ++k) {
    pum1[k] = in[base_in + k] * 1.0000f;
    pvm1[k] = in[base_in + k] * 1.0100f;
    ztt[k] = in[base_in + k] * 1.0200f;
    ptte[k] = in[base_in + k] * 1.0300f;
    pqte[k] = in[base_in + k] * 1.0400f;
    pvom[k] = in[base_in + k] * 1.0500f;
    pvol[k] = in[base_in + k] * 1.0600f;
    pverv[k] = in[base_in + k] * 1.0700f;
    pgeo[k] = in[base_in + k] * 1.0800f;
    zqq[k] = in[base_in + k] * 1.0900f;
    pcte[k] = in[base_in + k] * 1.1000f;
    ztp1[k] = in[base_in + k] * 1.1100f;
    zqp1[k] = in[base_in + k] * 1.1200f;
    ztu[k] = in[base_in + k] * 1.1300f;
    zqu[k] = in[base_in + k] * 1.1400f;
    zlu[k] = in[base_in + k] * 1.1500f;
    zlude[k] = in[base_in + k] * 1.1600f;
    zmfu[k] = in[base_in + k] * 1.1700f;
    zmfd[k] = in[base_in + k] * 1.1800f;
    zqsat[k] = in[base_in + k] * 1.1900f;
    pmfude_rate[k] = in[base_in + k] * 1.2000f;
    pmfdde_rate[k] = in[base_in + k] * 1.2100f;
    zdpmel[k] = in[base_in + k] * 1.2200f;
    zmfuus[k] = in[base_in + k] * 1.2300f;
    zmfdus[k] = in[base_in + k] * 1.2400f;
    zuv2[k] = in[base_in + k] * 1.2500f;
    ztenu[k] = in[base_in + k] * 1.2600f;
    ztenv[k] = in[base_in + k] * 1.2700f;
    ztenh[k] = in[base_in + k] * 1.2800f;
    zqenh[k] = in[base_in + k] * 1.2900f;
    zqsenh[k] = in[base_in + k] * 1.3000f;
    ztd[k] = in[base_in + k] * 1.3100f;
    zqd[k] = in[base_in + k] * 1.3200f;
    zmfus[k] = in[base_in + k] * 1.3300f;
    zmfds[k] = in[base_in + k] * 1.3400f;
    zmfuq[k] = in[base_in + k] * 1.3500f;
    zmfdq[k] = in[base_in + k] * 1.3600f;
    zdmfup[k] = in[base_in + k] * 1.3700f;
    zdmfdp[k] = in[base_in + k] * 1.3800f;
    zmful[k] = in[base_in + k] * 1.3900f;
    zuu[k] = in[base_in + k] * 1.4000f;
    zvu[k] = in[base_in + k] * 1.4100f;
    zud[k] = in[base_in + k] * 1.4200f;
    zvd[k] = in[base_in + k] * 1.4300f;
    zlglac[k] = in[base_in + k] * 1.4400f;
    dh[k] = in[base_in + k] * 1.4500f;
    dhen[k] = in[base_in + k] * 1.4600f;
    kup[k] = in[base_in + k] * 1.4700f;
    vptu[k] = in[base_in + k] * 1.4800f;
    vten[k] = in[base_in + k] * 1.4900f;
    ptu[k] = in[base_in + k] * 1.5000f;
    pqu[k] = in[base_in + k] * 1.5100f;
    plu[k] = in[base_in + k] * 1.5200f;
    zbuo[k] = in[base_in + k] * 1.5300f;
    abuoy[k] = in[base_in + k] * 1.5400f;
    plude[k] = in[base_in + k] * 1.5500f;
    zlrain[k] = in[base_in + k] * 1.5600f;
    zodetr[k] = in[base_in + k] * 1.5700f;
    pdmfen[k] = in[base_in + k] * 1.5800f;
    ztenwb[k] = in[base_in + k] * 1.5900f;
    zqenwb[k] = in[base_in + k] * 1.6000f;
    pdpmel[k] = in[base_in + k] * 1.6100f;
    plglac[k] = in[base_in + k] * 1.6200f;
    zdtdt[k] = in[base_in + k] * 1.6300f;
    zdqdt[k] = in[base_in + k] * 1.6400f;
    zdp[k] = in[base_in + k] * 1.6500f;
    zdudt[k] = in[base_in + k] * 1.6600f;
    zdvdt[k] = in[base_in + k] * 1.6700f;
    zuen[k] = in[base_in + k] * 1.6800f;
    zven[k] = in[base_in + k] * 1.6900f;
    zmfuu[k] = in[base_in + k] * 1.7000f;
    zmfdu[k] = in[base_in + k] * 1.7100f;
    zmfuv[k] = in[base_in + k] * 1.7200f;
    zmfdv[k] = in[base_in + k] * 1.7300f;
    pgeoh[k] = in[base_in + k] * 1.7400f;
    pmflxr[k] = in[base_in + k] * 1.7500f;
    pmflxs[k] = in[base_in + k] * 1.7600f;
    ilab[k] = k + 0;
    klab[k] = k + 1;
  }
  for (int k = 1; k < nz; ++k) {
    pum1[k] = __fmaf_rn(pum1[k-1], 0.5f, pvm1[k]);
    pvm1[k] = __fmaf_rn(pvm1[k-1], 0.5f, ztt[k]);
    ztt[k] = __fmaf_rn(ztt[k-1], 0.5f, ptte[k]);
    ptte[k] = __fmaf_rn(ptte[k-1], 0.5f, pqte[k]);
    pqte[k] = __fmaf_rn(pqte[k-1], 0.5f, pvom[k]);
    pvom[k] = __fmaf_rn(pvom[k-1], 0.5f, pvol[k]);
    pvol[k] = __fmaf_rn(pvol[k-1], 0.5f, pverv[k]);
    pverv[k] = __fmaf_rn(pverv[k-1], 0.5f, pgeo[k]);
    pgeo[k] = __fmaf_rn(pgeo[k-1], 0.5f, zqq[k]);
    zqq[k] = __fmaf_rn(zqq[k-1], 0.5f, pcte[k]);
    pcte[k] = __fmaf_rn(pcte[k-1], 0.5f, ztp1[k]);
    ztp1[k] = __fmaf_rn(ztp1[k-1], 0.5f, zqp1[k]);
    zqp1[k] = __fmaf_rn(zqp1[k-1], 0.5f, ztu[k]);
    ztu[k] = __fmaf_rn(ztu[k-1], 0.5f, zqu[k]);
    zqu[k] = __fmaf_rn(zqu[k-1], 0.5f, zlu[k]);
    zlu[k] = __fmaf_rn(zlu[k-1], 0.5f, zlude[k]);
    zlude[k] = __fmaf_rn(zlude[k-1], 0.5f, zmfu[k]);
    zmfu[k] = __fmaf_rn(zmfu[k-1], 0.5f, zmfd[k]);
    zmfd[k] = __fmaf_rn(zmfd[k-1], 0.5f, zqsat[k]);
    zqsat[k] = __fmaf_rn(zqsat[k-1], 0.5f, pmfude_rate[k]);
    pmfude_rate[k] = __fmaf_rn(pmfude_rate[k-1], 0.5f, pmfdde_rate[k]);
    pmfdde_rate[k] = __fmaf_rn(pmfdde_rate[k-1], 0.5f, zdpmel[k]);
    zdpmel[k] = __fmaf_rn(zdpmel[k-1], 0.5f, zmfuus[k]);
    zmfuus[k] = __fmaf_rn(zmfuus[k-1], 0.5f, zmfdus[k]);
    zmfdus[k] = __fmaf_rn(zmfdus[k-1], 0.5f, zuv2[k]);
    zuv2[k] = __fmaf_rn(zuv2[k-1], 0.5f, ztenu[k]);
    ztenu[k] = __fmaf_rn(ztenu[k-1], 0.5f, ztenv[k]);
    ztenv[k] = __fmaf_rn(ztenv[k-1], 0.5f, ztenh[k]);
    ztenh[k] = __fmaf_rn(ztenh[k-1], 0.5f, zqenh[k]);
    zqenh[k] = __fmaf_rn(zqenh[k-1], 0.5f, zqsenh[k]);
    zqsenh[k] = __fmaf_rn(zqsenh[k-1], 0.5f, ztd[k]);
    ztd[k] = __fmaf_rn(ztd[k-1], 0.5f, zqd[k]);
    zqd[k] = __fmaf_rn(zqd[k-1], 0.5f, zmfus[k]);
    zmfus[k] = __fmaf_rn(zmfus[k-1], 0.5f, zmfds[k]);
    zmfds[k] = __fmaf_rn(zmfds[k-1], 0.5f, zmfuq[k]);
    zmfuq[k] = __fmaf_rn(zmfuq[k-1], 0.5f, zmfdq[k]);
    zmfdq[k] = __fmaf_rn(zmfdq[k-1], 0.5f, zdmfup[k]);
    zdmfup[k] = __fmaf_rn(zdmfup[k-1], 0.5f, zdmfdp[k]);
    zdmfdp[k] = __fmaf_rn(zdmfdp[k-1], 0.5f, zmful[k]);
    zmful[k] = __fmaf_rn(zmful[k-1], 0.5f, zuu[k]);
    zuu[k] = __fmaf_rn(zuu[k-1], 0.5f, zvu[k]);
    zvu[k] = __fmaf_rn(zvu[k-1], 0.5f, zud[k]);
    zud[k] = __fmaf_rn(zud[k-1], 0.5f, zvd[k]);
    zvd[k] = __fmaf_rn(zvd[k-1], 0.5f, zlglac[k]);
    zlglac[k] = __fmaf_rn(zlglac[k-1], 0.5f, dh[k]);
    dh[k] = __fmaf_rn(dh[k-1], 0.5f, dhen[k]);
    dhen[k] = __fmaf_rn(dhen[k-1], 0.5f, kup[k]);
    kup[k] = __fmaf_rn(kup[k-1], 0.5f, vptu[k]);
    vptu[k] = __fmaf_rn(vptu[k-1], 0.5f, vten[k]);
    vten[k] = __fmaf_rn(vten[k-1], 0.5f, ptu[k]);
    ptu[k] = __fmaf_rn(ptu[k-1], 0.5f, pqu[k]);
    pqu[k] = __fmaf_rn(pqu[k-1], 0.5f, plu[k]);
    plu[k] = __fmaf_rn(plu[k-1], 0.5f, zbuo[k]);
    zbuo[k] = __fmaf_rn(zbuo[k-1], 0.5f, abuoy[k]);
    abuoy[k] = __fmaf_rn(abuoy[k-1], 0.5f, plude[k]);
    plude[k] = __fmaf_rn(plude[k-1], 0.5f, zlrain[k]);
    zlrain[k] = __fmaf_rn(zlrain[k-1], 0.5f, zodetr[k]);
    zodetr[k] = __fmaf_rn(zodetr[k-1], 0.5f, pdmfen[k]);
    pdmfen[k] = __fmaf_rn(pdmfen[k-1], 0.5f, ztenwb[k]);
    ztenwb[k] = __fmaf_rn(ztenwb[k-1], 0.5f, zqenwb[k]);
    zqenwb[k] = __fmaf_rn(zqenwb[k-1], 0.5f, pdpmel[k]);
    pdpmel[k] = __fmaf_rn(pdpmel[k-1], 0.5f, plglac[k]);
    plglac[k] = __fmaf_rn(plglac[k-1], 0.5f, zdtdt[k]);
    zdtdt[k] = __fmaf_rn(zdtdt[k-1], 0.5f, zdqdt[k]);
    zdqdt[k] = __fmaf_rn(zdqdt[k-1], 0.5f, zdp[k]);
    zdp[k] = __fmaf_rn(zdp[k-1], 0.5f, zdudt[k]);
    zdudt[k] = __fmaf_rn(zdudt[k-1], 0.5f, zdvdt[k]);
    zdvdt[k] = __fmaf_rn(zdvdt[k-1], 0.5f, zuen[k]);
    zuen[k] = __fmaf_rn(zuen[k-1], 0.5f, zven[k]);
    zven[k] = __fmaf_rn(zven[k-1], 0.5f, zmfuu[k]);
    zmfuu[k] = __fmaf_rn(zmfuu[k-1], 0.5f, zmfdu[k]);
    zmfdu[k] = __fmaf_rn(zmfdu[k-1], 0.5f, zmfuv[k]);
    zmfuv[k] = __fmaf_rn(zmfuv[k-1], 0.5f, zmfdv[k]);
    zmfdv[k] = __fmaf_rn(zmfdv[k-1], 0.5f, pgeoh[k]);
    pgeoh[k] = __fmaf_rn(pgeoh[k-1], 0.5f, pmflxr[k]);
    pmflxr[k] = __fmaf_rn(pmflxr[k-1], 0.5f, pmflxs[k]);
    pmflxs[k] = __fmaf_rn(pmflxs[k-1], 0.5f, pum1[k]);
  }
  for (int k = nz - 2; k >= 0; --k) {
    int g = ilab[k] + klab[k];
    pum1[k] = (g & 1) ? __fmaf_rn(pum1[k+1], 0.25f, pvm1[k]) : pum1[k];
    pvm1[k] = (g & 1) ? __fmaf_rn(pvm1[k+1], 0.25f, ztt[k]) : pvm1[k];
    ztt[k] = (g & 1) ? __fmaf_rn(ztt[k+1], 0.25f, ptte[k]) : ztt[k];
    ptte[k] = (g & 1) ? __fmaf_rn(ptte[k+1], 0.25f, pqte[k]) : ptte[k];
    pqte[k] = (g & 1) ? __fmaf_rn(pqte[k+1], 0.25f, pvom[k]) : pqte[k];
    pvom[k] = (g & 1) ? __fmaf_rn(pvom[k+1], 0.25f, pvol[k]) : pvom[k];
    pvol[k] = (g & 1) ? __fmaf_rn(pvol[k+1], 0.25f, pverv[k]) : pvol[k];
    pverv[k] = (g & 1) ? __fmaf_rn(pverv[k+1], 0.25f, pgeo[k]) : pverv[k];
    pgeo[k] = (g & 1) ? __fmaf_rn(pgeo[k+1], 0.25f, zqq[k]) : pgeo[k];
    zqq[k] = (g & 1) ? __fmaf_rn(zqq[k+1], 0.25f, pcte[k]) : zqq[k];
    pcte[k] = (g & 1) ? __fmaf_rn(pcte[k+1], 0.25f, ztp1[k]) : pcte[k];
    ztp1[k] = (g & 1) ? __fmaf_rn(ztp1[k+1], 0.25f, zqp1[k]) : ztp1[k];
    zqp1[k] = (g & 1) ? __fmaf_rn(zqp1[k+1], 0.25f, ztu[k]) : zqp1[k];
    ztu[k] = (g & 1) ? __fmaf_rn(ztu[k+1], 0.25f, zqu[k]) : ztu[k];
    zqu[k] = (g & 1) ? __fmaf_rn(zqu[k+1], 0.25f, zlu[k]) : zqu[k];
    zlu[k] = (g & 1) ? __fmaf_rn(zlu[k+1], 0.25f, zlude[k]) : zlu[k];
    zlude[k] = (g & 1) ? __fmaf_rn(zlude[k+1], 0.25f, zmfu[k]) : zlude[k];
    zmfu[k] = (g & 1) ? __fmaf_rn(zmfu[k+1], 0.25f, zmfd[k]) : zmfu[k];
    zmfd[k] = (g & 1) ? __fmaf_rn(zmfd[k+1], 0.25f, zqsat[k]) : zmfd[k];
    zqsat[k] = (g & 1) ? __fmaf_rn(zqsat[k+1], 0.25f, pmfude_rate[k]) : zqsat[k];
    pmfude_rate[k] = (g & 1) ? __fmaf_rn(pmfude_rate[k+1], 0.25f, pmfdde_rate[k]) : pmfude_rate[k];
    pmfdde_rate[k] = (g & 1) ? __fmaf_rn(pmfdde_rate[k+1], 0.25f, zdpmel[k]) : pmfdde_rate[k];
    zdpmel[k] = (g & 1) ? __fmaf_rn(zdpmel[k+1], 0.25f, zmfuus[k]) : zdpmel[k];
    zmfuus[k] = (g & 1) ? __fmaf_rn(zmfuus[k+1], 0.25f, zmfdus[k]) : zmfuus[k];
    zmfdus[k] = (g & 1) ? __fmaf_rn(zmfdus[k+1], 0.25f, zuv2[k]) : zmfdus[k];
    zuv2[k] = (g & 1) ? __fmaf_rn(zuv2[k+1], 0.25f, ztenu[k]) : zuv2[k];
    ztenu[k] = (g & 1) ? __fmaf_rn(ztenu[k+1], 0.25f, ztenv[k]) : ztenu[k];
    ztenv[k] = (g & 1) ? __fmaf_rn(ztenv[k+1], 0.25f, ztenh[k]) : ztenv[k];
    ztenh[k] = (g & 1) ? __fmaf_rn(ztenh[k+1], 0.25f, zqenh[k]) : ztenh[k];
    zqenh[k] = (g & 1) ? __fmaf_rn(zqenh[k+1], 0.25f, zqsenh[k]) : zqenh[k];
    zqsenh[k] = (g & 1) ? __fmaf_rn(zqsenh[k+1], 0.25f, ztd[k]) : zqsenh[k];
    ztd[k] = (g & 1) ? __fmaf_rn(ztd[k+1], 0.25f, zqd[k]) : ztd[k];
    zqd[k] = (g & 1) ? __fmaf_rn(zqd[k+1], 0.25f, zmfus[k]) : zqd[k];
    zmfus[k] = (g & 1) ? __fmaf_rn(zmfus[k+1], 0.25f, zmfds[k]) : zmfus[k];
    zmfds[k] = (g & 1) ? __fmaf_rn(zmfds[k+1], 0.25f, zmfuq[k]) : zmfds[k];
    zmfuq[k] = (g & 1) ? __fmaf_rn(zmfuq[k+1], 0.25f, zmfdq[k]) : zmfuq[k];
    zmfdq[k] = (g & 1) ? __fmaf_rn(zmfdq[k+1], 0.25f, zdmfup[k]) : zmfdq[k];
    zdmfup[k] = (g & 1) ? __fmaf_rn(zdmfup[k+1], 0.25f, zdmfdp[k]) : zdmfup[k];
    zdmfdp[k] = (g & 1) ? __fmaf_rn(zdmfdp[k+1], 0.25f, zmful[k]) : zdmfdp[k];
    zmful[k] = (g & 1) ? __fmaf_rn(zmful[k+1], 0.25f, zuu[k]) : zmful[k];
    zuu[k] = (g & 1) ? __fmaf_rn(zuu[k+1], 0.25f, zvu[k]) : zuu[k];
    zvu[k] = (g & 1) ? __fmaf_rn(zvu[k+1], 0.25f, zud[k]) : zvu[k];
    zud[k] = (g & 1) ? __fmaf_rn(zud[k+1], 0.25f, zvd[k]) : zud[k];
    zvd[k] = (g & 1) ? __fmaf_rn(zvd[k+1], 0.25f, zlglac[k]) : zvd[k];
    zlglac[k] = (g & 1) ? __fmaf_rn(zlglac[k+1], 0.25f, dh[k]) : zlglac[k];
    dh[k] = (g & 1) ? __fmaf_rn(dh[k+1], 0.25f, dhen[k]) : dh[k];
    dhen[k] = (g & 1) ? __fmaf_rn(dhen[k+1], 0.25f, kup[k]) : dhen[k];
    kup[k] = (g & 1) ? __fmaf_rn(kup[k+1], 0.25f, vptu[k]) : kup[k];
    vptu[k] = (g & 1) ? __fmaf_rn(vptu[k+1], 0.25f, vten[k]) : vptu[k];
    vten[k] = (g & 1) ? __fmaf_rn(vten[k+1], 0.25f, ptu[k]) : vten[k];
    ptu[k] = (g & 1) ? __fmaf_rn(ptu[k+1], 0.25f, pqu[k]) : ptu[k];
    pqu[k] = (g & 1) ? __fmaf_rn(pqu[k+1], 0.25f, plu[k]) : pqu[k];
    plu[k] = (g & 1) ? __fmaf_rn(plu[k+1], 0.25f, zbuo[k]) : plu[k];
    zbuo[k] = (g & 1) ? __fmaf_rn(zbuo[k+1], 0.25f, abuoy[k]) : zbuo[k];
    abuoy[k] = (g & 1) ? __fmaf_rn(abuoy[k+1], 0.25f, plude[k]) : abuoy[k];
    plude[k] = (g & 1) ? __fmaf_rn(plude[k+1], 0.25f, zlrain[k]) : plude[k];
    zlrain[k] = (g & 1) ? __fmaf_rn(zlrain[k+1], 0.25f, zodetr[k]) : zlrain[k];
    zodetr[k] = (g & 1) ? __fmaf_rn(zodetr[k+1], 0.25f, pdmfen[k]) : zodetr[k];
    pdmfen[k] = (g & 1) ? __fmaf_rn(pdmfen[k+1], 0.25f, ztenwb[k]) : pdmfen[k];
    ztenwb[k] = (g & 1) ? __fmaf_rn(ztenwb[k+1], 0.25f, zqenwb[k]) : ztenwb[k];
    zqenwb[k] = (g & 1) ? __fmaf_rn(zqenwb[k+1], 0.25f, pdpmel[k]) : zqenwb[k];
    pdpmel[k] = (g & 1) ? __fmaf_rn(pdpmel[k+1], 0.25f, plglac[k]) : pdpmel[k];
    plglac[k] = (g & 1) ? __fmaf_rn(plglac[k+1], 0.25f, zdtdt[k]) : plglac[k];
    zdtdt[k] = (g & 1) ? __fmaf_rn(zdtdt[k+1], 0.25f, zdqdt[k]) : zdtdt[k];
    zdqdt[k] = (g & 1) ? __fmaf_rn(zdqdt[k+1], 0.25f, zdp[k]) : zdqdt[k];
    zdp[k] = (g & 1) ? __fmaf_rn(zdp[k+1], 0.25f, zdudt[k]) : zdp[k];
    zdudt[k] = (g & 1) ? __fmaf_rn(zdudt[k+1], 0.25f, zdvdt[k]) : zdudt[k];
    zdvdt[k] = (g & 1) ? __fmaf_rn(zdvdt[k+1], 0.25f, zuen[k]) : zdvdt[k];
    zuen[k] = (g & 1) ? __fmaf_rn(zuen[k+1], 0.25f, zven[k]) : zuen[k];
    zven[k] = (g & 1) ? __fmaf_rn(zven[k+1], 0.25f, zmfuu[k]) : zven[k];
    zmfuu[k] = (g & 1) ? __fmaf_rn(zmfuu[k+1], 0.25f, zmfdu[k]) : zmfuu[k];
    zmfdu[k] = (g & 1) ? __fmaf_rn(zmfdu[k+1], 0.25f, zmfuv[k]) : zmfdu[k];
    zmfuv[k] = (g & 1) ? __fmaf_rn(zmfuv[k+1], 0.25f, zmfdv[k]) : zmfuv[k];
    zmfdv[k] = (g & 1) ? __fmaf_rn(zmfdv[k+1], 0.25f, pgeoh[k]) : zmfdv[k];
    pgeoh[k] = (g & 1) ? __fmaf_rn(pgeoh[k+1], 0.25f, pmflxr[k]) : pgeoh[k];
    pmflxr[k] = (g & 1) ? __fmaf_rn(pmflxr[k+1], 0.25f, pmflxs[k]) : pmflxr[k];
    pmflxs[k] = (g & 1) ? __fmaf_rn(pmflxs[k+1], 0.25f, pum1[k]) : pmflxs[k];
  }
  float acc = 0.0f;
  for (int k = 0; k < nz; ++k) {
    acc = __fadd_rn(acc, pum1[k]);
    acc = __fadd_rn(acc, pvm1[k]);
    acc = __fadd_rn(acc, ztt[k]);
    acc = __fadd_rn(acc, ptte[k]);
    acc = __fadd_rn(acc, pqte[k]);
    acc = __fadd_rn(acc, pvom[k]);
    acc = __fadd_rn(acc, pvol[k]);
    acc = __fadd_rn(acc, pverv[k]);
    acc = __fadd_rn(acc, pgeo[k]);
    acc = __fadd_rn(acc, zqq[k]);
    acc = __fadd_rn(acc, pcte[k]);
    acc = __fadd_rn(acc, ztp1[k]);
    acc = __fadd_rn(acc, zqp1[k]);
    acc = __fadd_rn(acc, ztu[k]);
    acc = __fadd_rn(acc, zqu[k]);
    acc = __fadd_rn(acc, zlu[k]);
    acc = __fadd_rn(acc, zlude[k]);
    acc = __fadd_rn(acc, zmfu[k]);
    acc = __fadd_rn(acc, zmfd[k]);
    acc = __fadd_rn(acc, zqsat[k]);
    acc = __fadd_rn(acc, pmfude_rate[k]);
    acc = __fadd_rn(acc, pmfdde_rate[k]);
    acc = __fadd_rn(acc, zdpmel[k]);
    acc = __fadd_rn(acc, zmfuus[k]);
    acc = __fadd_rn(acc, zmfdus[k]);
    acc = __fadd_rn(acc, zuv2[k]);
    acc = __fadd_rn(acc, ztenu[k]);
    acc = __fadd_rn(acc, ztenv[k]);
    acc = __fadd_rn(acc, ztenh[k]);
    acc = __fadd_rn(acc, zqenh[k]);
    acc = __fadd_rn(acc, zqsenh[k]);
    acc = __fadd_rn(acc, ztd[k]);
    acc = __fadd_rn(acc, zqd[k]);
    acc = __fadd_rn(acc, zmfus[k]);
    acc = __fadd_rn(acc, zmfds[k]);
    acc = __fadd_rn(acc, zmfuq[k]);
    acc = __fadd_rn(acc, zmfdq[k]);
    acc = __fadd_rn(acc, zdmfup[k]);
    acc = __fadd_rn(acc, zdmfdp[k]);
    acc = __fadd_rn(acc, zmful[k]);
    acc = __fadd_rn(acc, zuu[k]);
    acc = __fadd_rn(acc, zvu[k]);
    acc = __fadd_rn(acc, zud[k]);
    acc = __fadd_rn(acc, zvd[k]);
    acc = __fadd_rn(acc, zlglac[k]);
    acc = __fadd_rn(acc, dh[k]);
    acc = __fadd_rn(acc, dhen[k]);
    acc = __fadd_rn(acc, kup[k]);
    acc = __fadd_rn(acc, vptu[k]);
    acc = __fadd_rn(acc, vten[k]);
    acc = __fadd_rn(acc, ptu[k]);
    acc = __fadd_rn(acc, pqu[k]);
    acc = __fadd_rn(acc, plu[k]);
    acc = __fadd_rn(acc, zbuo[k]);
    acc = __fadd_rn(acc, abuoy[k]);
    acc = __fadd_rn(acc, plude[k]);
    acc = __fadd_rn(acc, zlrain[k]);
    acc = __fadd_rn(acc, zodetr[k]);
    acc = __fadd_rn(acc, pdmfen[k]);
    acc = __fadd_rn(acc, ztenwb[k]);
    acc = __fadd_rn(acc, zqenwb[k]);
    acc = __fadd_rn(acc, pdpmel[k]);
    acc = __fadd_rn(acc, plglac[k]);
    acc = __fadd_rn(acc, zdtdt[k]);
    acc = __fadd_rn(acc, zdqdt[k]);
    acc = __fadd_rn(acc, zdp[k]);
    acc = __fadd_rn(acc, zdudt[k]);
    acc = __fadd_rn(acc, zdvdt[k]);
    acc = __fadd_rn(acc, zuen[k]);
    acc = __fadd_rn(acc, zven[k]);
    acc = __fadd_rn(acc, zmfuu[k]);
    acc = __fadd_rn(acc, zmfdu[k]);
    acc = __fadd_rn(acc, zmfuv[k]);
    acc = __fadd_rn(acc, zmfdv[k]);
    acc = __fadd_rn(acc, pgeoh[k]);
    acc = __fadd_rn(acc, pmflxr[k]);
    acc = __fadd_rn(acc, pmflxs[k]);
  }
  out[i] = acc;
}
