#!/usr/bin/env bash
# Standalone WRF v4.6.1 updraft-helicity oracle build.
#
# Authority: SUBROUTINE cal_helicity (dyn_em/module_diffusion_em.F:7132-7579)
# plus the metric prep it consumes, SUBROUTINE compute_diff_metrics
# (module_diffusion_em.F:6882-7130).  Driver wiring in WRF v4.6.1:
#   - dyn_em/module_first_rk_step_part2.F:533-556 -- called EVERY step when
#     config_flags%nwp_diagnostics == 1, on the step's start-of-step state
#     (u_2/v_2/w_2/ph_2), after compute_diff_metrics refreshed zx/zy/rdzw
#     under diff_opt 1/2 (:419-434).
#   - Registry.EM_COMMON:2083 -- UP_HELI_MAX, IO "rh02" (restart + history),
#     "MAX UPDRAFT HELICITY", "m2 s-2"; :2210 nwp_diagnostics
#     (&time_control, default 0); :3272 package nwp_output.
#   - phys/module_diag_nwp.F:246-249,269 -- fixed-dt reset of up_heli_max to
#     zero on the FIRST step after each history write
#     (MOD(itimestep-1, history_interval*60/dt) == 0).
#
# NOTE on the task's authority naming: WRF v4.6.1 has no `calc_uh` in
# phys/module_diag_functions.F -- that name is wrf-python's post-processing
# routine (DCALCUH).  The model field UP_HELI_MAX is produced by
# cal_helicity above, which is what this oracle pins.
#
# Extraction: both subroutines are taken VERBATIM from the pinned git BLOB
# (never the working tree, which carries CRLF from the Windows checkout) and
# wrapped in a module that supplies only what their bodies reference from
# host scope: `g` (share/module_model_constants.F:17, g = 9.81) and a
# grid_config_rec_type carrying the eight BC flags they read.  The physics
# statements themselves are byte-identical to the authority; SHA-256 of the
# blob and of each extracted region are recorded beside the fixtures.
#
# Both subroutines are pure arithmetic (+,-,*,/ and comparisons; no libm
# calls), compiled at -O0 with the libmvec guard + positive control kept
# from the ysu oracle pattern so the no-vector-math claim is checked, not
# assumed.
#
# usage: build.sh WRF_SOURCE_ROOT BUILD_DIR   (run under WSL Ubuntu-24.04)
set -euo pipefail

if [[ $# -ne 2 ]]; then
    echo "usage: build.sh WRF_SOURCE_ROOT BUILD_DIR" >&2
    exit 2
fi

source_root=$(realpath "$1")
build_dir=$(realpath -m "$2")
script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
pinned_commit="d66e442fccc04111067e29274c9f9eaccc3cef28"
pinned_blob_sha256="a7d4570c97e51c635e86a0dbd628c6846457ac5b93d5a7af798b118c7d8d2d54"

# --- byte identity to the pinned commit -------------------------------------
head_commit=$(git -C "${source_root}" rev-parse HEAD)
if [[ "${head_commit}" != "${pinned_commit}" ]]; then
    echo "WRF tree is at ${head_commit}, not the pinned ${pinned_commit}" >&2
    exit 3
fi
mkdir -p "${build_dir}"
cd "${build_dir}"

# The Windows checkout holds this file with CRLF endings; `git diff` is not
# line-ending-safe across that boundary.  Take the pinned BLOB itself and
# verify it byte-for-byte, then require the working tree to be exactly the
# blob modulo trailing CR (so a real edit cannot hide behind line endings).
git -C "${source_root}" show \
    "${pinned_commit}:dyn_em/module_diffusion_em.F" \
    > module_diffusion_em.pinned.F
blob_sha=$(sha256sum module_diffusion_em.pinned.F | cut -d' ' -f1)
if [[ "${blob_sha}" != "${pinned_blob_sha256}" ]]; then
    echo "pinned blob sha256 ${blob_sha} != ${pinned_blob_sha256}" >&2
    exit 3
fi
if ! cmp -s <(sed 's/\r$//' "${source_root}/dyn_em/module_diffusion_em.F") \
            module_diffusion_em.pinned.F; then
    echo "working-tree dyn_em/module_diffusion_em.F differs from the pinned" \
         "blob beyond CRLF" >&2
    exit 3
fi

# --- verbatim extraction from the pinned blob --------------------------------
sed -n '/^    SUBROUTINE compute_diff_metrics(/,/^    END SUBROUTINE compute_diff_metrics/p' \
    module_diffusion_em.pinned.F > extract_compute_diff_metrics.f90
sed -n '/^    SUBROUTINE cal_helicity /,/^    END SUBROUTINE cal_helicity/p' \
    module_diffusion_em.pinned.F > extract_cal_helicity.f90
# Guard the patterns: exactly the authority line ranges (7132-7579 is 448
# lines; 6882-7130 is 249).
lines_cdm=$(wc -l < extract_compute_diff_metrics.f90)
lines_ch=$(wc -l < extract_cal_helicity.f90)
if [[ "${lines_cdm}" != 249 || "${lines_ch}" != 448 ]]; then
    echo "extraction drifted: compute_diff_metrics ${lines_cdm} lines" \
         "(want 249), cal_helicity ${lines_ch} lines (want 448)" >&2
    exit 3
fi

cat > uh_oracle_mod.F90 <<'EOF'
! Generated by build.sh: WRF v4.6.1 cal_helicity + compute_diff_metrics,
! extracted VERBATIM from the pinned blob of dyn_em/module_diffusion_em.F
! (regions appended below unchanged).  This wrapper supplies only the two
! host-scope symbols the bodies reference:
!   g                      share/module_model_constants.F:17 (9.81)
!   grid_config_rec_type   the eight BC flags the bodies read
!                          (frame_module_configure derived type member subset)
MODULE uh_oracle_mod
  IMPLICIT NONE
  REAL, PARAMETER :: g = 9.81
  TYPE grid_config_rec_type
    LOGICAL :: open_xs = .FALSE., open_xe = .FALSE.
    LOGICAL :: open_ys = .FALSE., open_ye = .FALSE.
    LOGICAL :: specified = .FALSE., nested = .FALSE.
    LOGICAL :: periodic_x = .FALSE., periodic_y = .FALSE.
  END TYPE grid_config_rec_type
CONTAINS
EOF
cat extract_compute_diff_metrics.f90 >> uh_oracle_mod.F90
echo "" >> uh_oracle_mod.F90
cat extract_cal_helicity.f90 >> uh_oracle_mod.F90
cat >> uh_oracle_mod.F90 <<'EOF'

END MODULE uh_oracle_mod
EOF

# --- the reference build: -O0, no vectoriser ---------------------------------
gfortran -c -O0 -ffree-form -ffree-line-length-none uh_oracle_mod.F90
gfortran -c -O0 -ffree-form -ffree-line-length-none \
    -I "${build_dir}" "${script_dir}/run_cal_helicity.F90"
gfortran -o run_cal_helicity uh_oracle_mod.o run_cal_helicity.o

# --- libmvec guard (ysu-oracle pattern) --------------------------------------
nm -u uh_oracle_mod.o | sed 's/^ *//' | sort > undefined-O0.txt
if grep -q '_ZGV' undefined-O0.txt; then
    echo "-O0 object pulled in a libmvec vector symbol:" >&2
    grep '_ZGV' undefined-O0.txt >&2
    exit 4
fi
if grep -Eq 'expf|powf|logf|sqrtf|cbrtf|atanf' undefined-O0.txt; then
    echo "unexpected libm symbol in the -O0 object (the two subroutines are" \
         "pure arithmetic):" >&2
    grep -E 'expf|powf|logf|sqrtf|cbrtf|atanf' undefined-O0.txt >&2
    exit 4
fi

gfortran -c -O2 -ftree-vectorize -ffree-form -ffree-line-length-none \
    -o uh_oracle_mod_O2vec.o uh_oracle_mod.F90
nm -u uh_oracle_mod_O2vec.o | sed 's/^ *//' | sort > undefined-O2vec.txt
gfortran -c -Ofast -ftree-vectorize -ffree-form -ffree-line-length-none \
    -o uh_oracle_mod_Ofast.o uh_oracle_mod.F90
nm -u uh_oracle_mod_Ofast.o | sed 's/^ *//' | sort > undefined-Ofast.txt

gfortran -c -Ofast -ftree-vectorize \
    -o libmvec_positive_control.o "${script_dir}/libmvec_positive_control.F90"
nm -u libmvec_positive_control.o | sed 's/^ *//' | sort > undefined-control.txt
if ! grep -q '_ZGV' undefined-control.txt; then
    echo "libmvec positive control produced no _ZGV symbol; the guard is" \
         "vacuous on this toolchain" >&2
    cat undefined-control.txt >&2
    exit 5
fi

{
    echo "# gfortran: $(gfortran --version | head -1)"
    echo "# glibc:    $(ldd --version | head -1)"
    echo "# -O0 libm/libmvec symbols (THE REFERENCE; empty = pure arithmetic):"
    grep -E 'expf|powf|logf|sqrtf|cbrtf|_ZGV' undefined-O0.txt || true
    echo "# -O2 -ftree-vectorize:"
    grep -E 'expf|powf|logf|sqrtf|cbrtf|_ZGV' undefined-O2vec.txt || true
    echo "# -Ofast -ftree-vectorize:"
    grep -E 'expf|powf|logf|sqrtf|cbrtf|_ZGV' undefined-Ofast.txt || true
    echo "# positive control (plain expf loop at -Ofast), proves the grep works:"
    grep -E 'expf|_ZGV' undefined-control.txt || true
} > libmvec-report.txt
cat libmvec-report.txt

# --- run ----------------------------------------------------------------------
./run_cal_helicity uh-inputs.csv uh-outputs.csv

# The receipt ships inside the wheel (woof/data/uh/oracle/), so the
# names must be machine-neutral: the checkout-resident source is
# recorded under the <oracle-workspace> placeholder, never under this
# machine's absolute path.
sha256sum module_diffusion_em.pinned.F \
    extract_compute_diff_metrics.f90 extract_cal_helicity.f90 \
    uh_oracle_mod.F90 "${script_dir}/run_cal_helicity.F90" \
    uh-inputs.csv uh-outputs.csv \
    | sed "s|  ${script_dir}/|  <oracle-workspace>/tools/uh_wrf461_oracle/|" \
    > oracle-sha256sums.txt
gfortran --version | head -1 > compiler.txt
echo "uh oracle built in ${build_dir}"
