#!/usr/bin/env python3
"""Regenerate the wrfout global-attribute-set golden from the writer.

The golden in ``tests/data/wrfout_global_attribute_set_v1.json`` is a
conformance contract: the exact SET of global attributes a frame carries
when it is written through ``woof.runtime._global_wrf_attrs`` and
``woof.io.wrfout.WrfoutWriter``.  It has never been authored by hand and
must not be -- a hand-edited set records what somebody believed the
writer does, which is precisely the thing the guard exists to check.

So this tool does not build the set.  It imports the guard's OWN frame
writer (``tests/test_wrfout_global_attribute_set._write_production_frame``)
and reads the names back off the emitted NETCDF4_CLASSIC files with
netCDF4, exactly as the assertions do.  There is one production path and
both the tool and the test walk it.

Two shapes are recorded, because the emitted set legitimately has two:

* ``global_attributes`` -- no source receipt (idealized cases, and any
  preparation route that publishes no initial-condition provenance).
* ``global_attributes_with_initial_condition`` -- a front-door-prepared
  run, which additionally states what its initial state WAS.

Names only, never values: the set is a schema contract and must carry no
case data.

    python tools/regenerate_wrfout_global_attribute_set.py [--check]

``--check`` regenerates into a temporary directory and diffs, exiting 1
on drift without writing -- for use where the golden must not move.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import sys
import tempfile
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))


def _load_guard():
    """Import the guard module by path -- ``tests`` is not a package."""

    path = _REPO_ROOT / "tests" / "test_wrfout_global_attribute_set.py"
    spec = importlib.util.spec_from_file_location(
        "gpuwm_wrfout_attribute_set_guard", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


_GUARD = _load_guard()
_GOLDEN_PATH = _GUARD._GOLDEN_PATH
PROVENANCE = _GUARD.PROVENANCE
_emitted_global_attribute_set = _GUARD._emitted_global_attribute_set
_write_production_frame = _GUARD._write_production_frame

_NOTE = (
    "Exact global-attribute SET a wrfout frame carries when written "
    "through woof.runtime._global_wrf_attrs and "
    "woof.io.wrfout.WrfoutWriter.  Generated by "
    "tools/regenerate_wrfout_global_attribute_set.py, which drives the "
    "guard's own production frame writer and reads the set back off the "
    "emitted NETCDF4_CLASSIC file; not authored.  Two shapes, because a "
    "run whose preparation published an initial-condition receipt states "
    "what its initial state WAS as well as when its clock began.  Names "
    "only -- no values -- so the set is a conformance contract and "
    "carries no case data."
)


def regenerate(workdir: Path) -> dict[str, object]:
    plain = _emitted_global_attribute_set(_write_production_frame(
        workdir / "wrfout_d02_plain.nc"))
    provenance = _emitted_global_attribute_set(_write_production_frame(
        workdir / "wrfout_d02_provenance.nc",
        initial_condition=PROVENANCE, source="gfs"))
    return {
        "_note": _NOTE,
        "schema": "gpuwm.wrfout-global-attribute-set/v1",
        "producer": ("woof.runtime._global_wrf_attrs + "
                     "woof.io.wrfout.WrfoutWriter"),
        "attribute_count": len(plain),
        "attribute_count_with_initial_condition": len(provenance),
        "global_attributes": sorted(plain),
        "global_attributes_with_initial_condition": sorted(provenance),
    }


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true",
        help="report drift and exit 1 instead of writing the golden")
    args = parser.parse_args(argv)

    with tempfile.TemporaryDirectory() as tmp:
        payload = regenerate(Path(tmp))
    rendered = json.dumps(payload, indent=1, sort_keys=False) + "\n"

    if args.check:
        current = _GOLDEN_PATH.read_text(encoding="utf-8")
        if current != rendered:
            print(f"{_GOLDEN_PATH} is stale; rerun without --check",
                  file=sys.stderr)
            return 1
        print(f"{_GOLDEN_PATH} is current")
        return 0

    _GOLDEN_PATH.write_text(rendered, encoding="utf-8")
    print(f"wrote {_GOLDEN_PATH} "
          f"({payload['attribute_count']} attributes, "
          f"{payload['attribute_count_with_initial_condition']} with "
          "initial-condition provenance)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
