! Harness stand-ins for the framework names WRF v4.7.1's ndown rebalance
! (dyn_em/module_initialize_real.F:4982-5266) and blend_terrain
! (dyn_em/nest_init_utils.F:712-785) reference and that carry no number the
! two routines compute with.
!
! * module_state_description and module_driver_constants are GENERATED by
!   WRF's Registry tool; only P_QV, num_moist, PARAM_FIRST_SCALAR and the
!   data-order codes are read here, with the values an EM build generates
!   (DATA_ORDER_XZY is the em_real order).
! * module_configure carries the two configuration records the routines
!   read: grid_config_rec_type's use_theta_m and use_baseparam_fr_nml, and
!   the two namelist getters blend_terrain calls.  The harness sets them.
! * module_domain carries TYPE(domain) with exactly the components the two
!   routines dereference, allocated by the driver with WRF's memory bounds.
! * wrf_message / wrf_debug / wrf_error_fatal / const_module_initialize are
!   the framework's message and namelist-constant entry points; the fatal
!   one stops the program, and const_module_initialize is never reached
!   (use_baseparam_fr_nml is false: the base-state constants come from the
!   input, as ndown reads them from the parent's wrfout).

MODULE module_driver_constants
   IMPLICIT NONE
   INTEGER, PARAMETER :: DATA_ORDER_XYZ = 1, DATA_ORDER_YXZ = 2,          &
                         DATA_ORDER_ZXY = 3, DATA_ORDER_ZYX = 4,          &
                         DATA_ORDER_XZY = 5, DATA_ORDER_YZX = 6
   INTEGER, PARAMETER :: model_data_order = DATA_ORDER_XZY
END MODULE module_driver_constants

MODULE module_state_description
   USE module_driver_constants
   IMPLICIT NONE
   INTEGER, PARAMETER :: PARAM_FIRST_SCALAR = 2
   INTEGER, PARAMETER :: P_QV = 2
   INTEGER, PARAMETER :: num_moist = 2
END MODULE module_state_description

MODULE module_wrf_error
   IMPLICIT NONE
   CHARACTER(LEN=256) :: wrf_err_message
END MODULE module_wrf_error

MODULE module_configure
   IMPLICIT NONE
   TYPE grid_config_rec_type
      INTEGER :: use_theta_m = 0
      LOGICAL :: use_baseparam_fr_nml = .FALSE.
   END TYPE grid_config_rec_type
   TYPE(grid_config_rec_type) :: model_config_rec
   INTEGER :: harness_spec_bdy_width = 5
   INTEGER :: harness_blend_width = 5
CONTAINS
   SUBROUTINE model_to_grid_config_rec ( id , model_config , config )
      INTEGER, INTENT(IN) :: id
      TYPE(grid_config_rec_type), INTENT(IN) :: model_config
      TYPE(grid_config_rec_type), INTENT(OUT) :: config
      config = model_config
   END SUBROUTINE model_to_grid_config_rec
   SUBROUTINE nl_get_spec_bdy_width ( id , value )
      INTEGER, INTENT(IN) :: id
      INTEGER, INTENT(OUT) :: value
      value = harness_spec_bdy_width
   END SUBROUTINE nl_get_spec_bdy_width
   SUBROUTINE nl_get_blend_width ( id , value )
      INTEGER, INTENT(IN) :: id
      INTEGER, INTENT(OUT) :: value
      value = harness_blend_width
   END SUBROUTINE nl_get_blend_width
END MODULE module_configure

MODULE module_domain
   IMPLICIT NONE
   TYPE domain
      INTEGER :: id = 2
      INTEGER :: sd31, ed31, sd32, ed32, sd33, ed33
      INTEGER :: sm31, em31, sm32, em32, sm33, em33
      INTEGER :: sp31, ep31, sp32, ep32, sp33, ep33
      INTEGER :: hypsometric_opt
      REAL :: t00, p00, tlp, tiso, p_strat, tlp_strat, p_top
      REAL, ALLOCATABLE :: c1h(:), c2h(:), c3h(:), c4h(:)
      REAL, ALLOCATABLE :: c1f(:), c2f(:), c3f(:), c4f(:)
      REAL, ALLOCATABLE :: dnw(:), rdnw(:), rdn(:)
      REAL, ALLOCATABLE :: ht(:,:), ht_fine(:,:), mub(:,:), mu_2(:,:), psfc(:,:)
      REAL, ALLOCATABLE :: pb(:,:,:), t_init(:,:,:), alb(:,:,:), phb(:,:,:)
      REAL, ALLOCATABLE :: t_2(:,:,:), p(:,:,:), alt(:,:,:), al(:,:,:)
      REAL, ALLOCATABLE :: p_hyd(:,:,:), ph_2(:,:,:), ph0(:,:,:)
   END TYPE domain
END MODULE module_domain

SUBROUTINE wrf_message ( str )
   CHARACTER(LEN=*), INTENT(IN) :: str
END SUBROUTINE wrf_message

SUBROUTINE wrf_debug ( level , str )
   INTEGER, INTENT(IN) :: level
   CHARACTER(LEN=*), INTENT(IN) :: str
END SUBROUTINE wrf_debug

SUBROUTINE wrf_error_fatal ( str )
   CHARACTER(LEN=*), INTENT(IN) :: str
   WRITE (0, '(A)') 'wrf_error_fatal: ' // TRIM(str)
   STOP 1
END SUBROUTINE wrf_error_fatal

SUBROUTINE const_module_initialize ( p00 , t00 , a , tiso , p_strat , a_strat )
   REAL, INTENT(OUT) :: p00 , t00 , a , tiso , p_strat , a_strat
   CALL wrf_error_fatal ( 'const_module_initialize is not part of this oracle' )
END SUBROUTINE const_module_initialize
